### ISSUE TITLE
Stuck on the Login page - Part 2

### ISSUE THREAD

**Issue by tiagojco** [linuxserver/docker-qbittorrent#112]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
After providing default login, should proced to logged page.

## Current Behavior
API Responds with 200 OK, but sends me back to login page.

## Steps to Reproduce

Video: https://youtu.be/iFbd0wvhw9s

## Environment
**OS:**
RaspberrypiOS

**CPU architecture:** arm32
armv7l
uname -a => Linux raspberrypi 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux
cat /etc/debian_version => 10.8

**How docker service was installed:**

docker installed by apt install docker from the distro repo

## Command used to create docker container (run/create/compose/screenshot)

```
docker run -d \
  --name=qbittorrent \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=America/Recife \
  -e WEBUI_PORT="8081" \
  -p 6881:6881 \
  -p 6881:6881/udp \
  -p 8081:8081 \
  -v /opt/qbittorrent:/config \
  -v /home/pi/Downloads:/downloads \
  --restart=always \
  -l traefik.http.services.qbittorrent.loadbalancer.server.port=8081 \
  linuxserver/qbittorrent
```
## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------


@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Your DockerHost is most likely running an outdated version of libseccomp

To fix this, please visit https://docs.linuxserver.io/faq#libseccomp

Some apps might not behave correctly without this

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
QWaitCondition::wait(): cv wait failure: Invalid argument
QWaitCondition::wait(): cv wait failure: Invalid argument
```

**Comment by tiagojco** [comment]
Didnt want to hijack closed issue #109 , but im having the same problem (and a few other users at the issue 109, and this guy: https://superuser.com/questions/1633210/qbittorrent-docker-webui-nothing-happen-on-default-password).

Please disregard the audio at the youtube link provided (bored at my classroom).

Tried option 3 at the FAQ, described at https://docs.linuxserver.io/faq#option-3, to no success.

**Comment by Roxedus** [comment]
What version of docker do you have installed?

**Comment by tiagojco** [comment]
18.09.1, build 4c52b90

**Comment by fraee** [comment]
ooops....The same problem

Docker version:
20.10.5, build 55c4c88

OS:
RaspberrypiOS

uname -a => Linux raspberrypi 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux
cat /etc/debian_version => 10.8

**Comment by Roxedus** [comment]
> 18.09.1, build 4c52b90

Update docker. 
![image](https://user-images.githubusercontent.com/7110194/111760185-b5b9e000-889e-11eb-8d73-bff4e31ea6b3.png)

**Comment by fraee** [comment]
> > 18.09.1, build 4c52b90
> 
> Update docker.
> ![image](https://user-images.githubusercontent.com/7110194/111760185-b5b9e000-889e-11eb-8d73-bff4e31ea6b3.png)

I think it is not the problem of the low version of docker, because I installed the latest version today, and I have the same problem.

**Comment by Roxedus** [comment]
@fraee I yet have to see your logs.

**Comment by fraee** [comment]
> @fraee I yet have to see your logs.

sorry. but ..Looks like my log is the same

```
Catching signal: SIGTERM
Exiting cleanly
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------


@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Your DockerHost is most likely running an outdated version of libseccomp

To fix this, please visit https://docs.linuxserver.io/faq#libseccomp

Some apps might not behave correctly without this

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
QWaitCondition::wait(): cv wait failure: Invalid argument
QWaitCondition::wait(): cv wait failure: Invalid argument
```

**Comment by Roxedus** [comment]
@fraee did you update libseccomp on your host?

**Comment by fraee** [comment]
> @fraee did you update libseccomp on your host?

The update did solve my problem, thank you very much!

**Comment by tiagojco** [comment]
after updating docker to version 20.10.5 the problem is solved.
Thanks @Roxedus
