### ISSUE TITLE
webUI not auto run?

### ISSUE THREAD

**Issue by luoye-fe** [linuxserver/docker-qbittorrent#113]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Steps to Reproduce

1. `docker run xxxx`
2. `docker exec -it qb bash`
3. visit `http://127.0.0.1:8080`, connect refused
4. `/usr/bin/qbittorrent-nox`
5. webui is ok, `欲通过 Web UI 控制 qBittorrent，请访问 http://localhost:8080`

## Environment
**OS:** debian
**CPU architecture:** x86_64
**How docker service was installed:** `apt`

## Command used to create docker container (run/create/compose/screenshot)

`portainer`

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    0
User gid:    0
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
```

**Comment by j0nnymoe** [comment]
Yes it does auto run, see our tests here: https://ci-tests.linuxserver.io/linuxserver/qbittorrent/latest/index.html

Though it's hard to help as you haven't provided near enough information to see why it's not working for you.

**Comment by luoye-fe** [comment]
```bash
# /var/run/s6/etc/cont-init.d/30-config
# xxx
chown -R abc:abc /downloads
# xxx
```

After debugging, it was found that `chown` caused this problem.

If the depth of the file tree is too deep, this step will take a lot of time, so, the next steps cannot be run.

**Comment by luoye-fe** [comment]
#56

**Comment by drizuid** [comment]
possible candidate for 
`find . \! -user abc -exec chown abc:abc{} \+`
from prior discussions, though xargs route may be needed for very deep trees, would need further testing

**Comment by thelamer** [comment]
I don't think this is a bug, I also don't think we should be messing with a large folder of files for perms. We have done so in the past, but in general we should try to shift away from it when possible. 
Users need to be responsible enough to know what they are mounting in has the correct permissions for the application to function.
