### ISSUE TITLE
未能登录

### ISSUE THREAD

**Issue by notjiangjiu** [linuxserver/docker-qbittorrent#115]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
arm32v7设备输入默认密码可以登录

## Current Behavior
arm32v7设备输入默认密码不能登录，输入账户密码后登录页面重新加载，无法进入，且没有任何提示

## Steps to Reproduce

1.尝试换浏览器，未能解决
2.输入密码登录，然后再刷新，未能解决
3.
4.

## Environment
**OS:**2021-01-11-raspios-buster-armhf.img
**CPU architecture:** arm32v7(raspberry4B)
**How docker service was installed:**

**Comment by aptalca** [comment]
English only please. Feel free to use Google Translate: https://translate.google.com/
