### ISSUE TITLE
Latest update breaks WebUI

### ISSUE THREAD

**Issue by stavros-k** [linuxserver/docker-qbittorrent#118]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
WebUI to work correctly

## Current Behavior
Latest realease (14.3.3.99202103241603-7341-f7e6b9649ubuntu20.04.1-ls121) breaks UI. Only the top bar is visible. The rest cuts off. Even menus that expand are cut off. See screeshot.
![image](https://user-images.githubusercontent.com/47820033/112389613-ae129500-8cfd-11eb-9ab1-d9c8798787b6.png)

## Steps to Reproduce

1. Update to the latest release
2. Open webui
3.
4.

## Environment
**OS:** Unraid
**CPU architecture:** x86_64
**How docker service was installed:**
From the App collection of unraid

## Command used to create docker container (run/create/compose/screenshot)
```
docker run -d --name='qbittorrent' --net='bridge' -e TZ="Europe/Athens" -e HOST_OS="Unraid" -e 'PUID'='99' -e 'PGID'='100' -e 'UMASK'='000' -p '6881:6881/tcp' -p '6881:6881/udp' -p '8080:8080/tcp' -v '/mnt/user/downloads/':'/downloads':'rw' -v '/mnt/user/appdata/qbittorrent':'/config':'rw' 'linuxserver/qbittorrent'
```
## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by aptalca** [comment]
Likely this: https://www.qbittorrent.org/news.php

**Comment by leftl** [comment]
looks like a fix has already been released, at least on their sourceforge page (v 4.3.4.1).
in the mean time, I reverted to previous image. here's the tag for other amd64 folks to save you a couple clicks:
`amd64-14.3.3.99202101191832-7248-da0b276d5ubuntu20.04.1-ls120`

**Comment by vawaver** [comment]
The same problem with Web UI here.
I hope the fix will be available here soon. Because I cannot make a rollback.

**Comment by j0nnymoe** [comment]
It will be fixed once they push a new version.

**Comment by stavros-k** [comment]
Update `14.3.3.99202103251603-7345-332b173e0ubuntu20.04.1-ls122` fixes the UI
