### ISSUE TITLE
Docker cannot access any volumes outside of container - Synology DSM 6.3

### ISSUE THREAD

**Issue by ProjectVRD** [linuxserver/docker-qbittorrent#119]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
QBittorrent should have access to all folders listed as volumes

## Current Behavior
QBittorrent displayed Error! for all torrents attempting to save in volumes as set in Options
QBittorrent says "Cannot Make Save Location" when saving 'Set Location...' option

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:** 
DSM 6.3

**CPU architecture:** 
x86_64

**How docker service was installed:** 
Official Docker Application on DSM 6.3

## Command used to create docker container (compose)
version: "3"
services:
  vpn:
    image: bubuntux/nordvpn
    network_mode: bridge        # Required
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun            # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=**********     # Required
      - "PASS=***********"         # Required
      - CONNECT=United_Kingdom
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.0.1/24 
    ulimits:                    # Recommended for High bandwidth scenarios
      memlock:
        soft: -1
        hard: -1
    ports:
      - 8080:8080 # qBittorrent
      - 7878:7878 # Radarr
      - 8989:8989 # Sonar

  torrent:
    image: linuxserver/qbittorrent
    environment:
      - PUID=1026
      - PGID=1000
    volumes:
      - /volume1/Downloads/qBittorrent:/Finished
      - /volume1/docker/handbrake/Watch:/Handbreak
      - /volume1/Downloads/qBittorrent/temp:/Temp
    network_mode: service:vpn
    depends_on:
      - vpn

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=1000
    volumes:
      - /volume1/Downloads/qBittorrent:/Finished
      - /volume1/Downloads/qBittorrent/temp:/Temp
    network_mode: service:vpn
    depends_on:
      - vpn

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1026
      - PGID=1000
    volumes:
      - /volume1/Downloads/qBittorrent:/Finished
      - /volume1/Downloads/qBittorrent/temp:/Temp
    network_mode: service:vpn
    depends_on:
      - vpn

**Comment by j0nnymoe** [comment]
You will only be able to access the folders you've mounted, `/Finished` & `/Temp` but also you've forgotten the `/config` mounts so you'll say bye bye to the configuration each time you update the containers.

**Comment by ProjectVRD** [comment]
> You will only be able to access the folders you've mounted, `/Finished` & `/Temp` but also you've forgotten the `/config` mounts so you'll say bye bye to the configuration each time you update the containers.

Cheers Jonny, done as you suggested using a compose file.
