### ISSUE TITLE
Add Flood UI

### ISSUE THREAD

**Issue by ericvoshall** [linuxserver/docker-qbittorrent#125]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Add [Flood UI](https://flood.js.org) to the QBittorrent image. The Transmission image was recently updated to include Flood UI.

## Current Behavior
Currently just uses the stock web UI.

**Comment by Tan-ki** [comment]
I don't really care about the cosmetic aspect of the UI, but Flood adds mobile support (which is definitly not the case for stock UI), and that is a feature that I miss !
+1

**Comment by Tan-ki** [comment]
Just to emphasize that even if I doubt we will ever get this feature, I'm more and more interested in it :)

**Comment by alexbelgium** [comment]
You might look at [VueTorrent](https://github.com/WDaan/VueTorrent), much easier to implement and just as nice :) I made a Home Assistant addon based on this ls container which includes VueTorrent as default ui and it is quite nice : mobile friendly and aesthetic

**Comment by TheSpad** [comment]
It's not something we're likely to bundle. You could do it as a [docker mod](https://github.com/linuxserver/docker-mods/) or use the standalone [Flood container](https://hub.docker.com/r/jesec/flood/) to hook into qbittorrent.
