### ISSUE TITLE
Per interface restictions not working?

### ISSUE THREAD

**Issue by hardwareadictos** [linuxserver/docker-qbittorrent#126]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I'm using Advanced tab interface settings to restrict downloads on a wifi interface i have on my Debian Host, container is on host network mode to have host interfaces visibility. Seems that this option is being ignored as downloads are being made throw my ethernet adapter.

## Expected Behavior
Qbittorrent respecting interface settings on Advanced tab
## Current Behavior
Qbittorrent using ethernet adapter for downloading while wifi adapter is being set on Advanced tab settings

## Steps to Reproduce

Just setting any interface on Advanced tab, qbittorrent still uses ethernet adapter

## Environment
**OS:** Debian 10
**CPU architecture:** x86_64
**How docker service was installed:**Official Docker repo for Debian 10

## Command used to create docker container (run/create/compose/screenshot)
docker-compose up -d

version: "2.1"
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=8080
    volumes:
      - ./config:/config
      - /mnt/Rasputin-DATA/qbittorrent:/downloads

    network_mode: host
    restart: unless-stopped

## Docker logs

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

![image](https://user-images.githubusercontent.com/20403906/119549756-d79c7b00-bd97-11eb-9774-a21a493859fd.png)

**Comment by homerr** [comment]
This is right, the container has no idea about your other interfaces... if you want to have it doing certain things over different interfaces that's a bit niche - and not something I have experience in - you may be best discussing it in discord.
