### ISSUE TITLE
Monitored Folders no longer working

### ISSUE THREAD

**Issue by glc650** [linuxserver/docker-qbittorrent#127]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Monitored Folders used to work

## Current Behavior
.torrent/.magnet files added to my Monitored Folder no long get auto added to qbittorrent.  Last worked as expected a few weeks ago.

## Steps to Reproduce
1.  Add torrents to Monitored Folder via jackett or manually.
2.  qbittorrent ignores them (doesn't add them to queue).

## Environment
**OS:** Ubuntu 20.04.2 LTS
**CPU architecture:** x86_64
**How docker service was installed:** from the official docker repo

## Command used to create docker container (run/create/compose/screenshot)
docker-compose up

## Docker logs
`
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
`

**Comment by homerr** [comment]
I've had a look and can't see any changes in the container around the time you raised the issue... can only assume there may be a problem docker or system side. Sounds silly but have you tried a restart? A bit odd it's stopped working with nothing changing.

**Comment by glc650** [comment]
Restarting was one of the first things I tried.

I ended up changing my monitored folder from a shared network folder on my NAS to a local folder.  Still have no idea why it stopped working when it worked for months before changing to local folder.

**Comment by homerr** [comment]
Interesting, I have found docker sometimes do odd stuff with networked file storage before so this doesn't surprise me. Glad it's working, will close this issue down.
