### ISSUE TITLE
Container random disconnection in minutes to hours after restart

### ISSUE THREAD

**Issue by kshshpsh** [linuxserver/docker-qbittorrent#128]
Container random disconnection in minutes to hours after restart

------------------------------

## Expected Behavior
After the container has been restarted for some time, the container cannot be accessed and the torrents cannot be linked

## Environment
**OS:Synology DSM 6.2.3-25423
**CPU architecture:** x86_64
**How docker service was installed:**
nas OS provided

## Command used to create docker container (run/create/compose/screenshot)

![Snipaste_2021-07-14_23-58-18](https://user-images.githubusercontent.com/26866347/125653755-22a04136-8185-4bcc-86e7-7379d3cc633d.png)

## Docker logs

double free or corruption (!prev)
 *************************************************************
 Please file a bug report at http://bug.qbittorrent.org and provide the following information: 
qBittorrent version: v4.3.5 
Caught signal: SIGABRT 
Stack trace:

**Comment by homerr** [comment]
Are you able to get logs out of the NAS which might help with this? Do you have a lot of things running on the NAS that could be exhausting resources?

**Comment by kshshpsh** [comment]
@homerr I can't find any docker-qbittorrent log in NAS log，but I run 5k+ torrents in docker-qbittorrent. Almost a month ago,it was working normally.
And now,I'm using the qbittorrent.spk,4.3.7,everything is right.
