### ISSUE TITLE
Adding umask parameter in environment don't work

### ISSUE THREAD

**Issue by ShakesBill** [linuxserver/docker-qbittorrent#132]
I added  umask=002 in environment settings following the guide, after reboot the docker , nothing changed.
when I use "docker exec" open the docker and type "umask" , still the old umask number 
anything wrong? 

![微信截图_20210804165153](https://user-images.githubusercontent.com/26357378/128153125-b964df62-b967-490a-a77b-8a8d371b2be3.jpg)

**Comment by JJJason1133** [comment]
The version is the latest

**Comment by Roxedus** [comment]
Check by running the shell as user abc. `docker exec -it -u abc qbittorrent umask`
