### ISSUE TITLE
WebUI does not load configuration correctly

### ISSUE THREAD

**Issue by quinnjr** [linuxserver/docker-qbittorrent#134]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
The WebUI after a docker pull should correctly load the information from a previous installation of the container. This is not true for builds after `14.3.6.99202107121017-7389-3ac8c97e6ubuntu20.04.1-ls148.` Prior to those updates, the container works correctly with showing previously loaded torrents in the WebUI.

## Current Behavior
Currently, no previously loaded torrents show in the WebUI. Also, new torrents being added are not displayed in the WebUI once loaded.

## Steps to Reproduce
1. Run `docker pull` on the latest images to update
2. Relaunch the container using `docker-compose up -d`
3. Observer that no torrents are loading in the WebUI
4. Run `docker pull` on a previously working image
5. Relaunch the container using `docker-compose up -d`, but with the image specified as the previous working image.
6. See torrents properly being loaded from disk in the WebUI.

## Environment
**OS**: Linux
**CPU architecture:** x86_64/
**How docker service was installed:**
Official installation from Synology NAS.

## Command used to create docker container (run/create/compose/screenshot)

`docker-compose up -d`

## Docker logs

No errors are shown in the docker logs.

**Comment by hadim** [comment]
I am seeing the same bug.

**Comment by quinnjr** [comment]
This seems to be fixed in 14.3.8.99202109100310-7422-338d9a084ubuntu20.04.1-ls155
