### ISSUE TITLE
Unstable version tag is pulling an older version (v4.4.0alpha1) - latest is v4.4.0beta3?

### ISSUE THREAD

**Issue by victorhooi** [linuxserver/docker-qbittorrent#135]
I am using the "unstable" version tag, and it appears to be pulling an older version of qbittorrent - specifically I’m getting qBittorrent v4.4.0alpha1, whereas there is [v4.4.0beta3](https://github.com/qbittorrent/qBittorrent/releases/tag/release-4.4.0beta3) (released on August 29).

Do you have any idea why this might be?

Also, I assume we’re pulling packages from [this PPA](https://launchpad.net/~qbittorrent-team/+archive/ubuntu/qbittorrent-unstable) for unstable -however, it’s unclear from the PPA how we reference that?

**Comment by TheSpad** [comment]
The issue is that `qbittorrent_4.4.0~202106230113-7327-124cc9621~ubuntu20.04.1` is the last build for Focal (20.04), which is what our container is based on. All subsequent builds have been for 20.10 or 21.04 only.

If they're not building packages for Focal, we can't install them.

**Comment by victorhooi** [comment]
Aha - that would explain it - thank you for the explanation.

What would be involved to moving the base to a newer Ubuntu version? (20.10 or 21.04)

**Comment by TheSpad** [comment]
We likely won't move base until the next LTS release, which will be 22.04 next spring.
