### ISSUE TITLE
Torrents stuck on 'retrieving metadata' unless I restart the computer

### ISSUE THREAD

**Issue by doobersn** [linuxserver/docker-qbittorrent#137]
Hi, I have a MacBook Air m1 and the newest version of qbittorrent. Unless I restart the computer, the magnet will not retrieve metadata. If dont download it the first time or open any other torrents thereafter, unless I restart the MacBook it will not retrieve metadata. Ideas? Thanks!

**Comment by almico** [comment]
I opened [this issue](https://github.com/alexbelgium/hassio-addons) on another repository that should be using this docker image, and I am facing the very same issue.

**Comment by maisondasilva** [comment]
Same here

**Comment by drizuid** [comment]
issue template was not filled out
