### ISSUE TITLE
Automatic adding torrents from a monitored folder not working

### ISSUE THREAD

**Issue by ashrhmn** [linuxserver/docker-qbittorrent#139]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I have set a folder to be monitored to auto add torrent files from that folder to download queue from the web ui settings. When I put a .torrent file inside that folder client should auto pickup the file and add to download queue

## Current Behavior

For now client does not detect any new file inside that monitored folder until the container is restarted

## Steps to Reproduce

1. Start container as directed in README 
2. Head to port 8080, login, open tools from menu bar, then options and then downloads. From that tab add folders in 'Automatically add torrents' section
3. Now put a .torrent file in the specified folder and download does not start automatically
4.

## Environment
**OS:**
**CPU architecture:** x86_64
**How docker service was installed:**

Using Docker for windows from official website

## Command used to create docker container (run/create/compose/screenshot)

version: "3"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
      - WEBUI_PORT=8080
    volumes:
      - ./app/config:/config
      - ./Downloads/:/downloads
      - ./AutoAdd/:/autoadd
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped

## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by EricTousignant** [comment]
I see the same issue as the original poster.

**Comment by szongi** [comment]
I have the same problem.

**Comment by Nev-eee** [comment]
I have the same issue, except I am using dyonr/qbittorrentvpn. I believe the root issue is something to do with qbittorrent in docker though.

**Comment by drizuid** [comment]
Unfortunately, this issue is an upstream one (which has hopefully been resolved in recent versions. This is not something we can fix.
