### ISSUE TITLE
Cannot change qBittorrent.conf file - it gets overwritten after container restart

### ISSUE THREAD

**Issue by ikesler** [linuxserver/docker-qbittorrent#141]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I'd like to make some adjustments to qBittorrent.conf file. Please see compose file below. I'm editing `/v/qbittorrent/config/qBittorrent/qBittorrent.conf` file from the host. Using Ubuntu 20 server host and nano editor. Changes I make do not survive container restart - file it reset to the defaults.

------------------------------

## Expected Behavior
qBittorrent.conf which is persisted in a volume must not be overwritten upon container restart. All manual changes there must be preserved.

## Current Behavior
qBittorrent.conf which is persisted in the volume gets overwritten each time container restarts.

## Steps to Reproduce
1. Run the service from the compose file below
2. Run `nano /v/qbittorrent/config/qBittorrent/qBittorrent.conf` on the host
3. Add some changes to the file and save it
3. Restart container by calling `docker container restart qbittorrent`
4. Check config file `nano /v/qbittorrent/config/qBittorrent/qBittorrent.conf`

## Environment
**OS:** Ubuntu 20.10 (server)
**CPU architecture:** x86_64
**How docker service was installed:** from the official docker repo

## Command used to create docker container (run/create/compose/screenshot)
```
version: "2.1"
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - WEBUI_PORT=8181
    volumes:
      - /v/qbittorrent/config:/config
      - /v/qbittorrent/downloads:/downloads
    restart: unless-stopped
```

## Docker logs

```
******** Information ********
To control qBittorrent, access the Web UI at http://localhost:8181
The Web UI administrator username is: admin
The Web UI administrator password is still the default one: adminadmin
This is a security risk, please consider changing your password from program preferences.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by Roxedus** [comment]
Try stopping the container before saving the file, as qbit writes to the file on shutdown

**Comment by ikesler** [comment]
> Try stopping the container before saving the file, as qbit writes to the file on shutdown

This is the case. Thanks a lot!

**Comment by Alcedema** [comment]
I am having the same issue from 4.4.1 all the way to 4.4.5. 

Any changes to the qBittorrent.conf file made by qbittorrent itself are wiped on container restart. I even chmod 444 the file but it was re-created.with default config with rw-r-r permissions. Nothing is preserved when the container is pulled or upgraded by watchtower even when volume is mapped and persistent and uid/gid are set correctly. All torrents are maintained, it's just the .conf file so anything like folder mapping on completion and bit torrent queue settings are defaulted every time.

**Comment by thespad** [comment]
You can see the logic here https://github.com/linuxserver/docker-qbittorrent/blob/master/root/etc/s6-overlay/s6-rc.d/init-qbittorrent-config/run#L7, we don't touch the file if it already exists

**Comment by Alcedema** [comment]
![Screenshot_2022-11-22-15-39-52-03_61c78dc80ee02b53007c815fefe993e3.jpg](https://user-images.githubusercontent.com/4752277/203356819-457ff51e-4f7a-42db-a702-8c97310bb601.jpg)

Here I show the conf file in /config (host). It exists before container restart. It is removed during the restart process and is therefore created default as it loads.

**Comment by Alcedema** [comment]
`qbittorrent:

    image: lscr.io/linuxserver/qbittorrent:4.4.1

    container_name: qbittorrent

    network_mode: service:piawg

    volumes:

        - /etc/docker/qbittorrent:/config

        - /mnt/media/Downloads:/downloads

    restart: always

    environment:

        - PUID=1000

        - PGID=1000

        - TZ=Europe/London

        - WEBUI_PORT=8080
        
`

Same with :latest (4.4.5) too.

**Comment by Roxedus** [comment]
There is no code in our image that does that. it will only copy a default one, if there is no exiting file.

**Comment by Alcedema** [comment]
I don't know what to say.. I'm using your image but when it starts, the /config/qBittorrent/qBittorrent.conf is removed.

When I stopped the container the file persisted so it's definitely when loading the container. 

Is there a debug option so I can see why the file is being removed? The directory is left alone, just this config file is the issue.

**Comment by j0nnymoe** [comment]
Maybe it's a permissions thing that when the container is starting, it think it's not there and forcefully replacing anyways. 
To test, use `/home/dietpi/appdata/qbittorrent` and see what happens.

**Comment by Alcedema** [comment]
Thank you! Looks like that was the issue. .conf file and new settings have persisted. 

Strange that this was the only image that had this problem. Will be moving everything to home directory. 

Thanks!

**Comment by Skamba** [comment]
In case anyone ends up here and made the same dumb mistake:

In the default docker-compose file there's a -WEBUI_PORT=8080 parameter under environment. If that's set, it will overwrite your config. So change it in your docker compose rather than in the config file.

**Comment by lslatr23** [comment]
> In case anyone ends up here and made the same dumb mistake:
> 
> In the default docker-compose file there's a -WEBUI_PORT=8080 parameter under environment. If that's set, it will overwrite your config. So change it in your docker compose rather than in the config file.

Yes, I had to add new variable into the container environment, now it works. The port in config file gets overwritten by the port set in WEBUI_PORT on container start.

**Comment by C9312B4DC0** [comment]
Ran into this issue today. `WEBUI_PORT` wouldn't work until I used `WEBUI_PORTS=80/tcp,80/udp`

**Comment by danieljrich** [comment]
I'll add to this for anyone else running a kubernetes cluster and having this issue. Though I'm sure this would work on any docker instance.

1. exec onto the container and edit qBittorrent.conf
2. `ps aux` note the PID of qbittorrent-nox
3. `kill -9 <qbit_pid>`
4. That's it! the supervisor on the container will auto restart qbit, so you don't even need to restart it.


As stated by others, qbit writes to the conf file on shutdown. A kill 9 isn't a graceful shutdown.

**Comment by phillijw** [comment]
> I'll add to this for anyone else running a kubernetes cluster and having this issue. Though I'm sure this would work on any docker instance.
> 
>     1. exec onto the container and edit qBittorrent.conf
> 
>     2. `ps aux` note the PID of qbittorrent-nox
> 
>     3. `kill -9 <qbit_pid>`
> 
>     4. That's it! the supervisor on the container will auto restart qbit, so you don't even need to restart it.
> 
> 
> As stated by others, qbit writes to the conf file on shutdown. A kill 9 isn't a graceful shutdown.

Ah! The `-9` is what I was missing. This ended up being what worked for me:

```
# rm qBittorrent.conf && cp qBittorrent.conf.fixed qBittorrent.conf && kill -9 410
```

**Comment by gushrdev** [comment]
> Try stopping the container before saving the file, as qbit writes to the file on shutdown

I want you to know you saved me so much time! I was sitting here so confused for so long. I read this comment, verified that it wasn't saving, did a stop, edited the file, followed it with a restart and it worked! :D

**Comment by aptalca** [comment]
> Is this ever going to get fixed or is it going to be written off as a feature not a bug? If you set a password and/or rename the account it clobbers your change ever since this "feature" was added. The whole user auth scheme is a total mess, but that's another story

The solution was provided and confirmed by both the op and other users.

https://github.com/linuxserver/docker-qbittorrent/issues/141#issuecomment-993955133

It's not a bug or a feature per se. It's just a design choice the upstream project made where the settings are read from the config file on start and current active settings are written to the config file on shut down. It is what it is.
