### ISSUE TITLE
libQt5Core.so.5 apparently missing or permission issues

### ISSUE THREAD

**Issue by kozmaz87** [linuxserver/docker-qbittorrent#142]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

![image](https://user-images.githubusercontent.com/4070837/146577348-d821c460-3af2-4af2-8727-89e78b9e4910.png)

------------------------------

## Expected Behavior
no errors flooding the log would be nice

## Current Behavior
errors flooding the log
## Steps to Reproduce

1. LAunch the latest
2.
3.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by j0nnymoe** [comment]
Already explained in the application setup of the readme (under the webui section).

**Comment by kozmaz87** [comment]
This is not the reason. An so file is missing and the configuration mentioned in the readme has been applied and it still breaks,

**Comment by j0nnymoe** [comment]
No this is kernel related, as explained in the issue.

**Comment by j0nnymoe** [comment]
https://github.com/linuxserver/docker-qbittorrent/issues/103#issuecomment-831238484

**Comment by kozmaz87** [comment]
Yet other people could make a working container that does not require any sorcery. such as this...  https://hub.docker.com/r/80x86/qbittorrent

**Comment by TheSpad** [comment]
They're building from source with custom build options, our container uses the qbittorrent-provided repo package because otherwise every build take 2-3 hours.

**Comment by kozmaz87** [comment]
Right... it is very odd that this would be a thing... so apparently synology would be better off updating their kernel anyways... thanks anyway.
