### ISSUE TITLE
Number of peers in status summary (seeding only) does not match actual peers.

### ISSUE THREAD

**Issue by jipsterious** [linuxserver/docker-qbittorrent#143]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Number of peers in summary should equal total number of peers (unique?) in tracker tab.  I noticed this issue only appears in seeding torrents.

## Current Behavior
In seeding mode, the number of peers in the summary shows a non-zero value but is 0 in the tracker update.

## Steps to Reproduce
It is not something that can be reproduced.  It's better with a screenshot provided below.
[Screenshot](https://imgur.com/plFGHJX).

## Environment
**OS:** Synology NAS
**CPU architecture:** x86_64
**How docker service was installed:**
NAS OS

## Command used to create docker container (run/create/compose/screenshot)
Not relevant?

## Docker logs
Not relevant?

**Comment by Roxedus** [comment]
Sounds like a bugreport for qbiittorrent
