### ISSUE TITLE
All torrents errord with error: error: No such device

### ISSUE THREAD

**Issue by switchboy** [linuxserver/docker-qbittorrent#150]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Since updating the docker images to the latest image| linuxserver/qbittorrent:latest@sha256:0401cc86f30009c2772f88bde71a5e694a1ebb726593940b7460e99cfa616140

All newly added torrents fail to start. The files of the torrent are succesfully created in the correct folder but logs say:

(N) 2022-01-12T08:50:49 - 'torrentname' added to download list.
(N) 2022-01-12T08:50:49 - Couldn't enqueue move of "torrentname" from "/downloads/incomplete/" to "/downloads/incomplete". Both paths point to the same location.
(W) 2022-01-12T08:50:50 - File error alert. Torrent: "torrentname". File: "/downloads/incomplete/torrentname". Reason: torrentname file_open (/downloads/incomplete/torrentname/torrentfilename.extension) error: No such device

I can read and write from the docker container to the directory. Did a redownload of the image did a reboot of the server no dice...

------------------------------

## Expected Behavior
Start downloading the torrent

## Steps to Reproduce
1. Update previous container to the current lates
2. add any torrent
3. See it fail

## Environment
**OS: OPENMEDIAVAULT 5.6.23-1 kernel 5.10.0.0.bpp.5-AMD64
**CPU architecture:** x86_64
**How docker service was installed:** OMV extra's

## Command used to create docker container (run/create/compose/screenshot)

Portainer

    Home
    local
    Dashboard

App Templates
Stacks
Containers
Images
Networks
Volumes
Events
Host
Settings
Users
Environments
Registries
Authentication logs

    Settings

Portainer 2.11.0
Container inspect admin
Containers > qtorrent > Inspect
my account log out
Inspect

{
    "AppArmorProfile": "docker-default",
    "Args": [],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": null,
        "Domainname": "",
        "Entrypoint": [
            "/init"
        ],
        "Env": [
            "PUID=1000",
            "PGID=100",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "HOME=/config",
            "LANGUAGE=en_US.UTF-8",
            "LANG=en_US.UTF-8",
            "TERM=xterm",
            "XDG_CONFIG_HOME=/config",
            "XDG_DATA_HOME=/config",
            "PS1=$(whoami)@$(hostname):$(pwd)\\$ "
        ],
        "ExposedPorts": {
            "6881/tcp": {},
            "6881/udp": {},
            "8080/tcp": {}
        },
        "Hostname": "Apollo.WORKGROUP",
        "Image": "linuxserver/qbittorrent:latest",
        "Labels": {
            "build_version": "Linuxserver.io version:- 14.3.0.99202011251333-7141-587688634ubuntu18.04.1-ls103 Build-date:- 2020-12-02T00:03:08-05:00",
            "maintainer": "sparklyballs, thelamer",
            "org.opencontainers.image.authors": "linuxserver.io",
            "org.opencontainers.image.created": "2021-04-18T08:01:04+00:00",
            "org.opencontainers.image.description": "The [Qbittorrent](https://www.qbittorrent.org/) project aims to provide an open-source software alternative to µTorrent. qBittorrent is based on the Qt toolkit and libtorrent-rasterbar library.",
            "org.opencontainers.image.documentation": "https://docs.linuxserver.io/images/docker-qbittorrent",
            "org.opencontainers.image.licenses": "GPL-3.0-only",
            "org.opencontainers.image.ref.name": "45fcca6ea96af7cf924ae569946e339b32616697",
            "org.opencontainers.image.revision": "45fcca6ea96af7cf924ae569946e339b32616697",
            "org.opencontainers.image.source": "https://github.com/linuxserver/docker-qbittorrent",
            "org.opencontainers.image.title": "Qbittorrent",
            "org.opencontainers.image.url": "https://github.com/linuxserver/docker-qbittorrent/packages",
            "org.opencontainers.image.vendor": "linuxserver.io",
            "org.opencontainers.image.version": "14.3.4.99202104180633-7350-2c8f322afubuntu20.04.1-ls127"
        },
        "OnBuild": null,
        "OpenStdin": false,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": {
            "/config": {},
            "/downloads": {}
        },
        "WorkingDir": ""
    },
    "Created": "2022-01-09T13:07:21.288852663Z",
    "Driver": "overlay2",
    "ExecIDs": null,
    "GraphDriver": {
        "Data": {
            "LowerDir": "/var/lib/docker/overlay2/22ad808ab4942cadfe623f0f9a0cc2a3ef57b171bfad7d9131bca667ca61f373-init/diff:/var/lib/docker/overlay2/22321945c59127cbc81395d3b040e8691966c677d58c9743090ab4ea75433d0e/diff:/var/lib/docker/overlay2/97772a8f62881dd84c2bc820086e781ea69c03d2aaa892aec357f4e8f210aa37/diff:/var/lib/docker/overlay2/11edcf148e8bb05567bc93730263cf708dd8d2274e96c0c461765ef2c4cd067b/diff:/var/lib/docker/overlay2/76e4b40469c185cff45337d33a246f23bb455b47a79d72a66e80a6a6eabb0c65/diff:/var/lib/docker/overlay2/21618e58aecdc664b69fed40977994e087a0013adc67c726400b5c308db1fcfe/diff:/var/lib/docker/overlay2/d90e9925aeb5e7bcd4c0fc2ca252974c4323c0ed18f57ba70d6aa97a985443b3/diff:/var/lib/docker/overlay2/10d1215b92a9bae6213fc09ceee445a8122d500bdf7a1f222af9a78739d8bcbf/diff:/var/lib/docker/overlay2/e57a6bd6b6b2a4ee1cc6ebce656b5ff240f8093c7942e89698451a808bc93bad/diff:/var/lib/docker/overlay2/c3f97df7a4c395348a8dd694775c2f8974112535bda0aa41cd34cb9a811da957/diff:/var/lib/docker/overlay2/20567a430740548c36c6468d0254bf894bf05ebaa27a4c531d85b28b2fef24a3/diff",
            "MergedDir": "/var/lib/docker/overlay2/22ad808ab4942cadfe623f0f9a0cc2a3ef57b171bfad7d9131bca667ca61f373/merged",
            "UpperDir": "/var/lib/docker/overlay2/22ad808ab4942cadfe623f0f9a0cc2a3ef57b171bfad7d9131bca667ca61f373/diff",
            "WorkDir": "/var/lib/docker/overlay2/22ad808ab4942cadfe623f0f9a0cc2a3ef57b171bfad7d9131bca667ca61f373/work"
        },
        "Name": "overlay2"
    },
    "HostConfig": {
        "AutoRemove": false,
        "Binds": [
            "/srv/dev-disk-by-label-SSData/config/qtorrent:/config",
            "/srv/50911774-19fb-46b6-bc9e-8cf81623d044/downloads:/downloads"
        ],
        "BlkioDeviceReadBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceWriteIOps": null,
        "BlkioWeight": 0,
        "BlkioWeightDevice": null,
        "CapAdd": [
            "AUDIT_WRITE",
            "CHOWN",
            "DAC_OVERRIDE",
            "FOWNER",
            "FSETID",
            "KILL",
            "MKNOD",
            "NET_BIND_SERVICE",
            "NET_RAW",
            "SETFCAP",
            "SETGID",
            "SETPCAP",
            "SETUID",
            "SYS_CHROOT"
        ],
        "CapDrop": [
            "AUDIT_CONTROL",
            "BLOCK_SUSPEND",
            "DAC_READ_SEARCH",
            "IPC_LOCK",
            "IPC_OWNER",
            "LEASE",
            "LINUX_IMMUTABLE",
            "MAC_ADMIN",
            "MAC_OVERRIDE",
            "NET_ADMIN",
            "NET_BROADCAST",
            "SYSLOG",
            "SYS_ADMIN",
            "SYS_BOOT",
            "SYS_MODULE",
            "SYS_NICE",
            "SYS_PACCT",
            "SYS_PTRACE",
            "SYS_RAWIO",
            "SYS_RESOURCE",
            "SYS_TIME",
            "SYS_TTY_CONFIG",
            "WAKE_ALARM"
        ],
        "Cgroup": "",
        "CgroupParent": "",
        "CgroupnsMode": "host",
        "ConsoleSize": [
            0,
            0
        ],
        "ContainerIDFile": "",
        "CpuCount": 0,
        "CpuPercent": 0,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpuShares": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "DeviceCgroupRules": null,
        "DeviceRequests": null,
        "Devices": [],
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "ExtraHosts": [],
        "GroupAdd": null,
        "IOMaximumBandwidth": 0,
        "IOMaximumIOps": 0,
        "Init": false,
        "IpcMode": "private",
        "Isolation": "",
        "KernelMemory": 0,
        "KernelMemoryTCP": 0,
        "Links": null,
        "LogConfig": {
            "Config": {},
            "Type": "json-file"
        },
        "MaskedPaths": [
            "/proc/asound",
            "/proc/acpi",
            "/proc/kcore",
            "/proc/keys",
            "/proc/latency_stats",
            "/proc/timer_list",
            "/proc/timer_stats",
            "/proc/sched_debug",
            "/proc/scsi",
            "/sys/firmware"
        ],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "NanoCpus": 0,
        "NetworkMode": "host",
        "OomKillDisable": false,
        "OomScoreAdj": 0,
        "PidMode": "",
        "PidsLimit": null,
        "PortBindings": {},
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyPaths": [
            "/proc/bus",
            "/proc/fs",
            "/proc/irq",
            "/proc/sys",
            "/proc/sysrq-trigger"
        ],
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "unless-stopped"
        },
        "Runtime": "runc",
        "SecurityOpt": null,
        "ShmSize": 67108864,
        "UTSMode": "",
        "Ulimits": null,
        "UsernsMode": "",
        "VolumeDriver": "",
        "VolumesFrom": null
    },
    "HostnamePath": "/var/lib/docker/containers/946cee105cd62e6483919725936a58f3d79c553cf7ce324c633b5aa32c71ebfc/hostname",
    "HostsPath": "/var/lib/docker/containers/946cee105cd62e6483919725936a58f3d79c553cf7ce324c633b5aa32c71ebfc/hosts",
    "Id": "946cee105cd62e6483919725936a58f3d79c553cf7ce324c633b5aa32c71ebfc",
    "Image": "sha256:0401cc86f30009c2772f88bde71a5e694a1ebb726593940b7460e99cfa616140",
    "LogPath": "/var/lib/docker/containers/946cee105cd62e6483919725936a58f3d79c553cf7ce324c633b5aa32c71ebfc/946cee105cd62e6483919725936a58f3d79c553cf7ce324c633b5aa32c71ebfc-json.log",
    "MountLabel": "",
    "Mounts": [
        {
            "Destination": "/config",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/srv/dev-disk-by-label-SSData/config/qtorrent",
            "Type": "bind"
        },
        {
            "Destination": "/downloads",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/srv/50911774-19fb-46b6-bc9e-8cf81623d044/downloads",
            "Type": "bind"
        }
    ],
    "Name": "/qtorrent",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "Networks": {
            "host": {
                "Aliases": null,
                "DriverOpts": null,
                "EndpointID": "2b545f5f8b869b5e7ffa6742e923601f3daccf5fe813f481fc6969e862f02ffc",
                "Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAMConfig": null,
                "IPAddress": "",
                "IPPrefixLen": 0,
                "IPv6Gateway": "",
                "Links": null,
                "MacAddress": "",
                "NetworkID": "346429b356788338d03f6733a3f71f316beea8e02de340ac69c31f264e41d093"
            }
        },
        "Ports": {},
        "SandboxID": "6f5f86ec84e37140a42df980ed9052a0488a8832e1f6711e6865cbee2e30e1e9",
        "SandboxKey": "/var/run/docker/netns/default",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "Path": "/init",
    "Platform": "linux",
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/946cee105cd62e6483919725936a58f3d79c553cf7ce324c633b5aa32c71ebfc/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "2022-01-11T21:25:51.959596777Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 1738,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2022-01-11T21:26:23.404931493Z",
        "Status": "running"
    }
}

## Docker logs
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8080

Catching signal: SIGTERM
Exiting cleanly
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8080

bool Http::RequestParser::parsePostMessage(const QByteArray&) unknown content type: ""
Http::RequestParser::ParseResult Http::RequestParser::doParse(const QByteArray&) message body parsing error
Http::RequestParser::ParseResult Http::RequestParser::doParse(const QByteArray&) unsupported request method:  "CONNECT"
Http::RequestParser::ParseResult Http::RequestParser::doParse(const QByteArray&) header parsing error

##What helped

Reverting to amd64-20.04.1 fixed all my problems with no changes in my configuration. So it is clearly a regression somewhere

**Comment by Dekumori** [comment]
Reverting to the previous image should mitigate the issue for now until a permanent fix is available, whether that comes from here or somewhere upstream.

image: lscr.io/linuxserver/qbittorren:6328840003f0d731b07cd0985491989df3a8d6fae8595dcbd9afaf385850d493

**Comment by azumukupoe** [comment]
`image: lscr.io/linuxserver/qbittorrent:14.3.9` worked for me

**Comment by dfduarte78** [comment]
Tks guys, updated my docker-compose images yesterday and my webui was VERY slow, torrents wouldn't download faster than 200KB/s... reverted to 14.3.9 and everything seems to be back in order.

**Comment by zigagrcar** [comment]
Same problem, using mergerfs torrents throw error no such device

**Comment by drizuid** [comment]
These issues are with the application itself and should be reported there. This is not something we can fix.

**Comment by ShauneBoy** [comment]
Appreciate this has been closed but I'm still seeing this in the latest build - did even try another torrent client (deluge) and that is doing the same thing with it's latest build (bear with me for relevance here)... Whilst the older version [4.3.9] works for me (along with Deluge], the one thing I not they have in common is that are both based on Ubuntu - it's the versions/builds that are based on Alpine seem to fail/have issues - not sure if that makes any difference/explains anything?

**Comment by moomiji** [comment]
This seems to be the right solution:
https://github.com/guillaumedsde/alpine-qbittorrent-openvpn/issues/107#issuecomment-1033348843
