### ISSUE TITLE
Go back to the other version of qbittorrent-cli

### ISSUE THREAD

**Issue by rwtallant13** [linuxserver/docker-qbittorrent#151]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

start docker container
docker exec -it qbittorrent /usr/bin/qbt torrent pause all
pauses all torrents

## Current Behavior

start docker container
docker exec -it qbittorrent /usr/bin/qbt torrent pause all
Error: unknown command "torrent" for "qbt"
Run 'qbt --help' for usage.

## Alternatives Considered

Before the docker image was rebased to alpine a different version of qbt was used. It was previously fedarovich/qbittorrent-cli but now it is using ludviglundgren/qbittorrent-cli. Was this done due to some limitation in alpine or was it just an oversight since it was before added through an apt repo but now is manually curled? The fedarovich qbt is much more full featured and a better qbittorrent-cli program in my opinion and would be a better option for this container. 

Thanks.

**Comment by TheSpad** [comment]
The original cli tool doesn't provide Alpine binaries meaning we'd have to compile it from source and include the .NET runtimes in the container, which is why we had to switch away from it. Not saying we can never go back to it, but that it's a lot more work to do so.

**Comment by nomandera** [comment]
@rwtallant13 or anyone else, has anything be lost that actually reduces day to day functionality?

**Comment by rwtallant13** [comment]
I personally used the qbt tool to pause all torrents if i needed to as well as various other uses once in a while like editing global limits, messing with monitored folders, or torrent specific things like renaming, changing priority, reannouncing or enabling super seeding. If you look through the command reference list on the fedarovich version it has tons more features than the new cli tool does. 

I wouldnt really say im losing too much functionality since all these things could be done through the webui but i can no longer script or automate it as easily which is something i had gotten used to.

**Comment by rwtallant13** [comment]
I took it upon myself to ask fedarovich if an alpine binary would be possible. You can check that [here](https://github.com/fedarovich/qbittorrent-cli/issues/59) but tl;dr is they will try to add it to their next release. It would add a few dependencies but when that happens would going back to that version of qbt be possible if I notify this thread again?

**Comment by TheSpad** [comment]
If they can build standalone alpine binaries there's no reason we can't switch back to including them.

I've done some tests with building it myself as part of the image but it nearly doubles the size of the image because of how the dotnet framework packages things. I'm sure there's a smarter way to do it.
