### ISSUE TITLE
Not working behind a VPN container

### ISSUE THREAD

**Issue by MartinHotmann** [linuxserver/docker-qbittorrent#153]
Latest version as of today (release-4.4.0-ls169)
I removed the "ports" section of the docker-compose.yml file and changed network to:
`network_mode: "container:vpn"`

In the VPN container `vpn` I pipe through the port 8080 to 8080, to be able to access the WEB GUI by this port, rest will go through the VPN - as it should. But as soon as this is done, the port 8080 is not reachable anymore.

This worked with every other torrent container, but wanted to switch to qBittorrent as it includes the WEB GUI and the app in on image.

------------------------------

## Desired Behavior
Should work, even behind a VPN, actually this should be the recommended setup.

## Current Behavior
Does not work on this container, but all others.

I am using [`ghcr.io/wfg/openvpn-client`](https://github.com/wfg/docker-openvpn-client) as VPN container.

Any help would be appreciated. I can't imagine this container does not work behind a VPN container. 
Did anyone encountered the same issues?

Thanks in advance!

#### EDIT:
probably not related to the torrent container but the VPN container, anyway I leave it open in case some new evidence show it's related to the torrent container.

**Comment by ihaddy** [comment]
I encountered the same issue. 

To fix it you have to go to into the qBittorrent.conf file in your config volume, wherever you saved that, and add 


`WebUI\HostHeaderValidation=false`

to the end of it.

I ran into a further bug, where that alone should've fixed it, but for some reason the docker image overwrites the config file and restores it to a certain point, i'm not sure when, so the changes were not persisting.

To fix THAT issue, you can make the config file immutable and not overwritable to the docker container by doing:

`chattr +i qBittorrent.conf`

As a note, don't expose the login to the internet after doing this because it reduces the security of the application.

**Comment by ImjuzCY** [comment]
This didn't work for me. I stopped the container before editing the config file, this way it will persist. But it seems that qBittorrent is ignoring requests from any other machine that is in host's LAN. Using curl qBittorrent can be accessed from host (`curl localhost:8080`), or other containers that are in the same Docker Network (`curl vpn:8080`), but will not respond to anything outside of host (`curl host-ip:8080`)

**Comment by pbanj** [comment]
OK so I think I figured it out once and for all. don't use `localhost` or any other IP other than the IP for the VPN container's (docker)IP and the webui port

example: 172.56.0.3:8080

so no need to disable the header stuff

**Comment by stevenlafl** [comment]
I have the same issue but am not specifying any host IP to listen on, `grep` shows no match for 'localhost' or '127.0.0.1'. `netcat -tunlp` shows port 8080 is listening on 0.0.0.0, but Recv-Q gets +1 added every time I try to request, indicating the application (docker?) is blocking it. Other containers work fine.

I see both:

`WebUI\Address=*`
and
`WebUI\HostHeaderValidation=false`

in the qBittorrent.conf file.

I can see that I can curl it from within both the VPN container and from the host. It's only when I try to access it from the outside that it balks. My firewall is set to trust my IP address and the docker network. Again, only this container is affected, and my request is received by the kernel but docker does not appear to be picking it up.

**Comment by drizuid** [comment]
We will not provide support for routing a container through another container. This is basic networking and docker stuff and not an issue with the container. you're welcome to review <https://www.linuxserver.io/blog/routing-docker-host-and-container-traffic-through-wireguard> and go from there.

**Comment by pbanj** [comment]
> We will not provide support for routing a container through another container. This is basic networking and docker stuff and not an issue with the container. you're welcome to review https://www.linuxserver.io/blog/routing-docker-host-and-container-traffic-through-wireguard and go from there.

would it be possible to add the ability to set the `TrustedReverseProxiesList` and `ServerDomains` options using environment variables? that way people can add them from the start so they don't run into this issue

**Comment by drizuid** [comment]
@aptalca I don't use qbit and I know your general stance on new vars, thoughts on this?

**Comment by aptalca** [comment]
Both of those options are set in the gui settings. There is no reason to expose them as env vars. It's easy to access the gui locally without reverse proxy to set them. If it's a remote machine, ssh port forward. Worst case, edit the config file in the config folder. Plenty of options for such an edge case.
