### ISSUE TITLE
About advanced settingsof WebUI in QB 4.4.1

### ISSUE THREAD

**Issue by ayd13swb** [linuxserver/docker-qbittorrent#158]
Why are there still some options that require LIBTORRENT less than 2.0 in the advanced settings of WebUI in QB 4.4.1, and these options no longer exist in the Windows version of QB. Is the WEBUI not updated or what?Such as Disk cache or Coalesce reads & writes and so on.

**Comment by thelamer** [comment]
We wrap applications in docker containers. Please direct this question upstream.

**Comment by ayd13swb** [comment]
> We wrap applications in docker containers. Please direct this question upstream.

Yes i know that ..But the .exe and .dmg app isn't have those option anymore.

like shots

this is the docker vesion https://s4.ax1x.com/2022/03/03/bYP5gf.png

.exe vesion https://s4.ax1x.com/2022/03/03/bYPIv8.png

so ,is those options still effect or not?

**Comment by TheSpad** [comment]
The linux release can still be built against libtorrent 1.x which is likely why those settings are still in the UI. I have no idea if they have any effect when built against libtorrent 2.x, you'd need to ask the qbittorrent devs directly.
