### ISSUE TITLE
Search feature stopped working since version 4.4.1-r0-ls175

### ISSUE THREAD

**Issue by runil** [linuxserver/docker-qbittorrent#159]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
After updating the container I expected search feature to remain functional

## Current Behavior
Search tab is missing all search engines, unable to search.

## Steps to Reproduce

1. Update from previous release with working search to 4.4.1-r0-ls175
2. Search feature stops working.

## Environment
**OS:Ubuntu Server**
**CPU architecture:** x86_64
**How docker service was installed:** Using docker.io package

## Docker logs

......
......
......
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8011
QIODevice::read (QProcess): device not open
Could not parse Nova search engine capabilities, msg:
QIODevice::read (QProcess): device not open
Error:
QIODevice::read (QProcess): device not open
Could not parse Nova search engine capabilities, msg:
QIODevice::read (QProcess): device not open
Error:
QIODevice::read (QProcess): device not open
Could not parse Nova search engine capabilities, msg:
QIODevice::read (QProcess): device not open
.....
.....
.....

**Comment by scottwallacesh** [comment]
This is because Python is missing.

By running, `apk add python` inside the container and restarting it, I can get it to work again.

**Comment by aptalca** [comment]
Which search feature? I don't believe qbit has a search function. You have to install a search plugin for it.

If you're referring to the filter function, that's working for me just fine on the latest

**Comment by scottwallacesh** [comment]
Yes, search plugins aren't working. I believe it's because Python is missing from the image.

**Comment by BAZOOKAPANDA-REAL** [comment]
I have the same issue. updated to 4.4.1, plugins gone
Should mention though, I am running this as a Unraid docker container (the one from linuxserver's Repository), not on Ubuntu server.

But yes, I updated now my plugins are gone and don't want to reinstall, unfortunately this also means that my active downloads cant find their trackers and are stalled. Curiously enough two of my downloads can still reach their trackers, odd.

So if it's not patched by the time those are done I will have to roll back a version or two.
Hope this gets patched soon. Best of luck to the devs.

**Comment by scottwallacesh** [comment]
Fixed for me.
