### ISSUE TITLE
"Cannot write to directory" while moving an existing file

### ISSUE THREAD

**Issue by GurnissonDev** [linuxserver/docker-qbittorrent#164]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

When I select a file -> set location -> write path -> save, should move the file to the new folder without losing the "seed".

## Current Behavior

When I try to move a file I receive the message: "Cannot write to directory" while moving an existing file"
![image](https://user-images.githubusercontent.com/57829629/159546280-1b46f29c-60f0-478d-80e1-96d1a517c445.png)

If I download it directly to /peliculas I have no problem, it saves the file correctly.

## Steps to Reproduce

1. Right click on a downloaded file
2. Click on "set location..."
3. Write new folder (/Peliculas)
4. Click on "save"
5. I receive the error message

## Environment
**OS:** Ubuntu server
**CPU architecture:** x86_64 GNU/Linux
**How docker service was installed:**

Following official instructions: https://docs.docker.com/engine/install/ubuntu/
Official docker repo.

I have a NFS: /Multimedia, which contains some folders:
1. /Multimedia/descargas -> Download folder, mapped to /downloads inside container
2. /Multimedia/Peliculas -> mapped to /peliculas
3. /Multimedia/Series -> maped to /series

If I move a file to any place is no /downloads, it throws the error.

The NFS is stored in a Senology NAS.

PUID and GUID are configured. Umask is also configured (022)

Executing docker-compose with sudo changes nothing.

## Command used to create docker container (run/create/compose/screenshot)

===============
Docker-compose.yml
===============
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8090
      - UMASK=022
    volumes:
      - /home/vicente/qbittorrent/config:/config
      - /mnt/multimedia/descargas:/downloads
      - /mnt/multimedia:/multimedia
      - /mnt/multimedia/torrent:/watch
    ports:
      - 51413:51413
      - 51413:51413/udp
      - 8090:8090
    dns:
     - 8.8.8.8
     - 4.4.4.4
    restart: unless-stopped

## Docker logs

===================
Docker logs
===================
$ docker logs qbittorrent
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing...
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8090

==================
QBITTORRENT Logs
==================
https://pastebin.com/R5e1DLKJ 

Thank you in advance!

**Comment by ach5948** [comment]
I'm also seeing this issue

**Comment by meisyn** [comment]
same

**Comment by j0nnymoe** [comment]
Closing this issue. Nearly a year old, while yes we didn't reply originally but the user is trying to access a folder that's not even mapped as a volume in their compose. 

@meisyn please just don't say "same" - open a new issue and provide the information requested.
