### ISSUE TITLE
Default username/password is not what's published. 

### ISSUE THREAD

**Issue by thewickedjon** [linuxserver/docker-qbittorrent#166]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

The documentation (https://docs.linuxserver.io/images/docker-qbittorrent)  states (The webui is at <your-ip>:8080 and the default username/password is admin/adminadmin.) 

This is not accurate, as Im using this and it's not logging in.
------------------------------

## Expected Behavior

I should use the default username & password and it should log me in to the web UI.,

## Current Behavior

I use the default username & password and it won't log me in. 

## Steps to Reproduce

1. Get unraid server 
2. install community apps plugin
3. search for qbittorrent (linuxserver's repository) and install
4. once docker container is running,  open web ui
5. try to log in with the documentation's default username/password

## Environment
**OS:** unraid 6.9.2
**CPU architecture:** x86_64
**How docker service was installed:**

Docker container was installed 100% gui based only clicking from the community apps 

## Command used to create docker container (run/create/compose/screenshot)
 no command was used, this was done all from the community apps menu, 

## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing...
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8080

**Comment by j0nnymoe** [comment]
Can you test in a different browser/incognito mode? This usually happens when a password manager or some other extension is interfering with the login page.

**Comment by thewickedjon** [comment]
> Can you test in a different browser/incognito mode? This usually happens when a password manager or some other extension is interfering with the login page.

omg it worked on another browser!!!!!    sorry!!!!

**Comment by BeeTwenty** [comment]
i have same issue But Incognito/new browser/on mobile/without password manager still not working with admin/adminadmin

**Comment by haitispaceagency** [comment]
Issue persists for me. Tried Firefox, Firefox mobile, Safari mobile, and all of the incognito variations of those and it just is not the correct password.

**Comment by j0nnymoe** [comment]
Perhaps open a new issue. The problem you've got now is not related to this issue.

**Comment by H3llShadow** [comment]
FYI for anyone stumbling upon this more recently from google, the current documentation now states:

> The web UI is at <your-ip>:8080 and a temporary password for the **admin user will be printed to the container log on startup.**

As such, you'll find your password by running:
`docker ps` - get container_id
`docker logs container_id`
