### ISSUE TITLE
Cannot change Keep incomplete torrents path

### ISSUE THREAD

**Issue by saulrugero** [linuxserver/docker-qbittorrent#169]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I open the Web GUI and open the Options/Downloads window, select the tick box for "Keep incomplete torrents in:" and update the path from /downloads/incomplete/ to something else, for example /nas/Torrents/Incomplete.
## Current Behavior

After I click save and when I re-open the Options/Downloads window the path in unchanges from /downloads/incomplete/
## Steps to Reproduce

1. Open Web GUI Options/Downloads
2. Tick "Keep incomplete torrents in"
3. Change the path from /downloads/incomplete/
4. Click Save
5. Re-open Options/Downloads
6. You will see the path reverts to /downloads/incomplete/

This seems to be an issue in 4.4.2 and not in previous versions according to experiences by others. I have not tested this.
https://www.reddit.com/r/qBittorrent/comments/tqtcv6/unable_to_change_the_keep_incomplete_torrents_in/

## Environment
**OS:** Ubuntu 22.04
**CPU architecture:** x86_64
**How docker service was installed:**

Installed from official repository.
## Command used to create docker container (run/create/compose/screenshot)

version: '2.1'
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - /home/user/docker/qbittorrent:/config
      - /media/nas:/nas
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
## Docker logs

The actions on the Web UI create no entries in the docker qbittorrent container log.

**Comment by SupDRN** [comment]
I have the same problem.
Windows 11
qbittorrent 4.4.2

**Comment by akarabach** [comment]
the same problem for me, synology nas

**Comment by drizuid** [comment]
As mentioned in the OP this is a change by qbit in their latest versions. We support the container, not the application. Only the qbit devs can address this.
