### ISSUE TITLE
Lattest(4.4.2-r5-ls192) qbittorrent breaks RSS functions

### ISSUE THREAD

**Issue by Little-Karl** [linuxserver/docker-qbittorrent#172]

**Comment by Little-Karl** [comment]
looked around, looks like a qt issue but switching to 4.4.2-r4-ls191 seems to fix it

**Comment by johnareh** [comment]
rss dose not work for me on 4.4.2-r5-ls193 or 4.4.2-r5-ls192. 
but works on 4.4.2-r4-ls191

**Comment by Dep0s1t** [comment]
same, rss doesn't work on the latest version.

**Comment by PathToLife** [comment]
linking with issue on main qbt repo
https://github.com/qbittorrent/qBittorrent/issues/16879

**Comment by PathToLife** [comment]
Fixed in https://github.com/qbittorrent/qBittorrent/pull/17120 (3 days ago from this comment time)

Please close when updated

**Comment by josmellop** [comment]
Is the bug already fixed? :(

**Comment by whalehub** [comment]
> Is the bug already fixed? :(

Yes, the bug is not present in the latest image.

**Comment by Holdlang** [comment]
Latest version still have this error
