### ISSUE TITLE
Add qBittorrent logs to docker logs output 

### ISSUE THREAD

**Issue by UltraHKR** [linuxserver/docker-qbittorrent#179]
------------------------------

## Desired Behavior
"docker logs qb" > should output /path/docker/qb/qBittorrent/qbittorrent.log output. 
(like Jellyfin for example) 

## Current Behavior
"docker logs qb" > only shows container start/stop info... 

## Alternatives Considered
Manually using tail -f or cat, but isn't as integrated and I have long paths...

**Comment by thespad** [comment]
This may meet your requirements https://github.com/linuxserver/docker-mods/tree/universal-stdout-logs
