### ISSUE TITLE
Not Moving to Category Upon Completion

### ISSUE THREAD

**Issue by mccorkled** [linuxserver/docker-qbittorrent#18]
I have torrents being snatched under specific categories but upon completion they are not being moved to the categories directory. From what I have read there should be an option under...

"options > Downloads. For "Default Torrent Management Mode" choose "Automatic" AND click "Use Subcategories" AND for "Default Save Path" write in the path of your all_inbox_links (or whatever you have called it) directory."

I am not seeing this option, but it's available per torrent under it's right click menu. qBittorrent v4.0.3 Web UI.
Thanks.

**Comment by thelamer** [comment]
@mhofer117 offered a solution cleaning up old issues.
