### ISSUE TITLE
UMASK Permission Variable Not Working with Latest Update (Cannot Edit Files in Windows Mounted Share)

### ISSUE THREAD

**Issue by jeff15110168** [linuxserver/docker-qbittorrent#181]
## Expected Behavior
I'm having issues with files downloaded via qbittorrent linuxserver docker not getting the right permissions. I want to be able to edit files in Windows that were downloaded via qbittorrent docker but I'm now getting unix write errors. I had initially fixed this problem by creating a variable UMASK=000 about 12 months ago but recently this has stopped working ([another user here on Unraid Forum](https://forums.unraid.net/topic/59191-support-linuxserverio-qbittorrent/?do=findComment&comment=1139981) is reporting same issue). I ran Unraid's "docker fix safe permissions" to fix it manually but how do i permanently fix this? This wasn't an issue a few weeks ago, it just started happening (i haven't changed any settings).

For example, a file downloaded via qbt docker gives the below permissions (which doesn't let me edit the file via Windows mounted share):
```-rw-r--r-- 1 nobody users 268598687 Jun 19 15:24 [file name 1].mkv```

a file downloaded via another docker application i have setup with UMASK=000 (jdownloader) gives the below (which is what i want):
```-rw-rw-rw- 1 nobody users 187293974 Jun 19 15:32 [file name 2].mkv```

when i roll back to version "lscr.io/linuxserver/qbittorrent:4.4.3.1-r1-ls200", i don't have this issue anymore so it looks like it was something recent that changed this behavior.

## Environment
**OS: Unraid 6.9.2
**Kernel: Linux 5.10.28-Unraid x86_64
**OpenSSL: 1.1.1j
**How docker service was installed: Unraid Docker

## Command used to create docker container (run/create/compose/screenshot)
![image](https://user-images.githubusercontent.com/9892738/174498565-e9b0c848-67ab-41f2-9a77-bbc7c477fb4b.png)

**Comment by jeff15110168** [comment]
![image](https://user-images.githubusercontent.com/9892738/174501080-098b81df-a01e-4a02-a6f6-3c9cfbebe81d.png)

https://github.com/linuxserver/docker-qbittorrent/commit/b0576b6f8093162c36b8b96e26003f6bcfeeba02

Adding this detail in case it's relevant to troubleshooting.

**Comment by MercurySteam04** [comment]
Same Unraid version, same docker container version, same PGUID/PGID/UMASK values, same issue as OP. Can run the 'Fix Permissions' tool in Unraid but any new files have the same issue. Looks like an issue with the UMASK value not being respected. Getting errors along the line of "you require permission from unix (or sometimes server name) user/nobody" when deleting files from my downloads rootshare in Windows.

**Comment by thespad** [comment]
It's an issue we're aware of, it's been fixed in the upstream base image so the next build of the qbittorrent image will have the fix. In the meantime just roll back to the previous image release if you need the umask functionality.

**Comment by abhiagarwal01** [comment]
Can confirm that this is fixed by the latest image.

**Comment by jeff15110168** [comment]
> Can confirm that this is fixed by the latest image.

changed my repository to "lscr.io/linuxserver/qbittorrent", will try see if any further issues. thanks for reporting
