### ISSUE TITLE
Status Connection Yellow on Synology, it should be green?

### ISSUE THREAD

**Issue by FloydKulis** [linuxserver/docker-qbittorrent#187]
From what I remember, the connection status should be green. Unfortunately, I always have an orange flame.

I am using this installation:
```
  docker run -d --name=qbittorrent \
-p 26881:26881 \
-p 26881:26881/udp \
-p 5460:5460 \
-e WEBUI_PORT=5460 \
-e PUID=1026 \
-e PGID=1000 \
-e TZ=Europe/Warsaw \
-v /volume1/docker/qbittorrent:/config \
-v /volume1/downloads:/downloads \
--restart always \
ghcr.io/linuxserver/qbittorrent
```
I added port 5460 to the revers proxy in Synology:
![image](https://user-images.githubusercontent.com/37215675/184531168-e6f75ecf-c06f-4899-93e7-969e620c49de.png)

I added port 26881 forwarding in the router:
![image](https://user-images.githubusercontent.com/37215675/184531258-745fe86d-a17a-4a70-b1b0-29c731767d49.png)

The tracker sees me and downloads the files correctly.

But the connection status is orange and should it be green?
![image](https://user-images.githubusercontent.com/37215675/184531412-fcca70e0-ade0-4aa8-a8ca-a00fcf3b7260.png)

**Comment by j0nnymoe** [comment]
It will go green once you've configured your router to do your port forwarding for your bittorrent port, not webui.
