### ISSUE TITLE
qbt settings set not work because leck of libssl

### ISSUE THREAD

**Issue by tq02ksu** [linuxserver/docker-qbittorrent#189]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

`qbt settings set url/username`  not work with output as
```
root@qbittorent-7c9768464b-ds86r:/downloads# qbt settings set url http://localhost:20909
No usable version of libssl was found
/usr/bin/qbt: line 14:   649 Aborted                 /qbt/qbt "$@"
```

I check the Dockerfile, where only have libssl, openssl.
so I try to add `openssl1.1-compat` by cmd:
`ask add openssl1.1-compat`

and then the problem resolved.

------------------------------

## Expected Behavior

return OK 
## Current Behavior

```
root@qbittorent-7c9768464b-ds86r:/downloads# qbt settings set url http://localhost:20909
No usable version of libssl was found
/usr/bin/qbt: line 14:   649 Aborted                 /qbt/qbt "$@"
```
## Steps to Reproduce

1. install and run docker image
2. issue cmd `qbt settings set url xxx`

## Environment
**OS: truenas scale
**CPU architecture:** x86_64
**How docker service was installed:** By trueness charts

## Command used to create docker container (run/create/compose/screenshot)
 by k3s

**Comment by andras-tim** [comment]
Unfortunately, the `ghcr.io/linuxserver/qbittorrent:4.4.5-r2-ls224` is affected.
