### ISSUE TITLE
Container crashes with readonly config file

### ISSUE THREAD

**Issue by ViRb3** [linuxserver/docker-qbittorrent#190]
## Expected Behavior
As with every other LinuxServer container, and as this container has done forever, if the config file cannot be `chown`ed, proceed anyway.

## Current Behavior
Since 4.4.4 the config `chown` is fatal and the container crashes on boot.

## Steps to Reproduce
Start the container with the config file mounted as read-only volume. Observe crash.

## Environment
**OS:** Ubuntu 22..04
**CPU architecture:** arm64
**How docker service was installed:** `apt install docker.io`

## Command used to create docker container (run/create/compose/screenshot)
```yml
  qbittorrent:
    image: local/qbittorrent
    volumes:
      - ./qbittorrent/config/qBittorrent.conf:/config/qBittorrent/qBittorrent.conf:ro
```

## Docker logs
```
[custom-init] no custom services found, skipping...
[migrations] started
[migrations] no migrations found
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
chown: changing ownership of '/config/qBittorrent/qBittorrent.conf': Read-only file system
s6-rc: warning: unable to start service init-qbittorrent: command exited 1
```

**Comment by aptalca** [comment]
We never supported mounting standalone config files, let alone read only.

We support mounting a config folder with the necessary permissions.

You also seem to be using a locally built image, also not supported by us.

**Comment by ViRb3** [comment]
The "locally built image" is just a wrapper, the issue can be reproduced with your image just as easily. If mounting read-only is not supported, how are you supposed to ensure that the service does not silently change your configs, or to version-track any changes done via the UI? Even mounting the entire `/config` folder as read-only won't work for the same reason.
