### ISSUE TITLE
Not possible to use. file_fallocate error: Not supported

### ISSUE THREAD

**Issue by wellenc** [linuxserver/docker-qbittorrent#191]
Hello!

I'm using debian, docker-compose, latest image, exfat volume from veracrypt ( with 777 on it )

```environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - /media/veracrypt2/config:/config
      - /media/veracrypt2/:/downloads
```

Every download try ends up with "errored" status and file_fallocate error: Not supported in logs.

```File error alert. Torrent: "Airplane.mkv". File: "/downloads/Airplane.mkv.!qB". Reason: file_fallocate (/downloads/Airplane.) error: Not supported```

Any suggestions?

**Comment by j0nnymoe** [comment]
If it's only happening when using a veracrypt2 mount, I would highly suggest reading their documentation to see why the file allocate would get blocked. It's likely you need to add an option onto your mount point.

**Comment by wellenc** [comment]
> If it's only happening when using a veracrypt2 mount, I would highly suggest reading their documentation to see why the file allocate would get blocked. It's likely you need to add an option onto your mount point.

Hello, @j0nnymoe!

from what I can see the file is being allocated successfully 
<img width="1001" alt="изображение" src="https://user-images.githubusercontent.com/63397390/190866043-72343d24-e962-4c97-ba80-8a14024c4295.png">

Also I could read\write with my uid=1000 user.

As I see problem lies somewhere in the docker image

**Comment by j0nnymoe** [comment]
Please be mindful of the images you post.

And no I don't agree it's something to do with the container. If it works fine without veracrypt, it's then veracrypt that's adding in an extra complexity with our container or docker itself.

**Comment by wellenc** [comment]
> Please be mindful of the images you post.
> 
> And no I don't agree it's something to do with the container. If it works fine without veracrypt, it's then veracrypt that's adding in an extra complexity with our container or docker itself.

I've added that I could write to the FS inside the docker container (tried with docker exec and echo > file) so thats not FS error either.

How could I debug what prevents qbit from allocating?

**Comment by j0nnymoe** [comment]
Scratch that, I've been reminded that it's a libtorrent v2 pre-allocation issue. Our container is still built upon that due to the packages we use from the alpine repo. Unfortunatley at this moment there isn't a fix. We need to wait for the package to be moved back to v1 or either change how we build the container.

**Comment by geekifier** [comment]
@j0nnymoe Is there any sort of a workaround that an end-user could try to mitigate this? Or is replacing the library the only option?

**Comment by YunofHD** [comment]
> @j0nnymoe Is there any sort of a workaround that an end-user could try to mitigate this? Or is replacing the library the only option?
>
> Edit: In my case, it seems that qBittorrent was trying to pre_allocate files despite the option being ticked off. I toggled the option, saved, removed affected torrents (and files), and it started working again. This is saving to an SMB share mounted on a Linux server.

Please try to use old version qbittorrent
I met this problem too. My environment is Docker .
After seen a lot of issues I try to use this version images "lscr.io/linuxserver/qbittorrent:14.3.9", so problem fixed
My be problem is that we use iSCSI/Samba/NFS to storage files

**Comment by molotch** [comment]
> @j0nnymoe Is there any sort of a workaround that an end-user could try to mitigate this? Or is replacing the library the only option?
> 
> Edit: In my case, it seems that qBittorrent was trying to pre_allocate files despite the option being ticked off. I toggled the option, saved, removed affected torrents (and files), and it started working again. This is saving to an SMB share mounted on a Linux server.

Deselecting pre allocation worked for me too. I'm using bind mounts.

**Comment by lnking81** [comment]
> Please try to use old version qbittorrent I met this problem too. My environment is Docker . After seen a lot of issues I try to use this version images "lscr.io/linuxserver/qbittorrent:14.3.9", so problem fixed My be problem is that we use iSCSI/Samba/NFS to storage files

The only that helped. Disabled preallocation, downgraded all way down to 4.4.0. But only after installing 14.3.9 it started to work properly. Docker/Bind mount ext4 lvm

**Comment by SitramSoft** [comment]
I have the same issue when using the latest image.

Disabling preallocation in the options seems to solve the issue. I had to remove the existing torrents and add them again.

Another option is to downgrade to image version 4.3.9

**Comment by kaitallaoua** [comment]
Also can confirm downgrading to

> After seen a lot of issues I try to use this version images "lscr.io/linuxserver/qbittorrent:14.3.9", so problem fixed

fixed the same issue as the file not supported error

**Comment by ivobacco** [comment]
> I have the same issue when using the latest image.
> 
> Disabling preallocation in the options seems to solve the issue. I had to remove the existing torrents and add them again.
> 
> Another option is to downgrade to image version 4.3.9

Disabling preallocate files from configuration seems to have no effect
Same errors and same issues, only working option was to go back to older version

**Comment by AliYusuf95** [comment]
> > I have the same issue when using the latest image.
> > Disabling preallocation in the options seems to solve the issue. I had to remove the existing torrents and add them again.
> > Another option is to downgrade to image version 4.3.9
> 
> Disabling preallocate files from configuration seems to have no effect Same errors and same issues, only working option was to go back to older version

Still the same with latest release, I use qbittorrent with wsl2 docker integration. Only downgrade solves the problem.

**Comment by j0nnymoe** [comment]
Well we have no idea of your specific setup but It's an issue with libtorrentv2. Just use the libtorrentv1 tag.

Closing issue.

**Comment by SitramSoft** [comment]
For me using libtorrentv1 solved the issue.
