### ISSUE TITLE
qBittorrent on libtorrent 2.x is exetremely buggy, drop back to 1.x? 

### ISSUE THREAD

**Issue by jlw4049** [linuxserver/docker-qbittorrent#194]
If you look at qBittorrents github account you'll see that EVERYONE has problems with 2.x. 

Is it possible to create a release with either 1.x or 2.x? As the latest version of qBittorrent has actually defaulted back to libtorrent 1.x until the issues are resolved.

**Comment by aptalca** [comment]
It's up to alpine as we install from their repo

**Comment by jlw4049** [comment]
Should I post an issue on their website? Could you possibly link me to where I'd need to do that? 

qBitorrent quit using libtorrent 2.x because it is so unstable as their main download a 4.4.4 and beyond. So I think this is something that should be done in order to maintain stability.

**Comment by aptalca** [comment]
Here's their repo where you can open an issue: https://gitlab.alpinelinux.org/alpine/aports

**Comment by aptalca** [comment]
We're currently installing it from their `edge` repo: https://github.com/linuxserver/docker-qbittorrent/blob/master/Dockerfile#L1

**Comment by jlw4049** [comment]
Thanks man, I'll close this I suppose. I'll add the issue to their tracker!

**Comment by andras-tim** [comment]
For the record, the official 4.5.0 release news contains a note about the libtorrent v1:

> **NOTE:** The default builds for all OSs switched to libtorrent 1.2.x from 2.0.x. Builds for libtorrent 2.0.x are also offered and are tagged with lt20. The switch happened due to user demand and perceived performance issues. If until now you didn't experience any performance issue then go ahead and use the lt20 builds.

Source: https://www.qbittorrent.org/news.php

**Comment by andras-tim** [comment]
Ohh, I see... now the [`libtorrentv1`](https://github.com/linuxserver/docker-qbittorrent#version-tags) versions are available. Thanks!
