### ISSUE TITLE
[BUG] Weird tags on all elements

### ISSUE THREAD

**Issue by calebsw83** [linuxserver/docker-qbittorrent#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Qbittorrent is showing all sorts of weird tags when I browse via the webui

[login screen](https://i.imgur.com/WHk9Qzq.png)
[main screen](https://i.imgur.com/BgXhUri.png)

It started today, after watchtower upgraded me from 4.4.5 to 4.5.0. I see there was an update to 4.5.0 2 hours ago, and I tried pulling that, but this persisted. I tried rolling back to older versions, and while it removed the tags from almost everywhere, it still showed them in the status section on the main screen, [as seen here](https://i.imgur.com/cfjN6MA.png), everywhere else looks normal again except for the areas in the screenshot. 

### Expected Behavior

The verbose tags should not be present, and the following text pattern should not appear at all, save for the wildcards that I included, which appear to be the original labels: QBT_TR(\*)QBT_TR|CONTEXT=\*

### Steps To Reproduce

The only thing that happened between when these tags were visible and when they weren't was watchtower updated qbittorrent to 4.5.0. Now that it's happened, I can't revert to the way things were, in order to be able to reproduce the outcome. 

### Environment

```markdown
- OS:Synology DSM 6.2
- How docker service was installed: docker compose via portainer
```

### CPU architecture

x86-64

### Docker creation

```bash
qbittorrent:
    image: linuxserver/qbittorrent:4.4.5
    container_name: vpn-qbittorrent
    environment:
      - PUID=(redacted)
      - PGID=(redacted)
      - TZ=(redacted)
      - WEBUI_PORT=8085
    volumes:
      - /(redacted):/(redacted)
      - /(redacted):/(redacted)
      - /(redacted):/(redacted)
      - /(redacted):/(redacted)
    network_mode: service:vpn
    restart: always

This is the docker compose I've had for the last year, I'm sure this is fine and not related to the issue.
```

### Container logs

```bash
(redacted)@(redacted):/$ sudo docker logs vpn-qbittorrent
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    (redacted)
User gid:    (redacted)
-------------------------------------

[custom-init] No custom files found, skipping...

******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8085
[ls.io-init] done.
(redacted)@(redacted):/$
```

**Comment by Roxedus** [comment]
Redacting all the important information is not helpful. 

This is the fault of your custom theme/ui.
https://github.com/qbittorrent/qBittorrent/discussions/17771
