### ISSUE TITLE
[BUG] < 4.5.0 can't change to chinese language>

### ISSUE THREAD

**Issue by xinmans** [linuxserver/docker-qbittorrent#205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
4.5.0 can't change to chinese language

### Expected Behavior

4.5.0 can't change to chinese language

### Steps To Reproduce

option -》 webui -》 language -》简体中文

### Environment

```markdown
qBittorrent v4.5.0 Web UI (64-bit)


docker.io/linuxserver/qbittorrent:4.5.0
```

### CPU architecture

x86-64

### Docker creation

```bash
use portainer
```

### Container logs

```bash
no error
```

**Comment by thespad** [comment]
This is an upstream bug https://github.com/qbittorrent/qBittorrent/issues/18090

**Comment by greatbody** [comment]
考虑到使用中文的都是会中文的，我下面都用中文说。

解决方法有两个：

## WebUI 修改
- 使用浏览器的开发者模式，找到 Language 设置处的下拉菜单
- 修改 简体中文 的 select value 为 "zh_CN"，大小写不能错
- 保存即可

## 配置文件修改

打开 config 目录下的 qBittorrent/qBittorrent.conf 文件，修改其中的 `[Preferences]` 下的 `General\Locale` 的值为 `zh_CN`.
保存即可。

[Preferences]
......
General\Locale=zh_CN

**Comment by 568145697** [comment]
> 

这个方法是可以解决   每次需要修改QB设置后  还需要再次配置简中  太麻烦了  这个问题始终未解决

**Comment by xinmans** [comment]
官方为啥不修复？

**Comment by jelly0925** [comment]
好无语的BUG
