### ISSUE TITLE
Missing SVG file for WebUI icons

### ISSUE THREAD

**Issue by panosru** [linuxserver/docker-qbittorrent#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The queue icon is missing

![image](https://user-images.githubusercontent.com/400362/205175899-0e8961ce-c515-481c-95e1-c77ec3a3091f.png)

![image](https://user-images.githubusercontent.com/400362/205176341-39185070-63ef-4fb1-8f47-9d0f42034048.png)

### Expected Behavior

To show [the icon](https://opensource.xdown.org/qBittorrent-release-4.3.2/src/icons/queued.svg) properly

### Steps To Reproduce

Just run the default docker-compose YAML with the default theme

### Environment

```markdown
- OS: Ubuntu Server / Docker Container
- How docker service was installed: docker compose
```

### CPU architecture

x86-64

### Docker creation

![image](https://user-images.githubusercontent.com/400362/205177152-9f91195b-665b-4c02-830a-2b1d777551db.png)

![image](https://user-images.githubusercontent.com/400362/205177211-ed98f80e-477c-45ac-a0da-1dd828189c0d.png)

_VueTorrent theme is disabled._

### Container logs

```bash
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[custom-init] No custom files found, skipping...
WebUI will be started shortly after internal preparations. Please wait...
[ls.io-init] done.
```

**Comment by jeremyjohn** [comment]
Same issue here, is this going to get fixed in the next version?

**Comment by thespad** [comment]
This is an upstream issue (https://github.com/qbittorrent/qBittorrent/issues/18073), all we can do is wait for a release that incorporates the fix.
