### ISSUE TITLE
[BUG] UI won't load

### ISSUE THREAD

**Issue by YouveGotMeowxy** [linuxserver/docker-qbittorrent#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Anyone else having this issue with the current version of QB?

![image](https://user-images.githubusercontent.com/39491297/210584718-ed2ae366-1485-422c-8285-eb22fe39d834.png)

### Expected Behavior

GUI not all janky

### Steps To Reproduce

Nothing special. Just running the container as per usual.

### Environment

```markdown
- OS: Docker Desktop WSL2 Ubuntu 20.04
```

### CPU architecture

x86-64

### Docker creation

```bash
My config, that I've been using forever and haven't changed lately:


  qbittorrent:
    hostname: 'qbittorrent'
    image: 'ghcr.io/linuxserver/qbittorrent:latest'
    environment:
      TZ: 'America/Chicago'
      PUID: '1000'
      PGID: '1000'
      WEBUI_PORT: '8080'
    volumes:
      - '/opt/docker/configs/qbittorrent/config:/config:rw'
      - '/mnt/e/Docker/Logs/qbittorrent:/config/data/qBittorrent/logs:rw'
      - '/mnt/e/Media/.downloads/.blackhole:/Media/.downloads/.blackhole:rw'
      - '/mnt/e/Media/.downloads:/Media/.downloads:rw'
    networks:
      - 'download'
    deploy:
      mode: 'replicated'
      replicas: 1
      placement:
        constraints:
          - 'node.labels.Main == true'
      restart_policy:
        condition: 'any'
```

### Container logs

```bash
01/04/2023 9:02:14 AM
[custom-init] No custom services found, skipping...
01/04/2023 9:02:14 AM
[migrations] started
01/04/2023 9:02:14 AM
[migrations] no migrations found
01/04/2023 9:02:14 AM
01/04/2023 9:02:14 AM
-------------------------------------
01/04/2023 9:02:14 AM
          _         ()
01/04/2023 9:02:14 AM
         | |  ___   _    __
01/04/2023 9:02:14 AM
         | | / __| | |  /  \
01/04/2023 9:02:14 AM
         | | \__ \ | | | () |
01/04/2023 9:02:14 AM
         |_| |___/ |_|  \__/
01/04/2023 9:02:14 AM
01/04/2023 9:02:14 AM
01/04/2023 9:02:14 AM
Brought to you by linuxserver.io
01/04/2023 9:02:14 AM
-------------------------------------
01/04/2023 9:02:14 AM
01/04/2023 9:02:14 AM
To support LSIO projects visit:
01/04/2023 9:02:14 AM
https://www.linuxserver.io/donate/
01/04/2023 9:02:14 AM
-------------------------------------
01/04/2023 9:02:14 AM
GID/UID
01/04/2023 9:02:14 AM
-------------------------------------
01/04/2023 9:02:14 AM
01/04/2023 9:02:14 AM
User uid:    1000
01/04/2023 9:02:14 AM
User gid:    1000
01/04/2023 9:02:14 AM
-------------------------------------
01/04/2023 9:02:14 AM
01/04/2023 9:02:14 AM
[custom-init] No custom files found, skipping...
01/04/2023 9:02:14 AM
WebUI will be started shortly after internal preparations. Please wait...
01/04/2023 9:02:15 AM
[ls.io-init] done.
```

**Comment by aptalca** [comment]
If you're using a custom theme, revert back to default

**Comment by YouveGotMeowxy** [comment]
> If you're using a custom theme, revert back to default

After a lot of fooling around it does seem theme related, but don't know why the theme I'd been using for the longest time just randomly broke.

And then after that I've tried several themes that have the `.qbtheme` extension (also tried extracting it's resources to a folder and point to that), as well as even extracting the `https://github.com/qbittorrent/qBittorrent/tree/master/src/webui/www` folder and pointing my theme to it, but all I ever get is:

> Unacceptable file type, only regular file is allowed.

I can only get 1 custom theme to work, and that's [VueTorrent](https://github.com/WDaan/VueTorrent).

Other than that, I can set `WebUI\AlternativeUIEnabled=false` and the ugly default theme does load.

I was hoping the Nord theme I had also been using: https://docs.theme-park.dev/themes/qbittorrent, would still work on the default theme, but it doesn't.

Seems like maybe the QB devs might've made some changes that broke "old" themes?

**Comment by thespad** [comment]
Because 4.5.0 made substantial UI changes and very few custom themes have updated to support it.
