### ISSUE TITLE
custom settings for torrents

### ISSUE THREAD

**Issue by DuckersMcQuack** [linuxserver/docker-qbittorrent#218]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I want to request a setting for torrents to keep the ones i choose to to for instance keep active seeding for ratio/freeleech torrents, but automatic settings i've set like ratio/time target for other ones.

### Reason for change

To gain ratio on private trackers/freeleech.

**Comment by aptalca** [comment]
That needs to be reported to qbit devs. We don't control app features.
