### ISSUE TITLE
[BUG] Latest image (4.5.0-r1-ls241) breaks QNAP compatibility

### ISSUE THREAD

**Issue by lukenpi** [linuxserver/docker-qbittorrent#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Creating a new container with the latest image results in a non working qBittorrent. Inspecting the container logs a couple of segmentation faults are visible and a redundant "punt!" message.

### Expected Behavior

The image should just work as previous ones

### Steps To Reproduce

1. Open Container Station
2. Click Create, search for linuxserver/qbittorrent, click Install
3. Choose a bridge network, set static IP X.X.X.X (where X.X.X.X is an address in your LAN)
4. Define /config and /downloads
5. Confirm and wait for image creation
6. Container is not accessible at port X.X.X.X:8080

The same steps with version 4.5.0-r1-ls240 work as expected.

### Environment

```markdown
- OS: QTS 5.0.1.2248 on QNAP TS-231P3
- Kernel version: 4.2.8
- CPU: Annapurna Labs Alpine A314 Quad-Core ARM Cortex-A15 CPU @ 1.70 GHz
- How docker service was installed: Container Station
```

### CPU architecture

armhf

### Docker creation

```bash
See steps to reproduce
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
/etc/s6-overlay/s6-rc.d/init-adduser/run: line 7:    75 Segmentation fault      groupmod -o -g "$PGID" abc
/etc/s6-overlay/s6-rc.d/init-adduser/run: line 8:    76 Segmentation fault      usermod -o -u "$PUID" abc

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    1001
-------------------------------------

[custom-init] No custom files found, skipping...
punt!
punt!
punt!
punt!
punt!
punt!
```

**Comment by j0nnymoe** [comment]
What kernel version is your qnap?

**Comment by lukenpi** [comment]
> What kernel version is your qnap?

`uname -r` returns 4.2.8

**Comment by lukenpi** [comment]
> What kernel version is your qnap?

`uname -r` returns 4.2.8

**Comment by ivicask** [comment]
Same issue i cant open WEB after update of container on my QNAP

**Comment by sharkannon** [comment]
Seeing the same issue on my TS-431XeU running on the latest Container Station (v2.6.4.630)

```
Linux MEGALODON 4.2.8 #2 SMP Thu Jan 12 06:25:39 CST 2023 armv7l unknown
```

Docker images are any of the 4.5.x.  I can  install 4.4.x and things work just fine.

**Comment by j0nnymoe** [comment]
Likely issue specific to running an older kernel/arm32. Unfortunately hard for us to diagnose the issue as no one within the team has a arm QNAP device.

**Comment by drizuid** [comment]
As mentioned, due to the age of the unit (and failure to follow the readme for the container) we cannot assist with this. We suggest ensuring you use hardware that is supported and kept up to date.

**Comment by ivicask** [comment]
Age of unit?(TS-431P3)Its 2020 model of qnap runing x64 bit quad core ARM cpu, runing latest updates from qnap.
