### ISSUE TITLE
qbittorrent not showing tun0 interface 

### ISSUE THREAD

**Issue by aattieh** [linuxserver/docker-qbittorrent#223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Installed qbittorrent and Open VPN for which tun0 is showing with it IP with ifconfig, however when going to advanced options to change the interface the binding IP they are not showing there only etho and lo are showing.

did check config file but there was no option to force certain interface to be used 

### Expected Behavior

tun0 for VPN connections showed be showing up.

### Steps To Reproduce

install qbittorrent
install openvpn and run it 
open qbittorrent gui -> tools -> advanced -> change network interface drop down

### Environment

```markdown
- OS: Raspberian OS 32 Bit 
- How docker service was installed:


  qbittorrent:
    image: ghcr.io/qbittorrent/docker-qbittorrent-nox:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America\New_York
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - /home/brainadmin/Dockers/Plex_Requests/config/qbittorrent:/config
      - /home/brainadmin/Dockers/Plex_Requests/qbittorrent_downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
```

### CPU architecture

x86-64

### Docker creation

```bash
docker-compose up -d
```

### Container logs

```bash
Logs are showing that the correct VPN external IP have been detected but still the interface is not showing in the drop down list and i need to make sure it will not fallback to another interfaces 

(I) 2023-02-01T22:22:28 - Detected external IP. IP: "V.P.N.x"
```

**Comment by gacrestani** [comment]
Same thing for me.

**Comment by drizuid** [comment]
We will not provide support for routing a container through another container. This is basic networking and docker stuff and not an issue with the container. you're welcome to review https://www.linuxserver.io/blog/routing-docker-host-and-container-traffic-through-wireguard and go from there.
