### ISSUE TITLE
[BUG] 4.5.0 WebUI Language Bug

### ISSUE THREAD

**Issue by qiuzhangsaer** [linuxserver/docker-qbittorrent#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

WebUI Language "简体中文(Chinese Simplified)" <option> value is 'zh',This is wrong,After setting, the webui language is still English

### Expected Behavior

The correct value should be 'zh_ CN'
[![pSRXZ38.png](https://s1.ax1x.com/2023/02/09/pSRXZ38.png)](https://imgse.com/i/pSRXZ38)

### Steps To Reproduce

-

### Environment

```markdown
- OS:DSM 6.2.3-25426 Update 3
- How docker service was installed:Synology Docker
```

### CPU architecture

x86-64

### Docker creation

```bash
-
```

### Container logs

```bash
-
```

**Comment by aptalca** [comment]
That should be reported upstream to qbittorrent

**Comment by capric98** [comment]
The upstream seems like fix this issue by releasing 4.5.1.

**Comment by G0510OLD** [comment]
4.5.2-r0-ls250 still have the same issue

**Comment by j0nnymoe** [comment]
Have you reported this upstream? It's not for us to fix.

**Comment by drizuid** [comment]
Closing this as it is a qbittorrent issue, not a container issue. We cannot fix this.
