### ISSUE TITLE
[FEAT] Accept ui username/password as an environment variable

### ISSUE THREAD

**Issue by smartcontracts** [linuxserver/docker-qbittorrent#228]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Would be ideal if this would accept a username/password as environment variables. 

### Reason for change

I want to be able to easily spin up some seedboxes with exposed UIs but I don't want to have to manually edit the password each time.

**Comment by garret** [comment]
That is a pity that it cannot be implemented. I think that is possible on the transmission image but I am not 100% sure.

**Comment by aptalca** [comment]
It is not something crucial to get the container up and running, as it has default credentials that can be changed through the gui or via editing the config file. If you want to script it, you can easily do that.

https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers
