### ISSUE TITLE
[BUG] armhf tagged as armv8

### ISSUE THREAD

**Issue by akoray420** [linuxserver/docker-qbittorrent#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"failed to deploy a stack: qbittorrent Pulling no matching manifest for linux/arm/v7 in the manifest list entries"
Portainer deploy error.

armhf tagged as armv8

### Expected Behavior

arm32v7-libtorrentv1 works fine

### Steps To Reproduce

Change armhf "linux/arm/v8" -> "linux/arm/v7"

### Environment

```markdown
- OS: Rasbian OS (Rpi 2B)
- How docker service was installed: OMV 6
```

### CPU architecture

armhf

### Docker creation

```bash
---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - WEBUI_PORT=8080
    volumes:
      - /srv/dev-disk-by-uuid-26135595-f1f9-4603-9d8b-be0e0e1133ef/config:/config
      - /srv/dev-disk-by-uuid-26135595-f1f9-4603-9d8b-be0e0e1133ef/torrent:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
```

### Container logs

```bash
failed to deploy a stack: qbittorrent Pulling no matching manifest for linux/arm/v7 in the manifest list entries
```

**Comment by thespad** [comment]
Thanks for making us aware, we're looking into the issue.
