### ISSUE TITLE
[BUG] abnormal disk io with 4.5.2-libtorrentv2 against libtorrentv1

### ISSUE THREAD

**Issue by Elypha** [linuxserver/docker-qbittorrent#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running with the latest 4.5.2 [image](https://hub.docker.com/layers/linuxserver/qbittorrent/4.5.2/images/sha256-59985a34f6fbd5d11372c89b7578087db1911fdc4809484ca5b49c3dc9a2d809?context=explore), I see abnormal disk io as shown in the following screenshot (via `htop`):
![2023-03-08_09-10-44_854](https://user-images.githubusercontent.com/30290883/223671234-1df81acc-4987-456c-a11f-0c14543eca5f.png)
With the uploading speed being at around 10 MB/s, the disk read can go to 120 MB/s and eventually hit ~1GB/s in a few hours. Then the host will be barely responsible due to the heavy io.

If I switch to the `libtorrentv1` [image](https://hub.docker.com/layers/linuxserver/qbittorrent/4.5.2-libtorrentv1/images/sha256-49473420e7cb8db61876d38831da7ee712c4a491a3dbab2a85c1a76a4797c982?context=explore) with the same data file and config, everything would seem to be fine. With uploading speed of around 10 MB/s the disk read is at most times below 20 MB/s, and the device load can stay normal for days.

### Steps To Reproduce

1. I was running qbittorrent `4.4.x`. It's seeding about 900 small torrents (~5MB), and several large ones from 1GB to 300GB. Total size is about 600GB
2. Upgraded to `4.5.2` by just changing the version string in `.yaml`, then `docker-compose`
3. I/O issue found
4. Changed version from `4.5.2` to `4.5.2-libtorrentv1`, then the issue was solved
5. Repeat the steps and the same problem can be reproduced

### Environment

```markdown
- OS: Debian 11
- How docker service was installed: distro's package manager
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.5.2
    # image: lscr.io/linuxserver/qbittorrent:4.5.2-libtorrentv1
    container_name: qbt
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - WEBUI_PORT=51002
    volumes:
      - /data/docker/qbt_config:/config
      - /data/qbt_dl:/downloads
      - /data/qbt_rss:/rss
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    0
User GID:    0
───────────────────────────────────────

[custom-init] No custom files found, skipping...
WebUI will be started shortly after internal preparations. Please wait...
[ls.io-init] done.
```

**Comment by Roxedus** [comment]
This sounds very much like a qbit/libtorrent issue, rather than a container issue.

**Comment by Elypha** [comment]
> This sounds very much like a qbit/libtorrent issue, rather than a container issue.

Thanks for the reply. It seems the same to me, but I'm not sure if qbittorrent in linuxserver's image functions similarly as the official build. The official repo only provides appimages which don't seem to run on a server without desktop, so I can't really find a handy way to test it

**Comment by drizuid** [comment]
We are not the devs of libtorrent and cannot resolve their issues. Best to open an issue with the upstream devs.
