### ISSUE TITLE
[BUG] Segfault on container stop with libtorrentv1 ls18/ls19

### ISSUE THREAD

**Issue by abiacco** [linuxserver/docker-qbittorrent#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the docker container is stopped, a segfault is logged in host dmesg

Example: 
[Sun Apr 16 12:19:40 2023] qbittorrent-nox[29058]: segfault at 20 ip 0000000000465b6c sp 00007fffd8bef760 error 4 in qbittorrent-nox[400000+3a69000]
[Sun Apr 16 12:19:40 2023] Code: 48 03 82 80 00 00 00 8b 10 31 c0 e8 5a c5 fe ff 48 8b 7c 24 08 31 f6 e8 42 02 84 00 0f b7 43 06 4c 8b 4c 24 08 e9 30 78 97 00 <48> 8b 04 25 20 00 00 00 0f 0b 4c 89 e7 e8 a2 af 80 00 48 89 df e8

Issue only happens with "libtorrentv1" version tag with versions ls18/ls19 (not with ls14-ls17).
Tried "latest" version tag - issue is NOT reproducible.
Created a test script to run a 30 count loop of: start container, sleep 10s, stop container.
- libtorrentv1: 23 segfaults out of 30
- latest: 0 segfaults out of 30

All segfaults share same info as example above except ip/sp.
Tried a normal "Bridge" network type instead of my custom ip br0 config below. Issue reproducibility doesn't change

### Expected Behavior

Clean stop of docker container

### Steps To Reproduce

1. Create libtorrentv1 ls18/ls19 docker container
2. Start docker container
3. Stop docker container

### Environment

```markdown
- OS: Unraid 6.9.2/6.11.5 (currently testing on 6.11.5, only observed passively on 6.9.2)
- CPU: i5-8600k
- RAM: 2x16GB DDR4-3200
- DOCKER: Docker version 20.10.21, build baeda1f
- UNAME: Linux <PRIVATE> 5.19.17-Unraid #2 SMP PREEMPT_DYNAMIC Wed Nov 2 11:54:15 PDT 2022 x86_64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz GenuineIntel GNU/Linux
- Installed via: Unraid webui Apps tab
- Versions:
 lscr.io/linuxserver/qbittorrent:libtorrentv1
  Linuxserver.io version:- release-4.5.2_v1.2.18-ls18
  Linuxserver.io version:- release-4.5.2_v1.2.18-ls19
 lscr.io/linuxserver/qbittorrent:latest
  Linuxserver.io version:- 4.5.2-r2-ls258
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='qbittorrent-segfault'
  --net='br0'
  --ip='<PRIVATE>'
  -e TZ="America/Denver"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="<PRIVATE>"
  -e HOST_CONTAINERNAME="qbittorrent-segfault"
  -e 'TCP_PORT_6881'='6881'
  -e 'UDP_PORT_6881'='6881'
  -e 'WEBUI_PORT'='8282'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://<PRIVATE>:[PORT:8282]/'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/qbittorrent-logo.png'
  -v '/mnt/user/<PRIVATE>':'/downloads':'rw'
  -v '/mnt/cache/appdata/<PRIVATE>':'/config':'rw' 'lscr.io/linuxserver/qbittorrent:libtorrentv1-release-4.5.2_v1.2.18-ls19'
069dc64a12a6d3436e6baf1877a90d65ce39780dcfd386d1acdea1b00a27f0b2
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

[custom-init] No custom files found, skipping...
WebUI will be started shortly after internal preparations. Please wait...
[ls.io-init] done.
Catching signal: SIGTERM
Exiting cleanly
```

**Comment by abiacco** [comment]
No change on ls20

**Comment by thespad** [comment]
As far as I can tell this is an upstream issue and not something we can do anything about. The only change between ls17 and ls18 was [a minor libcrypto bump](https://github.com/linuxserver/docker-qbittorrent/compare/libtorrentv1-release-4.5.2_v1.2.18-ls17...libtorrentv1-release-4.5.2_v1.2.18-ls18), which were security fixes so could have changed/broken something, but wouldn't be something we can change.

**Comment by abiacco** [comment]
I understand. I'll keep checking on future releases. You can close this if you want, otherwise I'll comment/close when I notice it's fixed
