### ISSUE TITLE
[FEAT] HEALTHCHECK as part of the Dockerfile

### ISSUE THREAD

**Issue by ZaxLofful** [linuxserver/docker-qbittorrent#239]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add a HEALTHCHECK line to the Dockerfile that will detect whether the WebUI is still working and report the container as unhealthy if its not.

### Reason for change

Sometimes the container just stops working, but is not reported as unhealthy; thus is not restarted by the Docker Daemon. The only way to solve this is to restart the container and sometimes the rest of the docker-compose stack.

### Proposed code change

Add the following line to the dockerfile:

`HEALTHCHECK --interval=5s --timeout=5s --start-period=10s --retries=3 CMD curl --fail --silent --show-error --retry 3 --max-time 5 http://localhost:8080`

**Comment by Roxedus** [comment]
A healthcheck in docker does not besides showing the container as unhealthy in `docker ps`. 

> not restarted by the Docker Daemon

A healtcheck does not instruct docker to restart a unhealthy container. 

This is a decision we apply to all our images.

**Comment by dexter74** [comment]
I need the healthcheck control to use the dependencies.

**Comment by j0nnymoe** [comment]
1) read the response and why it was closed.
2) why would you comment on a 3 year old issue.
