### ISSUE TITLE
[BUG] <title> 401 Unauthorized Error when running 4.5.3[latest] docker image

### ISSUE THREAD

**Issue by HaldenMemphis** [linuxserver/docker-qbittorrent#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

HI!

I noticed that in the latest 4.5.3 docker image, the qBittorrent.conf file is completely different from the configuration in 4.5.2. This causes a 401 unauthorized error when starting qBittorrent's WEBUI directly with docker. Do I need to change it to the original configuration?

Best Regards.

Yifan

### Steps To Reproduce

run the docker and check the qBittorrent.conf

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d \
  --name=bt \
  -e WEBUI_PORT=9833 \
  -p 10086:6881 \
  -p 10086:6881/udp \
  -p 8080:9833 \
  -v /storage:/downloads \
  -v /storage/config:/config/qBittorrent \
  linuxserver/qbittorrent
```

### Container logs

```bash
[AutoRun]
enabled=false
program=

[BitTorrent]
Session\DefaultSavePath=/downloads/
Session\Port=6881
Session\QueueingSystemEnabled=true
Session\TempPath=/downloads/incomplete/

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=4

[Network]
PortForwardingEnabled=false

[Preferences]
Connection\PortRangeMin=6881
Connection\UPnP=false
Downloads\SavePath=/downloads/
Downloads\TempPath=/downloads/incomplete/
WebUI\Address=*
WebUI\Port=9833
WebUI\ServerDomains=*
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
- qBittorrent.conf 1/27 3%
```

**Comment by brandan-schmitz** [comment]
I have this issue as well, I have even tried modifying the `/config/qBittorrent/qBittorrent.conf` to add in the following line as is suggested in https://github.com/qbittorrent/qBittorrent/issues/8095#issuecomment-472740702 however every time I add it and then restart the container it is being overwritten again.

```
WebUI\HostHeaderValidation=false
```

I have verified that my config folder is indeed being persisted, the config is just being overwritten even though it is existing in the persisted folder.

**Comment by O2theC** [comment]
I think I am having a similar error, using the latest image and it works fine if I go directly to the container with port but if I go to it through a proxy(in my case I am using an npm reverse proxy) then it is a blank page with Unauthorized in the top left, I also tried that config thing and it got rid of it for me

**Comment by O2theC** [comment]
still having the unauthorized issue but I got the config thing to stick by editing it while the container is down, I think, I am still new to docker and all this stuff

**Comment by O2theC** [comment]
so i figured out how to fix my situation, I had to turn off Enable Cross-Site Request Forgery (CSRF) protection under
Settings>WebUI>Security>CSRF Protection checkbox, while there could be an issue with the setting in the code, I think it is much more likely a me problem and that I didn't set up my networking stuff correctly, I also turned back on host head validation and it still works

**Comment by tarbib** [comment]
Same issue there : I get a "Unauthorized"
I tried this 
> WebUI\HostHeaderValidation=false

But did not work either.

**Comment by HaldenMemphis** [comment]
Try other versions, I think there is some problem with this image. Maybe you can use an older version.

**Comment by Neobond** [comment]
> Try other versions, I think there is some problem with this image. Maybe you can use an older version.

Do I just rebuild with something like: linuxserver/qbittorrent:4.5.3 ?

**Comment by Neobond** [comment]
Just to follow up, I eventually discovered that I had to remove Chrome site data and cache _globally_ for WebUI access to start working again. Removing site data and cookies just for the WebUI site was not enough.

**Comment by Hadatko** [comment]
Issue is still present. I have fresh installation

**Comment by j0nnymoe** [comment]
This isn't an issue with the container. It's because you're tripping qbittorrent CSRF protections (as explained in the readme)

**Comment by Hadatko** [comment]
That doesn't work for me, but it can be related to nginx configuration maybe

**Comment by Hadatko** [comment]
Actually this is weird. I deleted all cockies ,,..... And stil not working, but in incognito mode it works. This happened to me before also with other sites. So consider it as working. Thank you ;)

**Comment by aptalca** [comment]
Closing, not a bug.
