### ISSUE TITLE
[BUG] Bad image tags confuse dependency update tools

### ISSUE THREAD

**Issue by DerEnderKeks** [linuxserver/docker-qbittorrent#249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently the following tags of the image, which seem to be outdated anyway, confuse tools like Renovate, as they are a higher SemVer than the actual current versions:

- 14.2.0.99201912051435-6796-912b076ubuntu18.04.1-ls56
- 14.2.0.99201912180418-6819-118af03ubuntu18.04.1-ls57
- 14.2.0.99201912180418-6819-118af03ubuntu18.04.1-ls58
- 14.2.0.99201912180418-6819-118af03ubuntu18.04.1-ls59
- 14.2.0.99201912180418-6819-118af03ubuntu18.04.1-ls60
- 14.2.0.99201912180418-6819-118af03ubuntu18.04.1-ls61
- 14.2.0.99201912180418-6819-118af03ubuntu18.04.1-ls62
- 14.2.0.99201912180418-6819-118af03ubuntu18.04.1-ls63
- 14.2.0.99201912180418-6819-118af03ubuntu18.04.1-ls64
- 14.2.0.99202003190933-6820-2bf340aubuntu18.04.1-ls65
- 14.2.2.99202003250005-6939-3c17ad5ubuntu18.04.1-ls66
- 14.2.2.99202003250005-6939-3c17ad5ubuntu18.04.1-ls67
- 14.2.3.99202004020718-6939-3c17ad5ubuntu18.04.1-ls68
- 14.2.3.99202004021627-6962-29e9594ubuntu18.04.1-ls69
- 14.2.3.99202004021627-6962-29e9594ubuntu18.04.1-ls70
- 14.2.3.99202004021627-6962-29e9594ubuntu18.04.1-ls71
- 14.2.3.99202004172232-6962-29e9594ubuntu18.04.1-ls72
- 14.2.3.99202004172232-6962-29e9594ubuntu18.04.1-ls73
- 14.2.5.99202004250119-7015-2c65b79ubuntu18.04.1-ls76
- 14.2.5.99202004250119-7015-2c65b79ubuntu18.04.1-ls77
- 14.2.5.99202004250119-7015-2c65b79ubuntu18.04.1-ls78
- 14.2.5.99202004250119-7015-2c65b79ubuntu18.04.1-ls79
- 14.3.8.99202109100310-7422-338d9a084ubuntu20.04.1-ls156
- 14.3.8.99202110081405-7423-ac5c264e6ubuntu20.04.1-ls157
- 14.3.8.99202110120741-7429-1bae770b2ubuntu20.04.1-ls158
- 14.3.9.99202110311443-7435-01519b5e7ubuntu20.04.1-ls159
- 14.3.9.99202110311443-7435-01519b5e7ubuntu20.04.1-ls160
- 14.3.9.99202110311443-7435-01519b5e7ubuntu20.04.1-ls161
- 14.3.9.99202110311443-7435-01519b5e7ubuntu20.04.1-ls162
- 14.3.9.99202110311443-7435-01519b5e7ubuntu20.04.1-ls163
- 20.04.1
- 14.3.9.99202110311443-7435-01519b5e7ubuntu20.04.1-ls164
- 14.3.9.99202110311443-7435-01519b5e7ubuntu20.04.1-ls165
- 14.3.9.99202110311443-7435-01519b5e7ubuntu20.04.1-ls166
- 14.3.9

### Expected Behavior

The listed tags shouldn't exist. Please delete them.

### Steps To Reproduce

1. Use a dependency update tool like Renovate
2. The tools tries to update the image tag to `20.04.1`

### CPU architecture

x86-64

### Docker creation

```bash
Irrelevant
```

### Container logs

```bash
Irrelevant
```

**Comment by Roxedus** [comment]
We do not delete tags, this is a [decision we stand by](https://github.com/linuxserver/docker-prowlarr/issues/42). 

The version numbers you are seeing actually maps to real versions in the apt repo, which we used when this image was based on Ubuntu.

**Comment by cyclingwithelephants** [comment]
Can you suggest a workaround to this issue please? 

Appreciate the stance on not deleting tags, but this still is a problem when using tools like dependabot, renovate, etc - I'm completely unable to create automated dependency management for only this container in my lab

**Comment by aptalca** [comment]
https://www.linuxserver.io/blog/docker-tags-so-many-tags-so-little-time#semver-info
