### ISSUE TITLE
[FEAT] apt support

### ISSUE THREAD

**Issue by Tiebe-Vercoutter** [linuxserver/docker-qbittorrent#250]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Is there a possibility to install things via apt or apt-get?

### Reason for change

I wan't to add a wiregaurd interface local to my container

**Comment by Tiebe-Vercoutter** [comment]
whoopsie use apk

**Comment by Roxedus** [comment]
This image is based on Alpine, where the package manager is apk, which is available to you.
