### ISSUE TITLE
[BUG] Last few Mb's never finish

### ISSUE THREAD

**Issue by apsinghnandha** [linuxserver/docker-qbittorrent#252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Current version atleast two times torrent came to last few Mb's and then it kept on resting to same last Mb's. Torrent never finished downloading. Any suggestions why is this happening.

### Steps To Reproduce

- PUID=1001
- PGID=1001
- WEBUI_PORT=8004

### Environment

```markdown
- OS: Ubuntu
- How docker service was installed: via Portainer
```

### CPU architecture

arm64

### Docker creation

```bash
Docker portioner yml.
```

### Container logs

```bash
I dont have
```

**Comment by drizuid** [comment]
Closing this, OP didn't fill out the template. We do not support deploying/creating containers with portainer.
