### ISSUE TITLE
[FEAT] update 4.6

### ISSUE THREAD

**Issue by iamckun** [linuxserver/docker-qbittorrent#267]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

update [4.6](https://github.com/qbittorrent/qBittorrent/tree/release-4.6.0)

### Reason for change

latest 4.6.0

**Comment by thespad** [comment]
The images will be updated when the upstream packages are. In the case of the libtorrentv1 branch 4.6.0 has already been published; the Alpine packagers usually take a few days to push new releases.
