### ISSUE TITLE
[BUG] WEB ui fails to start

### ISSUE THREAD

**Issue by lkiiiiiz** [linuxserver/docker-qbittorrent#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

WEB UI does not start. No relevant logs available.

Inside the container I do see that qbittorrent is running
```
root@af8d31ec5e2a:/# ps aux | grep qbit
root          39  0.0  0.0    212    68 ?        S    22:00   0:00 s6-supervise svc-qbittorrent
root         140  0.0  0.0    224    92 ?        S    22:00   0:00 /package/admin/s6-2.11.3.2/command/s6-svlisten1 -U -- /run/s6-rc/servicedirs/svc-qbittorrent /package/admin/s6-2.11.3.2/command/s6-svc -u -- /run/s6-rc/servicedirs/svc-qbittorrent
abc          146  0.0  0.1  50508 29848 ?        Ssl  22:00   0:00 /usr/bin/qbittorrent-nox --webui-port=8080
```

But port 8080 is not being listened to
```
root@af8d31ec5e2a:/# netstat -plnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:6881          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.11:33743        0.0.0.0:*               LISTEN      -
tcp        0      0 172.18.0.11:6881        0.0.0.0:*               LISTEN      -
```

### Steps To Reproduce

I am just starting the continer with the same config as before and it does not start the web GUI

WebUI related `qBittorrent.conf`:
```
WebUI\Address=*
WebUI\AlternativeUIEnabled=false
WebUI\AuthSubnetWhitelist=192.168.1.0/24, 127.0.0.1/32
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\BanDuration=3600
WebUI\CSRFProtection=true
WebUI\ClickjackingProtection=true
WebUI\CustomHTTPHeaders=
WebUI\CustomHTTPHeadersEnabled=false
WebUI\HTTPS\CertificatePath=
WebUI\HTTPS\Enabled=false
WebUI\HTTPS\KeyPath=
WebUI\HostHeaderValidation=true
WebUI\LocalHostAuth=false
WebUI\MaxAuthenticationFailCount=5
WebUI\Password_PBKDF2=********
WebUI\Port=8080
WebUI\ReverseProxySupportEnabled=false
WebUI\RootFolder=
WebUI\SecureCookie=true
WebUI\ServerDomains=*
WebUI\SessionTimeout=3600
WebUI\TrustedReverseProxiesList=
WebUI\UseUPnP=true
WebUI\Username=admin
```

### Environment

```markdown
❯ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"

❯ docker -v
Docker version 24.0.7, build afdd53b

Docker is installed from the official ppa
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2.3"
services:
  # QBittorrent
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Vilnius
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - /media/hdd/:/media/hdd
    ports:
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    labels:
      - subdomain=qbittorrent
      - traefik.http.routers.qbittorrent.entrypoints=websecure
      - traefik.http.routers.qbittorrent.tls.certresolver=ssl
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8080
      - traefik.enable=true
```

### Container logs

```bash
❯ docker-compose logs qbittorrent
Attaching to qbittorrent
qbittorrent    | [migrations] started
qbittorrent    | [migrations] no migrations found
qbittorrent    | ───────────────────────────────────────
qbittorrent    |
qbittorrent    |       ██╗     ███████╗██╗ ██████╗
qbittorrent    |       ██║     ██╔════╝██║██╔═══██╗
qbittorrent    |       ██║     ███████╗██║██║   ██║
qbittorrent    |       ██║     ╚════██║██║██║   ██║
qbittorrent    |       ███████╗███████║██║╚██████╔╝
qbittorrent    |       ╚══════╝╚══════╝╚═╝ ╚═════╝
qbittorrent    |
qbittorrent    |    Brought to you by linuxserver.io
qbittorrent    | ───────────────────────────────────────
qbittorrent    |
qbittorrent    | To support LSIO projects visit:
qbittorrent    | https://www.linuxserver.io/donate/
qbittorrent    |
qbittorrent    | ───────────────────────────────────────
qbittorrent    | GID/UID
qbittorrent    | ───────────────────────────────────────
qbittorrent    |
qbittorrent    | User UID:    1001
qbittorrent    | User GID:    1001
qbittorrent    | ───────────────────────────────────────
qbittorrent    |
qbittorrent    | [custom-init] No custom files found, skipping...
qbittorrent    | WebUI will be started shortly after internal preparations. Please wait...
```

**Comment by vertuk** [comment]
You didn't expose port 8080 in docker-compose.

**Comment by aguadoenzo** [comment]
Same issue here. After a restart, the webUI is accessible from some time, but then becomes unavailable, with no error message in the logs.

@vertuk considering the labels, it's likely OP has his container sitting behind a reverse proxy

**Comment by drizuid** [comment]
We do not support traefik here which is likely what is causing your problem. In your compose examples, you're missing the required webui port, then in your set of logs, I see youi've not passed PUID/PGID which likely cause a permissions issue.  Remove all traefik config, follow our container readme, then see if it works. We have no plans to assist with any traefik issues and they are not a qbittorrent container issue.

**Comment by drizuid** [comment]
Closing this as the user has a config issue,  which doesnt not belong in ghi. They have joined discord and were told the same thing i mentioned above.

**Comment by lkiiiiiz** [comment]
How can this be related to traefik? The container itself ha nothing listening to the port 8080. If you like I can remove it, but it cannot affect the fact that the web ui listener is not starting inside the container.


Isn't this the config to set the PUID/PGID?
```
environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Vilnius
      - UMASK_SET=022
      - WEBUI_PORT=8080
```

**Comment by thespad** [comment]
It shouldn't be related (I'm running qbittorrent though traefik without any issues, technically twice), but you have an odd issue that none of us had seen before and that means we need to reduce the variables as much as possible: step one is remove the reverse proxy from the equation and connect directly.

**Comment by lkiiiiiz** [comment]
I have managed to find that the issue was with the files in  `config/qBittorrent/BT_backup` folder. After removing the folder it have started working again. So the issue is not related to the image - it is qbittorent itself hanging.

Also if someone will be looking - the flag to have more logs is `S6_VERBOSITY=2`

**Comment by AnLuoRidge** [comment]
@lkiiiiiz  Thank you so much! In my case, I found there's a huge (>60 MB) .fastresume file in my `BT_backup` folder. Once removed, everything is back to normal.

**Comment by supersaiyan81** [comment]
> I have managed to find that the issue was with the files in `config/qBittorrent/BT_backup` folder. After removing the folder it have started working again. So the issue is not related to the image - it is qbittorent itself hanging.
> 
> Also if someone will be looking - the flag to have more logs is `S6_VERBOSITY=2`

hello @lkiiiiiz , 
I am trying to following this step but unable to delete the folder. I am using windows Docker Desktop and keeps saying there is a write protect against the disc. any ideas would be appreciated

**Comment by j0nnymoe** [comment]
Don't use docker desktop.

**Comment by Forinil** [comment]
Just run into the same problem - for me, the issue was the lockfile as described here: #430
