### ISSUE TITLE
[FEAT] Allow to specify session cookie name

### ISSUE THREAD

**Issue by bassterror** [linuxserver/docker-qbittorrent#273]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

In release 4.6.0 qbittorrent introduced this feature where you should be able to specify the name of the session cookie. It is mentioned [here](https://www.qbittorrent.org/news) "WEBUI: WebAPI: Allow to specify session cookie name (glassez)". I'm not sure if this can be used in the current docker state, or I just can't figure it out.

### Reason for change

I'm running two instances of the docker-qbittorrent. They have separate ports, appdata directories, etc. Everything is fine, but they both use the same cookie in my browser. So if you have an open tab with one of the instances and you log into the other one, the first one is logged out. If you open the second one in "incognito tab" (or another browser) that is not happening. I believe this feature will resolve the issue. I appreciate this is not big deal, but still I think it's useful.

**Comment by thespad** [comment]
Looking at the code, in principle you should just be able to pass `DEFAULT_SESSION_COOKIE_NAME` into the container.

**Comment by bassterror** [comment]
Thank you for the quick answer! Unfortunately I tried and it isn't working. No change in behavior.

**Comment by thespad** [comment]
Re-reading the comments on that PR it doesn't look like they ever added the CLI or ENV option for setting it, only directly in the config file.

**Comment by thespad** [comment]
It also doesn't look like it's actually possible to set it from the WebUI. I'm not sure this actually works at all based on my tests.

**Comment by bassterror** [comment]
Yes, I tried adding:
WebAPI\SessionCookieName=
or
WebUI\SessionCookieName=

No result.

**Comment by thespad** [comment]
Comment on a related issue is

> Now it is possible to change session cookie nane only by manually editing the configuration file, and I highly doubt that it is necessary to add such an option to any kind of UI:

> I believe that in the vast majority of cases it will be used by no-GUI instances, so it is a waste of effort to add this option to the GUI, as for the WebUI itself, I also doubt usefulness of this option, since it must be configured before the instance is launched.

**Comment by thespad** [comment]
So, completely inexplicably, and in a break from every other setting, it needs to go outside all of the preferences sections of the conf file. i.e. right at the top like:
```ini
WebAPI\SessionCookieName=steve

[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/config/qBittorrent/logs
...
```

**Comment by thespad** [comment]
I'm not sure that makes any more sense compared to the existing settings, but thanks for letting us know.
