### ISSUE TITLE
[BUG] cURL request does not work

### ISSUE THREAD

**Issue by NGDM** [linuxserver/docker-qbittorrent#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have this docker running through `network_mode: 'service:gluetun'` together with another container.
cURL requests to this other container via localhost:port used to work, but since 4.6.1-r0-ls297 the requests don't arrive and they don't return.

I believe something changed in the c-ares package which causes this: https://github.com/linuxserver/docker-qbittorrent/compare/4.6.0-r0-ls296...4.6.1-r0-ls297 
It seems they changed something to their DNS resolver: https://c-ares.org/changelog.html

### Expected Behavior

cURL request arrives and returns. 

### Steps To Reproduce

1. Run 4.6.0-r0-ls296 in docker with network_mode via container A
2. Run different container B with running webservice on port X (container A has open port X)
3. Open console for qBit-docker and make cURL request via localhost:portX to webservice of container B
4. Request arrives, response received
5. Repeat steps 1-4 with 4.6.1-r0-ls297
6. Request never arrives, no response received, console stays open

### Environment

```markdown
- OS: Synology DSM 7 (Docker version 20.10.3, build 55f0773)
- How docker service was installed: Synology Package Center
```

### CPU architecture

x86-64

### Docker creation

```bash
qbittorrent:
    image: 'linuxserver/qbittorrent:4.6.1-r0-ls297'
    container_name: qbittorrent
    environment:
      - PGID=$DOCKER_GID
      - PUID=$DOCKER_DOWNLOAD_UID
      - TZ=$TZ
      - WEBUI_PORT=8080
      - UMASK=$UMASK
    volumes:
      - '$DOCKER_PATH/qbittorrent/config:/config:rw'
      - '$DOWNLOADS_PATH:/data/downloads:rw'
    network_mode: 'service:gluetun'
    restart: 'unless-stopped'
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1031
User GID:    65539
───────────────────────────────────────

[custom-init] No custom files found, skipping...
WebUI will be started shortly after internal preparations. Please wait...
Connection to localhost (127.0.0.1) 8080 port [tcp/http-alt] succeeded!
[ls.io-init] done.
```

**Comment by drizuid** [comment]
We do not offer support for tunneling a container through another.

**Comment by Outsmart2383** [comment]
@NGDM did you find a solution for this? Thanks!

**Comment by NGDM** [comment]
> @NGDM did you find a solution for this? Thanks!

It seems this got fixed along the way with a new c-ares version. 
Not sure when, but I'm on latest version now and am able to make local requests again from within the container.
