### ISSUE TITLE
[BUG] can't access WebUI after latest update

### ISSUE THREAD

**Issue by draculya666** [linuxserver/docker-qbittorrent#283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when accessig the IP I get this message in the browser "Unacceptable file type, only regular file is allowed."
The arr's are able to connect. Only the WebUI ins't. 
Already removed the docker mods for the custom theme args to no avail

### Steps To Reproduce

run the  docker

### Environment

```markdown
- OS:Unraid 6.12.6
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='qbittorrent'
  --net='bridge'
  -e TZ="Europe/London"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Dracul"
  -e HOST_CONTAINERNAME="qbittorrent"
  -e 'WEBUI_PORT'='8080'
  -e 'DOCKER_MODS'='ghcr.io/gilbn/theme.park:qbittorrent'
  -e 'TP_THEME'='overseerr'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8080]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/qbittorrent-logo.png'
  -p '8080:8080/tcp'
  -p '6881:6881/tcp'
  -p '6881:6881/udp'
  -v '/mnt/user/Transmission/Downloads/complete/':'/downloads':'rw'
  -v '/mnt/user/appdata/qbittorrent':'/config':'rw' 'lscr.io/linuxserver/qbittorrent:latest'
```

### Container logs

```bash
(I) 2024-01-14T14:59:12 - IP geolocation database loaded. Type: DBIP-Country-Lite. Build time: Mon Jan 1 23:14:23 2024.
(N) 2024-01-14T14:59:12 - Using custom WebUI. Location: "/themepark".
(W) 2024-01-14T14:59:12 - Couldn't load WebUI translation for selected locale (C).
(N) 2024-01-14T14:59:12 - WebUI: Now listening on IP: *, port: 8080
(N) 2024-01-14T14:59:28 - WebAPI login success. IP: ::ffff:172.17.0.1
(N) 2024-01-14T15:00:05 - WebAPI login success. IP: ::ffff:172.17.0.1
(N) 2024-01-14T15:00:08 - WebAPI login success. IP: ::ffff:172.17.0.1
(N) 2024-01-14T15:00:17 - WebAPI login success. IP: ::ffff:172.17.0.1
(W) 2024-01-14T15:01:46 - UPnP/NAT-PMP port mapping failed. Message: "could not map port using UPnP[172.17.0.9]: no router found"
(W) 2024-01-14T15:01:46 - UPnP/NAT-PMP port mapping failed. Message: "could not map port using UPnP[172.17.0.9]: no router found"
(W) 2024-01-14T15:01:46 - UPnP/NAT-PMP port mapping failed. Message: "could not map port using UPnP[172.17.0.9]: no router found"
```

**Comment by j0nnymoe** [comment]
Likely need to remove the custom webui location from your config.

**Comment by draculya666** [comment]
It looks like is not downloading the files and creating the /themepark folder.
I pulled this from the logs:

------------------------------
| qBittorrent theme.park Mod |
------------------------------
Variables set:
'APP_FILEPATH'=/config/qBittorrent/qBittorrent.conf
'TP_DISABLE_THEME'=
'TP_HOTIO'=
'TP_DOMAIN'=
'TP_COMMUNITY_THEME'=
'TP_SCHEME'=
'TP_THEME'=overseerr

No domain set, defaulting to theme-park.dev
No scheme set, defaulting to https
---------------------------------------
| Downloading WebUI files from github |
---------------------------------------

Downloading qBittorrent webui to "/themepark"..please wait

Download finished


Downloading qBittorrent webui icons to "/themepark/xxx"..please wait

Download finished

---------------------------------------
| Adding the stylesheet to html files |
---------------------------------------
Stylesheet set to overseerr on /themepark/public/index.html

**Comment by j0nnymoe** [comment]
You need to check in with the theme park mod to see if there are changes needed to be made.

**Comment by j0nnymoe** [comment]
While yes they have exclusive lsio env's (and Gilbn is part of our team) - they aren't developed exclusively by us and in our docker mod repo so you would need to report issues directly to them.
