### ISSUE TITLE
[FEAT]  Add support for setting the Torrent Port through the Environment Variables

### ISSUE THREAD

**Issue by AidanHarveyNelson** [linuxserver/docker-qbittorrent#287]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I want to be able to set the Torrent port on the Docker CLI or Compose config

### Reason for change

I have a pretty large compose file that sets up a number of activities and having to manually go in through the UI to switch the ports when upstream ports change is frustrating.

### Proposed code change

From reviewing the code in this repo this should be possible by modifying the `root/etc/s6-overlay/s6-rc.d/svc-qbittorrent/run` file.

I am happy to put a PR together for this later today.

**Comment by Znerox** [comment]
After I updated this image today, I see my torrent client was reset to port 6881. I see [here](https://hub.docker.com/r/linuxserver/qbittorrent) that I can now set an environment variable TORRENTING_PORT to set the torrent port, like @AidanHarveyNelson requested. It seems to me that this change had the unintended consequence of resetting everyone's port to 6881.

**Comment by aptalca** [comment]
Fixed in the latest. If your port changed due to that faulty image, you'll have to set it again in the gui after update.
