### ISSUE TITLE
[BUG] read errors on nfs/cifs shares and qbittorrent redownloads existing files

### ISSUE THREAD

**Issue by warlordattack** [linuxserver/docker-qbittorrent#289]
### qBittorrent & operating system versions

qbittorrent 4.6.3 docker

### What is the problem?

1/ 
i have rocky linux vm inside proxmox, with podman container for qbittorrrent (linuxserverio latest : 4.6.3)
this rocky linux mounts shares : nfs (docker data, shared by truenas) + cifs (media files storage from windows disk)
rocky linux got updated one night and rebooted 
now my qbittorrent sqlite database is dead (no torrents table, 0 bytes file size) : would be nicer to be able to use mariadb instead of sqlite (never had this situation with mariadb/mysql also stored on nfs share from truenas)
i had 6000 torrents there, all gone (sqlite file was 300mb before dead if i remeber, probably broke because was open by the program when rocky linux rebooted : the container probably recieved normal stop signal but qbittorrent did not close the sqlite file in time, then container probably recieved brutal termination signal after some time, if the sqlite file was not properly closed it was then destroyed)
but media files are OK
because now i know in my situation (nfs share) it's not a good idea to use sqlite, 
i switched back to old fastresume files instead of sqlite
so i try to add torrents in qbittorrent one by one and map them to existing already downloaded files
because once it redownoladed all existing media files i swithed docker path to media files to read only mode
so when i add a torrent i choose the right category (categories has path to files)
then i use force recheck option 
but unfortunatly force recheck does nothing
and the added torrent does not see the existing file and try to redownload it (and it works new file replace the same file that existed before the download, so there is no user permission problem)
Looks like read problem with cifs/nfs shares monted on rocky linux

2/
when i switched back from sqlite to fasttorrent files i now have new critical error messages : 

An error occurred while trying to open the log file. Logging to file is disabled.
and
Couldn't save torrent resume data to '/config/qBittorrent/BT_backup/13...ed.fastresume'. Error: Operation not permitted.

This is strange : the files are created and exist inside BT_backup folder when i add new torrent, but after .torrent and .fasttorrent is created the critical error above appears
And the qbittorrent.log also exists but is empty.
(perhaps same open/read problem when the file is on nfs share ? and i don't have this problem with my other containers witch data is on the same nfs share and they access media on the cifs share with no problem too)

So docker has correct user rights to the folder
But the error message persists
I tryed : 
-delete and recreate container
-delete and recreate BT_backup folder
-restart rocky linux
-reapply user rights on the truenas dataset where docker datafiles are located

### Steps to reproduce

install rocky linux + podman + qbittorrent linuxserverio latest 
inside rocky : 
-map cifs share from windows and put media files there
-map nfs share from truenas for docker data
add torrent file and download (using catégot with corresponding folder located on cifs share from windows)
then delete dorrent file without deleting media on cifs share 
then add this torrent again and map the same category/folder as first time 
it will ignore existing media file and redownload it

### Additional context

```
version: "3.7" 
services:
  srv_qb:
    container_name: ${C_QB}
    image: ${C_QB_IMG}
    restart: ${C_ALL_RESTART}
    mem_limit: 4g
    volumes:
      - ${REP_APPDATA}/${C_QB}:/config
      - ${REP_DOWNLOADS}/qb:/downloads
      - ${REP_TORRENT}:/torrent
      # new media
      - ${REP_X_PARTAGE}:/x-partage:ro
      - ${REP_X_PARTAGET}:/x-partage-t:ro
      - ${REP_Y_PARTAGE}:/y-partage:ro
      - ${REP_Y_PARTAGET}:/y-partage-t:ro
      - ${REP_Z_PARTAGE}:/z-partage:ro
      - ${REP_Z_PARTAGET}:/z-partage-t:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - WEBUI_PORT=${C_QB_6682} # hotio 28080
    labels:
      - "com.centurylinklabs.watchtower.enable=${C_QB_WT}"
    network_mode: container:${C_GLU}


REP_APPDATA=/mnt/mydocker/appdata # Z:\nas\v-docker\appdata
REP_TORRENT=/mnt/z/v-partage/torrent        # 
REP_DOWNLOADS=/mnt/z/v-partage/downloads    # 
REP_CACHE=/mnt/z/v-partage/cache            # 
REP_X_PARTAGE=/mnt/x/v-partage
REP_X_PARTAGET=/mnt/x/v-partaget
REP_Y_PARTAGE=/mnt/y/v-partage
REP_Y_PARTAGET=/mnt/y/v-partaget
REP_Z_PARTAGE=/mnt/z/v-partage
REP_Z_PARTAGET=/mnt/z/v-partaget

cat /etc/fstab 
/dev/mapper/rl-root     /                       xfs     defaults        0 0
UUID=4bbe1de1-d058-4e79-8068-4e6a97d0b287 /boot                   xfs     defaults        0 0
/dev/mapper/rl-swap     none                    swap    defaults        0 0
192.168.50.110:/mnt/nvme2t/lab/px-docker /mnt/mydocker nfs defaults
//192.168.50.114/x      /mnt/x  cifs    credentials=/mnt/ant.smbcred,uid=1000,gid=1000,iocharset=utf8,file_mode=0777,dir_mode=0777      0       0
//192.168.50.114/y      /mnt/y  cifs    credentials=/mnt/ant.smbcred,uid=1000,gid=1000,iocharset=utf8,file_mode=0777,dir_mode=0777      0       0
//192.168.50.114/z      /mnt/z  cifs    credentials=/mnt/ant.smbcred,uid=1000,gid=1000,iocharset=utf8,file_mode=0777,dir_mode=0777      0       0


```

### Log(s) & preferences file(s)

[watched_folders.json](https://github.com/qbittorrent/qBittorrent/files/14229050/watched_folders.json)
[qBittorrent.conf.txt](https://github.com/qbittorrent/qBittorrent/files/14229051/qBittorrent.conf.txt)
[categories.json](https://github.com/qbittorrent/qBittorrent/files/14229052/categories.json)
![2024-02-10_123623](https://github.com/qbittorrent/qBittorrent/assets/3226486/70c32a29-72bd-4ae1-97d3-330aeb53eab5)
![2024-02-10_123608](https://github.com/qbittorrent/qBittorrent/assets/3226486/017a926f-4497-4a38-92b0-88f568f50382)

**Comment by warlordattack** [comment]
A don't know if thi is linuxserverio or qbittorrent issue so also opened the same issue here : 
https://github.com/qbittorrent/qBittorrent/issues/20394

**Comment by j0nnymoe** [comment]
This is not a bug. This is permissions issues due to your setup. We don't test in podman / we don't support remote shares for `/config` mounts. Also you could be hitting just general issues with libtorrentv2, at least try our v1 branch.

https://docs.linuxserver.io/misc/support-policy/#unsupported

**Comment by warlordattack** [comment]
Thank you i will try

**Comment by blumoreno** [comment]
> we don't support remote shares for `/config` mounts. 
This solved my issue. Moved my config mount off the smb share.
