### ISSUE TITLE
[BUG]  Web UI fails to load after successful login

### ISSUE THREAD

**Issue by FafferMcgee** [linuxserver/docker-qbittorrent#293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A fresh install does not load the WebUI after a successful login.
I use the temporary password output to the docker log, but when it is entered the WebUI reloads.
If I input the incorrect password intentionally, I receive an error as expected.

### Steps To Reproduce

1. Install qbittorrent from user apps repository
2. Open docker container's consel
3. Log in to WebUI

### Environment

```markdown
- OS: Unraid 6.12.6
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='qbittorrent'
  --net='tigerproxy'
  -e TZ="America/New_York"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="tiger-hoard"
  -e HOST_CONTAINERNAME="qbittorrent"
  -e 'WEBUI_PORT'='8080'
  -e 'TORRENTING_PORT'='6881'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8080]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/qbittorrent-logo.png'
  -p '8080:8080/tcp'
  -p '6881:6881/tcp'
  -p '6881:6881/udp'
  -v '/mnt/user/data/torrents/':'/downloads':'rw'
  -v '/mnt/user/appdata/qbittorrent':'/config':'rw' 'lscr.io/linuxserver/qbittorrent'

6deff17809f784efe3dbc82813d2cd97dbd771b38f679589968b5ddca9dc6aac

The command finished successfully!
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

[custom-init] No custom files found, skipping...
WebUI will be started shortly after internal preparations. Please wait...

******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8080

The WebUI administrator username is: admin
The WebUI administrator password was not set. A temporary password is provided for this session: 3qLztU6DU
You should set your own password in program preferences.
Connection to localhost (127.0.0.1) 8080 port [tcp/http-alt] succeeded!
[ls.io-init] done.
```

**Comment by aptalca** [comment]
What do you mean by `WebUI reloads`?
What address are you going to? Reverse proxy? Browser cache?

**Comment by FafferMcgee** [comment]
I'm going to the local IP address to load the Web UI, which has the login page. 
When I log in, there's a brief moment as if it is trying to load an interface (or go to another page), but it just stays on the login page.

**Comment by FafferMcgee** [comment]
Update: When I use the Web UI directly from the docker containers (Image1) and try to log in it fails to load the Web UI. After a successful login, It still just shows the login fields (image 2).

Image1
![image](https://github.com/linuxserver/docker-qbittorrent/assets/21181504/de9fe67e-01a1-4cd4-a033-65a6d0ddf504)
Image2
![image](https://github.com/linuxserver/docker-qbittorrent/assets/21181504/7e5f0475-4423-4620-8ee7-058d294edf7f)


[But I found this entry](https://www.truenas.com/community/threads/issue-accessing-qbittorrent-web-ui.91784/post-636200) mentioning that manually entering the IP address into the browser works.

And it does, if I manually enter the address and log in, I can access the Web UI.

**Comment by david-christ** [comment]
I have an issue that sounds like it is the exact same.

* Start docker image, e.g. via the `docker run ...` command from https://docs.linuxserver.io/images/docker-qbittorrent
* Open browser to `http://SERVER:8080/`
* Check docker logs for password
* Enter `admin` and `<password from logs>`
* Brief flicker
* Login page again

(note also that when entering "random" credentials, i get the expected `Invalid Username or Password.` error message.

I tried the aforementioned "typing in the URL manually into the address bar", but without any success.

System: Synology DS415+, 

```
$ docker --version
Docker version 20.10.3, build 55f0773
```

**Comment by david-christ** [comment]
Small addition, I just grabbed an old, backed-up config directory from another setup from January. It was set up for a different port, and upon start, it overwrote the port with 8080, even though no overwriting environment variable was set.

The system from the backup starts up, and lets me log in, so I assume it must have something to do with fresh configs. I'd like to set up a new machine, so would prefer not to re-use the old config.
