### ISSUE TITLE
Unraid: Unable to Access WebUI (resolved after research)

### ISSUE THREAD

**Issue by drumtechphoto** [linuxserver/docker-qbittorrent#294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No WebUI access after an upgrade to the container sometime last week, container still works as normal otherwise.
- Been running behind GluetunVPN container.

### Expected Behavior

WebUI access, and proceed to log in as normal.

### Steps To Reproduce

1. Check container configs via Docker app
2. Confirmed all settings are correct.
3. Confirmed settings are correct for GluetunVPN container, including port mapping.
4. Check configs via cli, WebUI\Port=8080
5. I use port 8089 as an example.
6. Changed network from "none" to "vpn"
7. Removed --net=container:GluetunVPN
8. Saved settings, container started, checked logs, all appear normal.
9. "To control qBittorrent, access the WebUI at: http://localhost:8080"
10. This is odd because my port for WebUI has always been 8089.
11. WebUI still was still inaccessible.
12. Reverted settings, new error was "unauthorized" when access from http://serverip:8089.

I will post my resolution for others.

### Environment

```markdown
- OS: Unraid 6.12.8
- How docker service was installed: Docker / Community App Store.
```

### CPU architecture

x86-64

### Docker creation

```bash
qbittorrent-unraid

Repository:
lscr.io/linuxserver/qbittorrent

Support Thread:
https://github.com/linuxserver/docker-qbittorrent/issues/new/choose

Project Page:
https://www.qbittorrent.org/

Registry URL:
https://github.com/orgs/linuxserver/packages/container/package/qbittorrent

Icon URL:
https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/qbittorrent-logo.png

WebUI:
http://[IP]:[PORT:8089]
Extra Parameters:
--cap-add=NET_ADMIN --device /dev/net/tun --net=container:GluetunVPN
Post Arguments:

CPU Pinning: (allocated 4 CPUs)
CPU: 
HT:
Network Type:
None

Bash
Privileged:
OFF

Resume Files:
/mnt/user/appdata/qbittorrent/qBittorrent/data/resume/
Container Path: /resume

Download Path:
/mnt/user/data
Container Path: /data

Appdata:
/mnt/user/appdata/qbittorrent

Container Path: /config
Contains all relevant configuration files.

PUID:
99
Container Variable: PUID

PGID:
100
Container Variable: PGID

UMASK:
000

**Port is Mapped in GluetunVPN Container as per guides/Readme**
```

### Container logs

```bash
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

[custom-init] No custom files found, skipping...
WebUI will be started shortly after internal preparations. Please wait...

******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8080
```

**Comment by j0nnymoe** [comment]
With the information you've provided, it doesn't look like you've used the WEBUI_PORT variable within the docker template to change the webui port.

**Comment by drumtechphoto** [comment]
Steps for Resolution:

1. Researched, found fix >> (probably is more than one posting of this fix)
2. https://github.com/guillaumedsde/alpine-qbittorrent-openvpn/issues/42 
3. Yes its a separate OS & Repository/Maintainer. (A fix is a fix. still applies to qBittorrent)
4. Added the two following lines to the qBittorrent.conf file >>

WebUI\CSRFProtection=false
WebUI\ClickjackingProtection=false
**the maintainer posted the fix > https://github.com/guillaumedsde

5. Restarted the container, confimed WebUI access is working again.

Contents of qBittorrent.conf after the fix (yes private info removed):

Session\MaxConnections=500
Session\MaxConnectionsPerTorrent=100
Session\MaxUploads=500
Session\MaxUploadsPerTorrent=5
Session\PeXEnabled=false
Session\PieceExtentAffinity=true
Session\Port=26636
Session\Preallocation=true
Session\QueueingSystemEnabled=true
Session\ReannounceWhenAddressChanged=true
Session\SaveResumeDataInterval=6
Session\SeedChokingAlgorithm=RoundRobin
Session\SubcategoriesEnabled=true
Session\SuggestMode=true
Session\Tags=Public, IPT
Session\TempPath=/data/torrents/incomplete
Session\TempPathEnabled=true
Session\UseAlternativeGlobalSpeedLimit=true
TorrentFileSizeLimit=1048576000

[Core]
AutoDeleteAddedTorrentFile=IfAdded

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=6

[Network]
PortForwardingEnabled=true
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Advanced\RecheckOnCompletion=true
Connection\PortRangeMin=6881
Connection\UPnP=true
Downloads\SavePath=/downloads/
Downloads\TempPath=/downloads/incomplete/
General\Locale=en
MailNotification\req_auth=true
WebUI\Address=*
WebUI\CSRFProtection=false
WebUI\ClickjackingProtection=false
WebUI\HostHeaderValidation=false
WebUI\LocalHostAuth=false
WebUI\Password_PBKDF2=""
WebUI\Port=8080
WebUI\ServerDomains=*
WebUI\UseUPnP=true
WebUI\Username=username

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"

**Comment by j0nnymoe** [comment]
Disabling qbittorrent security is not a fix.

**Comment by drumtechphoto** [comment]
> Disabling qbittorrent security is not a fix.

You are correct, its a workaround for now.

> With the information you've provided, it doesn't look like you've used the WEBUI_PORT variable within the docker template to change the webui port.

I did try editing and changing to other ports, without resolution/fix.

Forgot to post, current version of the container is: 4.6.3-r0-ls314

**Comment by j0nnymoe** [comment]
There is nothing here to "fix". 

There is a WEBUI_PORT env which is documented here https://github.com/linuxserver/docker-qbittorrent?tab=readme-ov-file#webui_port-variable if you need to use a port other than the default 8080.

**Comment by drumtechphoto** [comment]
> There is nothing here to "fix".
> 
> There is a WEBUI_PORT env which is documented here https://github.com/linuxserver/docker-qbittorrent?tab=readme-ov-file#webui_port-variable if you need to use a port other than the default 8080.

Thanks for sharing, just reviewed the guide.  

After walking back through the steps I did, for some odd reason, the WebUI Port defaulted to port 8080 no matter what settings I changed via Docker config or via cli manually changing the qBittorrent.conf config file.
