### ISSUE TITLE
[BUG] No usable version of libssl was found 

### ISSUE THREAD

**Issue by rwtallant13** [linuxserver/docker-qbittorrent#298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot use internal qbt tool due to lack of libssl

### Expected Behavior

qbt works and lists torrents

### Steps To Reproduce

```
> docker exec -it qbittorrent qbt torrent list
Please use --ask-for-password or --password and ensure username/url are set
No usable version of libssl was found
/usr/bin/qbt: line 14:   351 Aborted                 (core dumped) /qbt/qbt "$@"
```

### Environment

```markdown
- OS: Debian bookworm
- How docker service was installed: docker repository
```

### CPU architecture

x86-64

### Docker creation

```bash
qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:pia"
    depends_on:
      - pia
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Canada/Eastern
      WEBUI_PORT: 8080
      DOCKER_MODS: linuxserver/mods:universal-package-install
      INSTALL_PACKAGES: py3-qbittorrent-api@testing
    sysctls:
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    volumes:
      - ./qbittorrent/config:/config
      - ./qbittorrent/alpine_repositories:/etc/apk/repositories
      - /data/media/downloads:/downloads
    restart: always
```

### Container logs

```bash
[mod-init] Running Docker Modification Logic
[mod-init] Adding linuxserver/mods:universal-package-install to container
[mod-init] Downloading linuxserver/mods:universal-package-install from lscr.io
[mod-init] Installing linuxserver/mods:universal-package-install
[mod-init] linuxserver/mods:universal-package-install applied to container
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

**** Adding py3-qbittorrent-api@testing to OS package install list ****
[mod-init] **** Installing all mod packages ****
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
(1/18) Installing py3-certifi-pyc (2023.11.17-r0)
(2/18) Installing py3-parsing (3.1.2-r0)
(3/18) Installing py3-parsing-pyc (3.1.2-r0)
(4/18) Installing py3-packaging (23.2-r0)
(5/18) Installing py3-packaging-pyc (23.2-r0)
(6/18) Installing py3-setuptools (69.1.1-r0)
(7/18) Installing py3-setuptools-pyc (69.1.1-r0)
(8/18) Installing py3-qbittorrent-api-pyc@testing (2024.2.59-r0)
(9/18) Installing py3-charset-normalizer (3.3.2-r0)
(10/18) Installing py3-charset-normalizer-pyc (3.3.2-r0)
(11/18) Installing py3-idna (3.6-r0)
(12/18) Installing py3-idna-pyc (3.6-r0)
(13/18) Installing py3-urllib3 (1.26.18-r0)
(14/18) Installing py3-urllib3-pyc (1.26.18-r0)
(15/18) Installing py3-requests-pyc (2.31.0-r1)
(16/18) Installing py3-certifi (2023.11.17-r0)
(17/18) Installing py3-requests (2.31.0-r1)
(18/18) Installing py3-qbittorrent-api@testing (2024.2.59-r0)
Executing busybox-1.36.1-r20.trigger
OK: 122 MiB in 97 packages
[custom-init] No custom files found, skipping...
WebUI will be started shortly after internal preparations. Please wait...

******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8080

[ls.io-init] done.
```

**Comment by thespad** [comment]
It appears that `qbt` is still inexplicably being built against openssl 1.1, which is now 6 months past EOL.

I've opened https://github.com/fedarovich/qbittorrent-cli/issues/103 but honestly I don't have a lot of hope given that they've allowed it to sit in an unsupported and broken state for this long.

**Comment by rwtallant13** [comment]
No. It isn't.

QBT is provided as part of the image. 

I've installed the qbittorrent api to use. Thats not what this post is about. 

https://github.com/linuxserver/docker-qbittorrent/issues/189

Reopening.

**Comment by rwtallant13** [comment]
> It appears that `qbt` is still inexplicably being built against openssl 1.1, which is now 6 months past EOL.
> 
> I've opened [fedarovich/qbittorrent-cli#103](https://github.com/fedarovich/qbittorrent-cli/issues/103) but honestly I don't have a lot of hope given that they've allowed it to sit in an unsupported and broken state for this long.

Oh I see. Oh well thanks anyway

**Comment by thespad** [comment]
As a temporary "fix" you can install the `openssl1.1-compat` package from the edge/testing repo, but who knows how much longer that will be available for.

**Comment by aptalca** [comment]
> No. It isn't.

> QBT is provided as part of the image.

Oops, I missed that the failing binary is `/usr/bin/qbt`. Apologies, reopening.

**Comment by tim-durrant** [comment]
Any update on this.  CLI tool was included back in 2022 according to this image's version history but obviously not even tested to connect to qbittorrent let alone do any operations... showstopper

**Comment by Roxedus** [comment]
Its been tested several times since inclusion, but as you can tell, using a CLI with qbittorrent is not the normal way we operate. 
The updates would be made in the issue Spad opened and linked above, that's the issue you need to ultimately follow. You can use the proposed workaround in the meantime.

**Comment by tim-durrant** [comment]
What tests were performed?  QBT can't even connect to a qBitTorrent Web UI

> As a temporary "fix" you can install the `openssl1.1-compat` package from the edge/testing repo, but who knows how much longer that will be available for.

Thanks for the workaround.  Just to be clear, are you saying that this package should be installed manually inside the container once it's running?

**Comment by thespad** [comment]
If you're exec'd in as root then the settings file will end up in /root/.qbt, if you exec in as abc it should end up in /config and persist.
