### ISSUE TITLE
[BUG] Can't access webUI with network_mode: service:gluetun

### ISSUE THREAD

**Issue by ljo123** [linuxserver/docker-qbittorrent#299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Just updated to the latest version with the new TORRENTING_PORT option and I can no longer access the webUI. My container uses the Gluetun template so the ports are opened in that container, not in the qbit one. Everything was working properly on the prior version. Logs show no errors.

Also is it necessary to set the TORRENTING_PORT in compose if I've already set it in the webUI?

### Expected Behavior

WebUI should be accessible.

### Steps To Reproduce

In compose I have the following:

Gluetun config has:
FIREWALL_VPN_INPUT_PORTS=1234
ports:
  - 8080:8080

qbit config has:
environment:
  - WEBUI_PORT=8080

Then in the qbit webUI options I set the port manually to 1234.

### Environment

```markdown
- OS: ubuntu 22.04
- How docker service was installed: convenience script
```

### CPU architecture

x86-64

### Docker creation

```bash
Full Docker compose:

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
      - /opt/docker/volumes/qbittorrent:/config
      - /mnt/downloads:/downloads
    network_mode: service:gluetun
    restart: unless-stopped
```

### Container logs

```bash
******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8080

Connection to localhost (127.0.0.1) 8080 port [tcp/*] succeeded!
[ls.io-init] done.
```

**Comment by j0nnymoe** [comment]
Does it work if you take gluetun out?

**Comment by ljo123** [comment]
> Does it work if you take gluetun out?

Yes. If change the compose to remove the port in gluetun, add it in qbit and also remove "network_mode: service:gluetun" then the webui is accessible again.

**Comment by j0nnymoe** [comment]
No that isn't needed to be set.

If it's a gluetun issue, it's outside of our support.

**Comment by ljo123** [comment]
I can confirm that it is a gluetun issue. False alarm thansk!
