### ISSUE TITLE
Ability to add packages

### ISSUE THREAD

**Issue by danpowell88** [linuxserver/docker-qbittorrent#3]
It would be cool if there is a variable where we could provide addtional packages to be installed during the build.

One of the common use cases would be to run unrar on torrent completion, this does also require the multiverse repository to be enabled as well.

**Comment by sparklyballs** [comment]
not something likely to be happening anytime soon.

but requesting packages to be added to the image itself is the better way forward.
also the image is based on alpine not ubuntu.

**Comment by danpowell88** [comment]
Sorry new to this, which image should I be running?

On 13 Jun. 2017 6:09 pm, "sparklyballs" <notifications@github.com> wrote:

Closed #3 <https://github.com/linuxserver/docker-qbittorrent/issues/3>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/linuxserver/docker-qbittorrent/issues/3#event-1120874047>,
or mute the thread
