### ISSUE TITLE
Unable to connect to seeds/peers

### ISSUE THREAD

**Issue by benze** [linuxserver/docker-qbittorrent#30]
I'm running linuxserver/qbittorrent (latest) and see my container launch as expected. However, none of my torrents are able to connect to any seeds or peers.

I'm launching the container as follows:
``` 
 docker run --rm --name qb_test -p 8080:8080 -e TZ="America/New_York" -p 6882:6882 -p 6882:6882/udp  linuxserver/qbittorrent
```

I've also created the appropriate port forwarding mappings in my router to allow port 6882 from the internet to my docker host port 6882.  I have futher tested the mapping using telnet from a public IP to ensure that I am able to connect qbittorrent in the container; the telnet connection gets established.

At this point, I'm not sure where I have to go track down this issue.  Is this a problem with the container?  with my docker host configuration?  Something completely different?

Docker Engine:
CentOS Linux release 7.5.1804 (Core)
Docker version 18.06.1-ce, build e68fc7a

I have nothing specific in the logs showing up either:
```
[eric@localhost ~]$  docker run --name qb_test -p 8080:8080 -e TZ="America/New_York" -p 6882:6882 -p 6882:6882/udp  linuxserver/qbittorrent
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

******** Information ********
To control qBittorrent, access the Web UI at http://localhost:8080
The Web UI administrator user name is: admin

```

Any suggestions what I can do to validate if it is the container, my host, or just some silly missing configuration?  If I install qbittorrent-nox on the host directly, then my seeds connect fine.

**Comment by homerr** [comment]
Recreate the container with the correct PUID and PGID environment variables set and lets go from there.

**Comment by homerr** [comment]
Going to close this as it appears to have gone stale - if you need support with using the container please join us in Discord where available team members and the community can offer you further assistance. 

https://discord.gg/YWrKVTn
