### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by djdjfjfkeocj** [linuxserver/docker-qbittorrent#300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

用nginx proxy manager给webui进行反向代理的时候无法访问，显示
![image](https://github.com/linuxserver/docker-qbittorrent/assets/78682444/c7fc5ae3-35e8-4647-ad1d-9cfee98ea7f9)
登录进去后显示
![image](https://github.com/linuxserver/docker-qbittorrent/assets/78682444/12216513-d30b-491e-a8dd-e644a0944db7)

### Steps To Reproduce

111

### Environment

```markdown
- OS:UNRIAD 6.12.8
- How docker service was installed:Community Applications
```

### CPU architecture

x86-64

### Docker creation

```bash
1111
```

### Container logs

```bash
11111
```

**Comment by homerr** [comment]
Not following reporting guidelines.
