### ISSUE TITLE
[BUG] File written to disk with wrong user ID

### ISSUE THREAD

**Issue by kyle-mcknight** [linuxserver/docker-qbittorrent#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The files written to disk have an incorrect UID of "1024".  This causes other containers running with UID 1026 to not be able properly access the files.

### Expected Behavior

The files are written using the UID specified in the PUID environment variable of my docker cmpose file.

### Steps To Reproduce

1. Using the docker compose provided in the docker creation step, this issue happens for me.

### Environment

```markdown
- OS: windows docker desktop using wsl backend
- How docker service was installed: docker desktop
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "3.8"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /some/path/qbittorrent:/config
      - /some/path:/data/downloads ### i've also used just '/downloads' with the same result
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1026
User GID:    100
───────────────────────────────────────
[custom-init] No custom files found, skipping...
WebUI will be started shortly after internal preparations. Please wait...
******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8080
[ls.io-init] done.
Connection to localhost (127.0.0.1) 8080 port [tcp/http-alt] succeeded!
```

**Comment by aptalca** [comment]
If qbit is running as user 1026, it is not possible for it to write things as 1024 or change ownership to 1024 afterwards.

You must have something else going on, perhaps related to wsl if you're using windows paths (ntfs)

**Comment by kyle-mcknight** [comment]
The volume on the host is a NFS mounted drive in WSL, I've got other linux server containers running that also use the same shared NFS with no problem. I looked at the other containers I have and I couldn't find a user ID 1024. I couldn't find a 1024 in my WSL distro either. Granted I'm no expert, I just looked at the /etc/passwd file. If there's another way to search for that user ID, i'd try

**Comment by j0nnymoe** [comment]
Sounds like you have your NFS share configured to use the UID/GID of the synology nas rather than respecting the uid of the container (1024 is the default admin user of synology).

**Comment by kyle-mcknight** [comment]
I just ran qbit as a windows application using the same folders, and when it writes, it gets the proper 'abc' user (when viewing the new files from inside the other servarr containers looking at the same volume).

The shared folder on the synology NAS is owned by a non-root admin user that uses 1026 and is in group 100 (the default synology users group). All files and folders show 1026 as the user. That's why I used 1026 for the qbit container. I guess this is where my knowledge ends; I'm not sure why files written from the qbit container would then use synology's admin user

**Comment by j0nnymoe** [comment]
To clarify that the container is working correctly, get it to download to a folder within WSL, and see if it applies the correct uid/gid.

**Comment by kyle-mcknight** [comment]
If I create a directory named 'downloads' on WSL in my home dir and give it user/group of 1026/users, then when i run qbit in a container as 1026/100 for the user/group IDs, then the file is created when downloading with the proper 1026/users ID and group.

And now as I write this, just like editing a paper with other people... I now remember that synology has a setting to map permissions. I think by default it maps all to the admin... hence... 1024. 

Thank you both for spending time on this.  

Closing out as not a bug. Tested with the proper mapping setting in the NFS permissions for the folder in synology.
