### ISSUE TITLE
[BUG] Config file overwritten when docker restart the container

### ISSUE THREAD

**Issue by kurushimeru** [linuxserver/docker-qbittorrent#303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've installed qBittorrent on my Asustor NAS. 

When it crashed or when I want to stop qBittorrent, when I relaunch it the config file is overwritten and I lost all my configuration. Worst, I loose all the list of torrent I've already added with histo of stats ...

### Expected Behavior

When I stop the service, I want to keep the configuration

### Steps To Reproduce

1. Go to App Central
2. Go to Installed app
3. Stop qBittorrent
4. Restart qBittorrent

### Environment

```markdown
- OS:
- How docker service was installed: through app center of Asustor
```

### CPU architecture

x86-64

### Docker creation

```bash
It was done automatically through the package
```

### Container logs

```bash
Not working, but when I launch sudo docker container logs

******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:18181

The WebUI administrator username is: admin
The WebUI administrator password was not set. A temporary password is provided for this session: XXXX
You should set your own password in program preferences.
Connection to localhost (127.0.0.1) 18181 port [tcp/*] succeeded!
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
crond[149]: USER root pid 3444 cmd run-parts /etc/periodic/15min
crond[149]: USER root pid 3464 cmd run-parts /etc/periodic/15min
qt.network.ssl: No functional TLS backend was found
crond[149]: USER root pid 3485 cmd run-parts /etc/periodic/15min
QIODevice::read (QProcess): device not open
Could not parse Nova search engine capabilities, msg:  
QIODevice::read (QProcess): device not open
Error:  
qt.network.ssl: No functional TLS backend was found
crond[149]: USER root pid 3499 cmd run-parts /etc/periodic/15min
crond[149]: USER root pid 3500 cmd run-parts /etc/periodic/hourly
```

**Comment by j0nnymoe** [comment]
We do not provide any of the packages for Asustor platform nor do we have any hardware to test this on. It sounds like it's not configured correctly as this doesn't happen on other platforms.

**Comment by kurushimeru** [comment]
Okay so this is not yours ? https://www.asustor.com/en/app_central/app_detail?id=990&type=

**Comment by thespad** [comment]
It looks like it's using our container but we are not Patrick and do not provide packaged apps for Asustor.
