### ISSUE TITLE
[BUG] ERR_CONNECTION_REFUSED on unraid

### ISSUE THREAD

**Issue by LordJABA** [linuxserver/docker-qbittorrent#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The container starts i have a message with a temporary passwords in logs but when i open the ip with port (http://192.168.0.11:8081/ - 8080 is already taken) i from other computer on the same LAN  get ERR_CONNECTION_REFUSED

### Expected Behavior

Opening the web ui

### Steps To Reproduce

Install linuxservers qbittorrent app setting non default port.
Try to open webUI - tried with multiple browsers

### Environment

```markdown
- OS:Unraid 6.12.10
- How docker service was installed: Unraid default + community apps
```

### CPU architecture

x86-64

### Docker creation

```bash
app settings dump:



qbittorrent
Overview:
The Qbittorrent(https://www.qbittorrent.org/) project aims to provide an open-source software alternative to µTorrent. qBittorrent is based on the Qt toolkit and libtorrent-rasterbar library.


Additional Requirements:
None Listed
Repository:
lscr.io/linuxserver/qbittorrent
Network Type:

Bridge
Console shell command:

Bash
Privileged:
OFF
WebUI:
8081
Container Port: 8080

Port: 6881:
Container Port: 6881
tcp connection port

Port: 6881:
Container Port: 6881
udp connection port

Path: /downloads:
/mnt/user/vault/downloads/

WEBUI_PORT:
8081

TORRENTING_PORT:
6881
```
```


### Container logs

```bash
Connection to localhost (127.0.0.1) 8081 port [tcp/tproxy] succeeded!
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

[custom-init] No custom files found, skipping...
WebUI will be started shortly after internal preparations. Please wait...

******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8081

The WebUI administrator username is: admin
The WebUI administrator password was not set. A temporary password is provided for this session: gTT7W74Sj
You should set your own password in program preferences.
[ls.io-init] done.
```

**Comment by j0nnymoe** [comment]
For the webui port , you've not got the host port/container port matching the port number you set for `WEBUI_PORT`.

**Comment by LordJABA** [comment]
@j0nnymoe  it it set:
 WEBUI_PORT:
8081

**Comment by LordJABA** [comment]
this port mapping from docker tab:
172.17.0.6:6881/TCP>192.168.0.11:6881
172.17.0.6:6881/UDP>192.168.0.11:6881
172.17.0.6:8080/TCP>192.168.0.11:8081

**Comment by LordJABA** [comment]
![image](https://github.com/linuxserver/docker-qbittorrent/assets/6648367/92d3c4d4-8e00-4eff-9fd3-6d3b042d20e2)

**Comment by j0nnymoe** [comment]
It's not set the same.
![Screenshot_20240515-074109](https://github.com/linuxserver/docker-qbittorrent/assets/10374553/227e8448-945c-4cbd-9809-da2b810ac3b6)

**Comment by j0nnymoe** [comment]
Both the host/container ports need to match your webui port as mentioned here: https://github.com/linuxserver/docker-qbittorrent?tab=readme-ov-file#webui_port-variable

**Comment by LordJABA** [comment]
so if the WebUI is set to 8081:
![image](https://github.com/linuxserver/docker-qbittorrent/assets/6648367/5b2a6a1b-89a8-47ca-9cf7-4e9d854ffc1d)
the WEBUI_PORT also needs to be set to 8081:
![image](https://github.com/linuxserver/docker-qbittorrent/assets/6648367/3c692dc8-bd6e-4b20-9fc9-7dd6b78fb2d1)
Or am I misunderstanding?

**Comment by LordJABA** [comment]
tried changing WEBUI_PORT to 8080 and I get `Unauthorized` as I  expected

**Comment by LordJABA** [comment]
Got it. Needed to change container port to also 8081- the issue is thats not allowed to be modified in unraid UI. Needed to remove default port mapping and add nee one 8081>8081
![image](https://github.com/linuxserver/docker-qbittorrent/assets/6648367/cdb23473-44bc-4122-b084-62e782b121c7)

thanks for pointing this out
maybe someone will find that helpful during first days on unraid
