### ISSUE TITLE
[BUG] Fastresume files being ignored

### ISSUE THREAD

**Issue by remy33** [linuxserver/docker-qbittorrent#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Fastresume has no impact on client, whenever container restart  all the torrents do 'checking'.

After fidling this does not happened if qbittorrent is set to use "SQlite database (experimental)"

### Expected Behavior

Files shouldn't be ignored and the download shall resume to be "seeding" without checking process, just like they're when enabling SQlite database.

### Steps To Reproduce

1. Have a torrent seeding.
2. Restart container ( docker restart qbittorrent , or docker compose up -d if changed settings) 
3. See that torrent is checked. 

### Environment

```markdown
- OS: 
Ubuntu20.04
- How docker service was installed: 
docker script from the official repository.
```

### CPU architecture

x86-64

### Docker creation

```bash
qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=XXXX
      - TORRENTING_PORT=XXXX
    volumes:
      - ./qbittorrent-config:/config
      - ./downloads:/downloads
    network_mode: service:wireguard
    restart: unless-stopped
```

### Container logs

```bash
There is no error shown in log:

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────

[custom-init] No custom files found, skipping...
QtSingleCoreApplication: listen on local socket failed, QLocalServer::listen: Unknown error 95
WebUI will be started shortly after internal preparations. Please wait...

******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:XXXX

Connection to localhost (::1) XXXX port [tcp/*] succeeded!
[ls.io-init] done.
Catching signal: SIGTERM
Exiting cleanly
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────
```

**Comment by remy33** [comment]
If additional feedback is needed, tell me what I should add. 
Maybe can we change the default container to use the experimental SQlite database?

**Comment by j0nnymoe** [comment]
Try using the required ENV's from our documentation and see if that helps. No other reports of this not working.

**Comment by remy33** [comment]
I tried with the default Environment from docs at first, maybe I messed up some setting? IDK since I use nearly default config.
Anyways, if no one else have it, I guess issue can be closed and if someone else will have the bug, they will know how to get around it and might contribute.

**Comment by j0nnymoe** [comment]
It could be a permissions issue, you haven't provided full volume paths and you really using be using the suggested env's for permissions etc.
