### ISSUE TITLE
[FEAT] Please reinstate qbittorrent-cli in the docker image. It's up to date.

### ISSUE THREAD

**Issue by mrfatboy** [linuxserver/docker-qbittorrent#316]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Please reinstate qbittorrent-cli in the docker image.  The developer of qbittorent-cli says it's up to date.  Please see his response here:

[qbitorrent-cli issues](https://github.com/fedarovich/qbittorrent-cli/issues/109#issuecomment-2230052898)

### Reason for change

Qbittorrent-cli is necessary for my qbittorrent docker container.

**Comment by aptalca** [comment]
Continuing the discussion in the linked issue: https://github.com/fedarovich/qbittorrent-cli/issues/109

**Comment by aptalca** [comment]
This was fixed in #317
