### ISSUE TITLE
[BUG] Cannot listen to certain addresses

### ISSUE THREAD

**Issue by Ador-able** [linuxserver/docker-qbittorrent#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have set up to listen to all addresses, but I cannot listen to certain addresses. The addresses can be seen in the webui 
![屏幕截图 2024-09-12 154322](https://github.com/user-attachments/assets/ab340a84-f02d-4a61-972a-4ebda7608440)
![屏幕截图 2024-09-12 154210](https://github.com/user-attachments/assets/24f40fed-62ce-48ca-9525-f5cef65f6b24)
This only occurs after the container is started, and when I change the listening address on the webui, I can correctly listen to all addresses.
### Expected Behavior

Correctly monitor all addresses

### Steps To Reproduce

1、docker
2、Configure macvlan and allocate it to qbit

### Environment

```markdown
- OS: Ubuntu 
- Network：macvlan ipv6
```

### CPU architecture

x86-64

### Docker creation

```bash
---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    mem_limit: 8192m
    container_name: qbittorrent
    networks:
      macvlan_network:
        ipv4_address: 192.168.3.193
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=000
      - TZ=Etc/UTC
      - WEBUI_PORT=28080
      - TORRENTING_PORT=26881
    volumes:
      - /mnt/data/Docker/Qbittorrent/config:/config
      - /mnt/big-storage/downloads/pt:/data/downloads/pt
      - /pt:/pt
    ports:
      - 28080:28080
      - 26881:26881
      - 26881:26881/udp
    restart: unless-stopped
networks:
  macvlan_network:
    external: true
    name: macvlan
```

### Container logs

```bash
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
Linuxserver.io version: 4.6.6-r0-ls349
Build-date: 2024-09-08T06:52:27+00:00
───────────────────────────────────────
    
[custom-init] No custom files found, skipping...
WebUI 将在内部准备不久后启动。请稍等…
******** 信息 ********
要控制 qBittorrent，请访问下列地址的 WebUI：http://localhost:28080
Connection to localhost (::1) 28080 port [tcp/*] succeeded!
[ls.io-init] done.
```

**Comment by drizuid** [comment]
Hello, we do not test, support, or generally recommend macvlan networks. You are welcome to join discord and discuss this in #other-support, but we will not provide support for this.
