### ISSUE TITLE
[BUG] WebUI Dark Mode Unreadable, no options to change in WebUI GUI

### ISSUE THREAD

**Issue by treverehrfurth** [linuxserver/docker-qbittorrent#325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I jsut updated to V5.0, running in a docker container, and the new WebUI is terrible and unreadable. 
The Download/Upload Torrents section is white background with grey text now and there is no way to change, use a custom theme or anything.
<img width="1540" alt="Screenshot 2024-09-30 at 2 52 34 PM" src="https://github.com/user-attachments/assets/cdfd5a51-1c70-4df5-9610-dc0f77c557c6">

Meanwhile my default Qbittorrent 4.6 on my Mac with no theme, just mac making the app dark mode looks fantastic.
<img width="1031" alt="Screenshot 2024-09-30 at 2 53 42 PM" src="https://github.com/user-attachments/assets/accf82f3-69a9-44d3-9720-d8e00e31bb5f">

I'm not sure if i'm just missing something or if this was a mistake to upgrade and this needs to be addressed.

### Steps To Reproduce

Run linuxserver docker image and open in web browser to visuals webUI

### Environment

```markdown
- OS: Ubuntu 22.04
- How docker service was installed: docker compose
```

### CPU architecture

x86-64

### Docker creation

```bash
docker-compose up -d
```

### Container logs

```bash
NA
```

**Comment by j0nnymoe** [comment]
You will need to seek support from qbittorrent directly as it's related to the app, not the container.

**Comment by SuperMario86** [comment]
I got the same, but when I reloaded the webpage ignoring the cache, everything showed up correctly. Firefox 130

**Comment by treverehrfurth** [comment]
Same actually, a few hours later it was all good, no idea what it was

**Comment by rupekeshan** [comment]
Clear cache in the browser or use incognito mode

**Comment by j0nnymoe** [comment]
Closing as it's not an issue with the container that needs fixing.
