### ISSUE TITLE
[BUG] read_only mode prevent plugin installation (to be confirmed)

### ISSUE THREAD

**Issue by jehon** [linuxserver/docker-qbittorrent#329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running docker with read_only = true, plugins are impossible to install:
neither work:
- check for update (should install the default plugins)
- install plugin

### Expected Behavior

When running "check for update", the plugins should come up "magically". They don't.

I think that in read_only mode either:
- the plugin folder need to be mounted from external, to allow writing in it
- the plugins impact some file somewhere

Anyway, I bit of documentation?

### Steps To Reproduce

1. start the docker as documented, with the read_only flag
2. go to search
3. bottom right: search plugins
4. use "check for update"
5. the list does not fill in
In non-read-only mode, the list fill in.

### Environment

```markdown
- OS: Linux Ubuntu
- How docker service was installed: snap
```

### CPU architecture

x86-64

### Docker creation

```bash
docker compose:

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    tmpfs:
      - /run:exec
    read_only: true # => prevent plugin installation
    environment:
      WEBUI_PORT: 8080
    expose:
      - 8080
```

### Container logs

```bash
nothing shown except normal startup
```

**Comment by j0nnymoe** [comment]
This is what I would expect to happen if you aren't mounting any external volumes.
No need to add additional documentation to the readme as read only is "best effort" support with our containers, all explained here: https://docs.linuxserver.io/misc/read-only/
