### ISSUE TITLE
Please use Qbittorrent version in tag name

### ISSUE THREAD

**Issue by Haxy89** [linuxserver/docker-qbittorrent#34]
Current tag name: 105 does not provide what QBittorrent version it uses.
Please, build tag name with used QBittorrent version.

**Comment by homerr** [comment]
This will come with the eventual transfer of this container to the new build environment. I can tell you that this release is based off of `QBITTORRENT_VER="4.1.3"`

**Comment by Haxy89** [comment]
I know it is based of 4.1.3.

I make pull linuxserver/docker-qbittorrent:105 now tell me what version it is based of after four weeks and read docker docs about tags. 
Build counter from Jenkins as a docker tag is a lame

**Comment by homerr** [comment]
Thanks for calling our work lame. It'll make us want to work even faster. 👍
