### ISSUE TITLE
Please release image with QBittorrent v4.1.4

### ISSUE THREAD

**Issue by Haxy89** [linuxserver/docker-qbittorrent#35]
Current latest tag is fo v4.1.3

**Comment by Schlesiger** [comment]
Yes, please release latest `v4.1.4`. I am experiencing a recurring crash with `v4.1.3`. `v4.1.4` [release notes](https://www.qbittorrent.org/news.php) mention fixing a crash bug.

**Comment by thelamer** [comment]
I would like to convert this repo to our new build process that will build whenever they release a new version, I have opened https://github.com/qbittorrent/qBittorrent/issues/10005 with their team. 
In the mean time I will open a PR to update the hard coded tag.

**Comment by Haxy89** [comment]
@thelamer 
This version needs at least libtorrent 1.1.10. Try to update this first https://github.com/linuxserver/docker-qbittorrent/pull/31

**Comment by thelamer** [comment]
@Haxy89 I tried 1.1.10 and 1.1.11 same results with both of them. We are not bombing out in the build process. I am not familiar with this program personally so not sure if there are deps missing from the final container post compilation.

**Comment by thelamer** [comment]
Adding python seems to get rid of that specific error , but the webUI is blank seems like something is missing on the backend or some kind of new dependency . 
Will have to play around with deps and see if anything can get this functioning in Alpine.

**Comment by thelamer** [comment]
After discussing this with the team it seems like the prudent course of action is to convert this into an Ubuntu base image. 
We try to do everything in our power to use alpine, but it seems like there is some kind of incompatibility that our team has been unable to identify with the latest version. 
The qbitorrent team already has a release pipeline in the form of a PPA, and should ensure stability and consistent releases in the future. 
Just updating the followers of this issue, when we have an image to test, your help in confirming functionality would also be much appreciated.

**Comment by sledgehammer999** [comment]
FYI, the python dependency was a fluke in v4.1.4. Python continues to be optional. In v4.1.5 python won't be queried if the user hasn't enabled the search engines functionality.

**Comment by thelamer** [comment]
@Haxy89 @sledgehammer999 @Schlesiger 
We have updated this image to use our new build process and rebased it to Ubuntu to pull from their PPA instead of github directly and compile. 
If any of you could certify functionality that would be much appreciated, so far we have only run the most basic loop testing of downloading test torrents. 

https://hub.docker.com/r/lsiodev/qbittorrent/tags/

These builds are now also multi arch, so if you are running amd64, armhf, or aarch64 you can simply pull the latest tag.

**Comment by j0nnymoe** [comment]
@Haxy89 @sledgehammer999 @Schlesiger Anyone managed to test the lsiodev version posted?

**Comment by Schlesiger** [comment]
Sorry I meant to write this earlier. Before the holidays I tried referencing the tag in my `docker-compose.yml` but Docker couldn't find it.

**Comment by thelamer** [comment]
@Schlesiger I can pull it fine, keep in mind if you are on arm host you can just use the latest tag, it is multi arched now and will pull the correct image for your arch. 
```
docker pull lsiodev/qbittorrent:latest
latest: Pulling from lsiodev/qbittorrent
84ed7d2f608f: Already exists 
59bb0f057aca: Pull complete 
3aa07d46a3c2: Pull complete 
90430af11f36: Pull complete 
c31b17b2414e: Pull complete 
30e4fa5682ea: Pull complete 
bc2608ce5bf1: Pull complete 
877dc2dfb541: Pull complete 
8d66af05ef0b: Pull complete 
225873ea04d5: Pull complete 
Digest: sha256:b1da3aeeea87eac224dfc50540793defda9774be2dda95590ae15c63029af910
Status: Downloaded newer image for lsiodev/qbittorrent:latest
```

**Comment by kamilmirza** [comment]
@thelamer @j0nnymoe 
multi arch build is working fine with latest tag on armhf
kudos to LinuxServer team for going multi arch

**Comment by ddellspe** [comment]
@thelamer @j0nnymoe Just tested with latest on amd64, works properly with no issues updating from the existing linuxserver/qbittorrent image

**Comment by j0nnymoe** [comment]
Excellent stuff - Thanks

**Comment by thelamer** [comment]
The ubuntu based image is now live closing out this issue
