### ISSUE TITLE
[FEAT] Better Sorting ("Completed on" drops downloading files to the bottom of the list)

### ISSUE THREAD

**Issue by TyrionKent** [linuxserver/docker-qbittorrent#351]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I'm not sure if this should be marked as bug instead of feature but...

Am I the only one having trouble sorting torrents by "Completed on" and having my Downloading torrents go to the bottom of the list? This only happens to me when using the containers webui. If i use qbittorrent on windows the list sorts leaving Downloading torrents on top... Also i've been reading it's possible to sort by multiple columns but have been unable to do so using the docker container.

### Reason for change

The sorting of the list behaves differently on windows than using docker. I'm not sure if its a bug, a feature that could be added or just different and i'm thinking too much about it.

**Comment by Roxedus** [comment]
This needs to be reported to qbittorrent directly.
