### ISSUE TITLE
[BUG] <title> Email not working

### ISSUE THREAD

**Issue by cr0wm4n** [linuxserver/docker-qbittorrent#352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am completing the email notifications in the settings, but when i click send test email button i get nothing. i have checked with tcpdump and i see no email traffic coming from the container,

### Expected Behavior

an email is sent

### Steps To Reproduce

install the container and configure per instructions, then change settings for the email and click the send test email button

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
I used the prebuilt container
```

### Container logs

```bash
nothing showing email
```

**Comment by aptalca** [comment]
Needs to be reported to qbittorrent devs
