### ISSUE TITLE
[FEAT] OPENVPN Support

### ISSUE THREAD

**Issue by IIIdefconIII** [linuxserver/docker-qbittorrent#355]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

wondering id VPN would be possible to able to work because there are forks around that already implented it

### Reason for change

private torrenting

### Proposed code change

no idea tbh

**Comment by Roxedus** [comment]
This would highly increase the support burden, which is not something we want. This is why we currently do not have this as a feature.

**Comment by IIIdefconIII** [comment]
> This would highly increase the support burden, which is not something we want. This is why we currently do not have this as a feature.

I Totally understand that, thanks for the quick follow up!, you might be able to think about it with the crew for a payment version, but then again youll get people crying with depricated stuff xD have a good one!

#archive
