### ISSUE TITLE
[BUG] /init failure - cant start container

### ISSUE THREAD

**Issue by albertusQuelle** [linuxserver/docker-qbittorrent#359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Start container qbittorrent failed: {"message":"failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: \"/init\": stat /init: no such file or directory: unknown"}.

### Steps To Reproduce

1. Synology DS918+
2. Container Manager
3. load this container
4. 

### Environment

```markdown
- OS:DSM 7.2.2-72806 Update 2
- How docker service was installed: package mgr
```

### CPU architecture

arm64

### Docker creation

```bash
docker run -d \
  --name=qbittorrent \
  -e PUID=1028 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -e WEBUI_PORT=8080 \
  -e TORRENTING_PORT=6881 \
  -p 8080:8080 \
  -p 49166:49166 \
  -v /volume1/docker/qbittorrent:/config \
  -v /volume1/video:/video`#optional` \
  --restart unless-stopped \
  lscr.io/linuxserver/qbittorrent:latest
```

### Container logs

```bash
empty, does not start
```

**Comment by Roxedus** [comment]
Have you tried to delete the local image, and pull it again?

**Comment by albertusQuelle** [comment]
Hi roxedus Yes I tried. And pulled the last image from registry Von meinem iPhone gesendetAm 25.12.2024 um 15:40 schrieb Roxedus ***@***.***>:﻿
Have you tried to delete the local image, and pull it again?

**Comment by albertusQuelle** [comment]
i removed a dangling qbittorrent image

![image](https://github.com/user-attachments/assets/0afa92b8-b085-4c1f-8ff9-21712d8626b6)

**Comment by aptalca** [comment]
This is why were repeatedly asking. As shown in the image, total reclaimed space being 0 means it did not get deleted.

**Comment by albertusQuelle** [comment]
Sure, got it. And i try - do you have more commands to enfore it somehow?

**Comment by albertusQuelle** [comment]
As the images were (to my knowledge) all deleted i downloaded it fresh from the registry. 

Same result
![image](https://github.com/user-attachments/assets/66a750cf-7978-468a-ba46-5ba3108a814b)

**Comment by albertusQuelle** [comment]
i went back to [5.0.2-r0-ls367](https://github.com/linuxserver/docker-qbittorrent/releases/tag/5.0.2-r0-ls367)

this works.. So i would deactivate automated updates via watchtower best possible imo

thx
