### ISSUE TITLE
Feature request: add in qbittorrent-cli for post download processing

### ISSUE THREAD

**Issue by devops-senpai** [linuxserver/docker-qbittorrent#40]
Please include https://github.com/fedarovich/qbittorrent-cli for those of us that use qbittorrent with things like radarr, sonarr etc. Using labels and the use of post download scripts we (at least myself) would like to do things such as use the qbittorrent-cli to do things such as once a download is finished and is hardlinked or copied over to our plex server there is a need to clean up such as deleting the torrent.  Having the qbittorrent-cli would make this process much easier.

I see that the qbittorrent-cli project uses dot-net which can be a very bulky install (especially to build). I am actually looking into using your docker image as well as another to do a multistage docker build so that I can just copy the resulting binary needed over. 
https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

I also would like to take this time to thank you for your work.

**Comment by thelamer** [comment]
Can you give me an actual example of how these binaries being inside this container is useful? 

Like a popular plugin/script that many people use kind of example.

**Comment by devops-senpai** [comment]
Mostly for post download actions. 
![post-download-actions](https://i.imgur.com/zIqNkMT.png)

For instance when a file has finished downloading:
```
#!/usr/bin/env

torrent_id=$1
torrent_path=$2
torrent_cat=$3

if [[ "${torrent_cat}" == "for_plex" ]] ; then
  # sync files to another server
  rsync -avz ${torrent_path} user@server:/path/to/plex/or/something
  # remove the torrent and delete the files
  qbt torrent delete -f ${torrent_id} 
else 
  echo "INFO: continuing to seed"
fi

**Comment by thelamer** [comment]
Upstream: https://github.com/fedarovich/qbittorrent-cli/issues/10

Blocking these changes until their repo is fixed.
