### ISSUE TITLE
Run External Program On Torrent Completion doesn't work

### ISSUE THREAD

**Issue by DjRicko** [linuxserver/docker-qbittorrent#54]
The feature to run an external program doesn't work, client never actually executes the program/script, nothing in log file either, it just does absolute nothing.

**Comment by Dulanic** [comment]
It works without problem here... what did you put in the WebUI?

![image](https://user-images.githubusercontent.com/2948206/65973859-9ec8c900-e431-11e9-8ac9-c700aacaf85e.png)

**Comment by thelamer** [comment]
Please use [our discord server](https://discord.gg/YWrKVTn) for general support.
