### ISSUE TITLE
Can you add the qbittorrent unstable packages as well?

### ISSUE THREAD

**Issue by victorhooi** [linuxserver/docker-qbittorrent#55]
The Dockerfile currently only downloads/installs the qbittorrent-stable branch packages.

Is it possible to add the qbittorrent-unstable packages as well?

https://launchpad.net/~qbittorrent-team/+archive/ubuntu/qbittorrent-unstable

This would let those who want to test with slightly more bleeding-edge packages.

**Comment by thelamer** [comment]
Yeah this makes sense will do
