### ISSUE TITLE
chown on Container Startup Hangs

### ISSUE THREAD

**Issue by dannyh** [linuxserver/docker-qbittorrent#56]
The container is not necessarily going to have the ability or permissions to change ownership of the /downloads directory. This causes the container to hang.

------------------------------

## Expected Behavior
qBitorrent should start

## Current Behavior
/var/run/s6/etc/cont-init.d/30-config:
```
# chown download directory if currently set to root
if [[ "$(stat -c '%U' /downloads)" != "abc" ]]; then
       chown -R abc:abc /downloads
fi
```

## Steps to Reproduce

1. Start the container down a /downloads directory with no permission to change or a filesystem that doesn't support ownership
2.
3.
4.

## Environment
**OS:**      Unraid
**CPU architecture:** x86_64  
**How docker service was installed:**      Unraid

## Command used to create docker container (run/create/compose/screenshot)
Unraid

**Comment by thelamer** [comment]
I cannot fathom a scenario where this container would exist with /downloads not having perms. 

In any case if you want to bypass this bind mount a different folder and use that , we don't require you use /downloads.

**Comment by luoye-fe** [comment]
#113
