### ISSUE TITLE
Include default jackett plugin

### ISSUE THREAD

**Issue by Dulanic** [linuxserver/docker-qbittorrent#59]
So this is mainly a request. By default, qBittorrent is supposed to come /w the Jackett search plugin installed. It seems to not be included here, can this be added?

https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin

```qBittorrent comes with few of search plugins. Although it is enough for most users, if you wish to add more search engines you can configure the Jackett plugin.```

**Comment by Nosirus** [comment]
+1 and change to python3 for future plugin updates

**Comment by burkasaurusrex** [comment]
> By default, qBittorrent is supposed to come /w the Jackett search plugin installed. It seems to not be included here, can this be added?

You should be able to click the "Search Plugins..." button in the bottom right and then "Check for updates". The default plugins will then be installed in your config folder so it persists between updates. You'll have to go in and edit the `jackett.json` file for your Jackett instance and then restart qBittorrent.

**Comment by j0nnymoe** [comment]
We consume packages directly from qbittorrent so no idea why they're missing. Do what @burkasaurusrex suggested :)
