### ISSUE TITLE
I lost my webui password

### ISSUE THREAD

**Issue by ali6681** [linuxserver/docker-qbittorrent#61]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

I forget my webui password, how can I find or reset the password?
## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:Ubuntu 18.04 LTS      
**CPU architecture:** x86_64
**How docker service was installed:**

**Comment by j0nnymoe** [comment]
https://github.com/qbittorrent/qBittorrent/wiki/Web-UI-password-locked-on-qBittorrent-NO-X-(qbittorrent-nox)

**Comment by ali6681** [comment]
I tried this, but the qBittorrent.conf file hasn't WebUI\Password_PBKDF2 option.

**Comment by robwolff3** [comment]
The github wiki post above worked for me.

**Comment by pvdochtend** [comment]
Worked also for me. Don't forget to FIRST stop the container. Because he will write the active config to the file.
I edited the file first and afterwards restart the docker. That didn't work :(

**Comment by rkbest13** [comment]
I am having the same issue  tried all the steps stop>edit>start. the config file does not have a WebUI\password. 
next is completely removed the container > deleted the folder with the conf and redeployed. but still cant get access. seems the main .conf file is somewhere else hidden. 
I am using the ubuntu>docker>portianer to install qbit. 
using CT from portainer templates ->https://raw.githubusercontent.com/Qballjos/portainer_templates/master/Template/template.json

**Comment by tomshomelab** [comment]
im having the exact same issue,
- editing the conf file and changing the password did not work for me
- removing the "lock=true" did not work
- removing the persistent storage from before i was locked out did not reset the password
- persistent storage is now not located where i had set it in the container
- now repulling the container does not re create the storage with the config file
- all default passwords do not work in the webgui. have tried using incognito too

**Comment by TheUncannyObserver** [comment]
I'm having this issue myself as well.  I don't know where the config is being stored, but even deleting the stack, the config folder on the drive, the image files, and redownloading everything does not give me a new default config. I'm at a loss as to what to do. The config file is definitely being stored somewhere and copied over instead of a fresh one being generated.

**Comment by noes14155** [comment]
Same for me using docker.   lscr.io/linuxserver/qbittorrent:latest cannot login.
Downgrading to lscr.io/linuxserver/qbittorrent:amd64-4.6.0 works.

**Comment by j0nnymoe** [comment]
@TheUncannyObserver it's not a bug, it's by design, it's because users don't bother to change default credentials. It's explained in their news page.
