### ISSUE TITLE
The docker can't use IPV6

### ISSUE THREAD

**Issue by kemaguagua** [linuxserver/docker-qbittorrent#63]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**      

## Docker logs

[https://github.com/qbittorrent/qBittorrent/pull/11592](url)
[https://github.com/qbittorrent/qBittorrent/issues/11561](url)

**Comment by j0nnymoe** [comment]
Closing as no additional info provided.
