### ISSUE TITLE
Feature request: environment variable for "port used for incoming connections"

### ISSUE THREAD

**Issue by burkasaurusrex** [linuxserver/docker-qbittorrent#64]
It would be cool if there was an env variable like "INCOMING_PORT" or something that set "port used for incoming connections" in the config as well as set which ports were exposed.

I'm using another container for a VPN that requests a forwarded port and stores that port in text file. Setting the environment variable with `-e FILE__INCOMING_PORT=/vpn/forwarded_port` would be awesome!

Thanks for the hard work!

**Comment by stumpylog** [comment]
I would also like to see someway to set this externally also, ideally in a way which supports user Docker compose as well.  Like an environment variable with the port, or a different one pointing to the file to read it from.

**Comment by stumpylog** [comment]
In case anyone finds it useful, I threw together a quick script with rewrites the qBittorrent configuration file and restarts the container, if the qBittorrent port doesn't match a forwarded port number.  Combined with a systemd timer, it does what I need.

Slightly tuned for my own setup, but hopefully adaptable to others'.

https://gist.github.com/stumpylog/5dc8f19460459c455d67a03485132187

**Comment by inquam** [comment]
I would like this too but I could see a mounted file that could contain the port to use and have the container use that. THis way one could use the gluetun Docker container (https://github.com/qdm12/gluetun) and have that create a forwarded port using PIA for instance and write that to the file. The port would then be picked up by Qbittorrent and used.

gluetun actually has support for a simple web api to get the port etc also that could be used, but would tie the two containers together a bit more then a generic file.

**Comment by gurmukhp** [comment]
+1 to this!

I have an openvpn container that creates a text file with the forwarded port. It'd be great if this txt file could be fed into this container so the correct incoming port was defined.

**Comment by j0nnymoe** [comment]
I don't think this is something we're interested in adding but if someone wants to submit a PR to the container to enable this feature, we will happily review it. :)

**Comment by norsemanGrey** [comment]
> In case anyone finds it useful, I threw together a quick script with rewrites the qBittorrent configuration file and restarts the container, if the qBittorrent port doesn't match a forwarded port number. Combined with a systemd timer, it does what I need.
> 
> Slightly tuned for my own setup, but hopefully adaptable to others'.
> 
> https://gist.github.com/stumpylog/5dc8f19460459c455d67a03485132187

Could I ask how you apply this to the container?

**Comment by stumpylog** [comment]
I tossed a README into the gist.  It's something you'd run externally to this container.  After a little configuration, it will use the VPN container API and qbittorrent API to update the listening port as needed.
