### ISSUE TITLE
Username and password authentication broken

### ISSUE THREAD

**Issue by budimanjojo** [linuxserver/docker-qbittorrent#65]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I can't log into qbittorrent, so I reset the password by deleting 2 lines in config/qBittorrent/qBittorrent.conf and managed to log in with default admin password. I changed the password again in the web ui, and it was working for a week and now I can't login again. I have sonarr, radarr, nzb360 accessing qbittorrent and they suddenly reporting to lost connection to qbittorrent. 

------------------------------

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**

**Comment by nomisunrider** [comment]
same problem as @budimanjojo

**Comment by j0nnymoe** [comment]
Test here and it's working as expected. There was an issue with qbittorrent during a major version change as explained on their changelog so I suspect this is the issue.

**Comment by nomisunrider** [comment]
I found the cause.  It is because the password hashing changed from qbittorrent >=4.2.0
Read here:

https://github.com/qbittorrent/qBittorrent/issues/11680
