### ISSUE TITLE
Feature Request: RSS feed support

### ISSUE THREAD

**Issue by aztech-azza** [linuxserver/docker-qbittorrent#66]
Is there a way to add RSS feed support from the original Qbittorrent project? Need the feature for automated download on Asustor NAS. Thanks in advance!

**Comment by gth7754125** [comment]
Use flexget.

**Comment by j0nnymoe** [comment]
@aztech-azza we consume binaries from the project itself so it's not something we're removing from it. https://github.com/linuxserver/docker-qbittorrent/blob/master/Dockerfile#L16
