### ISSUE TITLE
Feature request: python 3 instead of python 2

### ISSUE THREAD

**Issue by jackmurray** [linuxserver/docker-qbittorrent#67]
Is it possible to install the 'python3' package instead of 'python'(which actually points to python 2) in the Dockerfile? I would like to run a python script as a post-completion command and it'd be nice to be able to use python 3 to write this with. https://github.com/qbittorrent/qBittorrent/blob/master/INSTALL says that python3 (>= 3.3) is supported, although I haven't tried building a container from a modified Dockerfile to verify that it would actually work yet.

**Comment by ljcbaby** [comment]
I support this view. We do need python3.

**Comment by CHBMB** [comment]
https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

Will be helpful until we get around to this

**Comment by krootee** [comment]
+1.
Need python3 for many qbittorrent plugins.

**Comment by bigboo3000** [comment]
I created a folder named "custom-cont-init.d" in the config folder.
Then I created a python3 file in it with

`#!/bin/bash

echo "**** installing python3 ****"
apt-get update
apt-get install python3`

python3 installed correctly, now I can successfully add python3 search plugins in qbittorrent, but when I try to search something there is no result.

Any help?

**Comment by bigboo3000** [comment]
mhh it works only If I choose a specific plugin, when using "all plugins" it doesn't work
![Screenshot_2020-03-31 qBittorrent v4 2 2 Interface web](https://user-images.githubusercontent.com/16479698/78020165-35c6fd00-7351-11ea-858f-8a87c7c3aa81.png)
