### ISSUE TITLE
Cannot use "--net=container" option, "Error response from daemon: conflicting options"

### ISSUE THREAD

**Issue by thisaccountname** [linuxserver/docker-qbittorrent#72]
Super new to docker, but long story short:

I can run the default set of commands and get Qbit up and running just fine. However, adding `--net=container:vpn` throws the error 

> Error response from daemon: conflicting options: port publishing and the container type network mode

I am using Docker for Windows. Here is my command:

```
docker create --net=container:vpn 

--name=qbittorrent 

-e PUID=1000 

-e PGID=1000 

-e TZ=America/Los_Angeles 

-e UMASK_SET=022 

-e WEBUI_PORT=8080

-p 6881:6881 

-p 6881:6881/udp 

-p 8080:8080 

-v C:\DockerStuff\Qbit_Plain:/config 

-v B:\Download:/downloads 

--restart unless-stopped 

linuxserver/qbittorrent
```

**Comment by drizuid** [comment]
https://docs.docker.com/engine/reference/run/#network-settings
try `--network=container:vpn`

**Comment by 4C6D74** [comment]
You can't use the "-p" flag and the network type "container" at the same time. If you want to forward ports, you'll need to forward them in the other container, in your case "vpn"

**Comment by drizuid** [comment]
provided a link to the docker documentation on how to work through this, but we do not offer support for routing containers through a vpn. This isn't an issue with our container, so closing this.
