### ISSUE TITLE
Cannot use WebUI only in Chrome.

### ISSUE THREAD

**Issue by ralph0813** [linuxserver/docker-qbittorrent#75]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

Cannot use WebUI in Chrome.
------------------------------

## Current Behavior

Chrome returns HTTP ERROR 401, but it's fine in Safari.

## Steps to Reproduce

1. All the settings are default settings
2. Open the WebUI in chrome 

## Environment
**OS:**      unraid 6.8.1
**CPU architecture:** x86_64 
**How docker service was installed:**   unraid  default

## Command used to create docker container (run/create/compose/screenshot)
 unraid default 
![](https://raw.githubusercontent.com/ralph0813/PicGo/master/20200512103130.png?token=AMDJEQ35RFFOEPRO46BKWYC6XIFMG)

## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by brainrecall** [comment]
I hit this same issue. It would work in chrome if I went back to the address bar and added a "/" at the end of the URL.

To really fix it, go to Tools->Options->Web UI. Then uncheck "Enable Cross-Site Request Forgery (CSRF) protection" and then click Save. Then the web UI loaded first time every time.

**Comment by j0nnymoe** [comment]
known issue - which is why we provide the `WEBUI_PORT` variable to get around the CSRF protection.
