### ISSUE TITLE
Jackett is not working

### ISSUE THREAD

**Issue by fogkaspoker** [linuxserver/docker-qbittorrent#78]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
When going into http://<myIP>:9117/UI/Dashboard jackett should open. But I get a connection refused error. I am using portainer and the port 9117 has been mapped. the qBittorrent is working fine

## Steps to Reproduce

1. Install using portainer with this docker image and follow the steps.

## Environment
**OS:**      Proxmox latets
**CPU architecture:** arm64      
**How docker service was installed:** Using portainer      

## Docker logs

     
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 01-envfile: executing... 

[cont-init.d] 01-envfile: exited 0.

[cont-init.d] 10-adduser: executing... 

-------------------------------------

          _         ()

         | |  ___   _    __

         | | / __| | |  /  \ 

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/

Brought to you by linuxserver.io

-------------------------------------

To support LSIO projects visit:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------

User uid:    0

User gid:    0

-------------------------------------

[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 30-config: executing... 

[cont-init.d] 30-config: exited 0.

[cont-init.d] 99-custom-scripts: executing... 

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-scripts: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

Everything seems fine with the docker installation.

Thanks in advance for the help.
Jackett: api key error! Right-click this row and select 'Open description page' to open help. Configuration file: '/config/data/qBittorrent/nova3/engines/jackett.json'

the file is created

**Comment by j0nnymoe** [comment]
You seem to have posted this issue on the wrong GitHub repo.

**Comment by fogkaspoker** [comment]
Hello, Thanks for the answer.

I think this the right repository, I have installed:

Linuxserver/qbittorrent:latest

And I am having the mentioned issue. With the jackett that is supposed to be working on port 9117

Thanks in advance,
Regards.
