### ISSUE TITLE
Can't access webui since version 14

### ISSUE THREAD

**Issue by danpowell88** [linuxserver/docker-qbittorrent#8]
Unraid 6.3.5

![Setup](http://i.imgur.com/KRYe8f1.png)

Once I try to upgrade from any version past 14 I can no longer access the webui, this includes up to 21.

Thought this may be related to https://github.com/qbittorrent/qBittorrent/issues/6882 however it looks like 3.3.1.14 fixes this and that version should be in 21 I think.

**Comment by sparklyballs** [comment]
they implemented some CSRF "improvements" in 3.3.12  

which basically seem to have broken things "fixed" it in 3.3.14 but seems to think unraid is breaking csrf but works fine with my test bed ubuntu with the same settings

**Comment by danpowell88** [comment]
This does work to some extent if you dont do any additional port forwarding outside of the hosting environment.

For me I have the following setup
Unraid docker
docker port 8080: unraid port: 10000, specified all new appropriate flags and could access it successfully
nat port forwarding from my router for 10007 -> unraid 10000, this seems to trigger the CSRF issue, had to change my port forwarding to be 10000 -> 10000 to get around it.

Not a huge issue but something to potentially note in the readme

**Comment by sparklyballs** [comment]
read the "new" README
