### ISSUE TITLE
WebUI Display Error in chrome/chromium Edge

### ISSUE THREAD

**Issue by Czile-create** [linuxserver/docker-qbittorrent#80]
>version v4.2.5
>Windows 10 1909 Home

I install the docker in qnap container station, but when I open the webui in Chrome/Chromium Edge, the task list cannot display normally. In the sidebar, the number of tasks is normal, and the task classification is also normal. However, tasks are not displayed in the main interface.

But when I use chrome in Ubuntu 20.04LTS Home to open the WebUI, it displays normally. And when I open it on my phone/or in my Windows laptop but use wechat to open, it displays normally, too.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Web UI display normally.

## Current Behavior
When I open the webui in Chrome/Chromium Edge, the task list cannot display normally. In the sidebar, the number of tasks is normal, and the task classification is also normal. However, tasks are not displayed in the main interface.

## Environment
**OS:**      Win 10 1909 Home
**CPU architecture:** x86_64     
**How docker service was installed:**      Pull the docker in docker hub

**Comment by j0nnymoe** [comment]
Sounds like a configuration issue within your edge browser or general support for qbittorrent in edge. Nothing we can do so I would suggest asking on qbittorrent's forum.

**Comment by Czile-create** [comment]
> Sounds like a configuration issue within your edge browser or general support for qbittorrent in edge. Nothing we can do so I would suggest asking on qbittorrent's forum.

Drag to change the proportion of the left side bar and the main interface, the main interface has a great chance of turning into a white screen. At this time, stop dragging, and the main interface will remain white.
Please pay attention to my new update of the issue.

**Comment by tobbenb** [comment]
We don't develop the app, just package it. So you need to report the bug to the upstream developers.
