### ISSUE TITLE
Slow speeds after updating to latest docker image

### ISSUE THREAD

**Issue by darki73** [linuxserver/docker-qbittorrent#84]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

Total download speed should only be limited by the ISP speed.

## Current Behavior

I am on a fiber connection 
![image](https://user-images.githubusercontent.com/1318627/91430485-a3774680-e867-11ea-8ce5-ad8ee6395488.png)

![image](https://user-images.githubusercontent.com/1318627/91430084-86427800-e867-11ea-9129-d68e789a48d5.png)

Sometimes it even looks like that
![image](https://user-images.githubusercontent.com/1318627/91431148-a45ca800-e868-11ea-95f0-634e65661800.png)

But most of the time this is what i am getting (after the latest update)
![image](https://user-images.githubusercontent.com/1318627/91431191-b3dbf100-e868-11ea-8252-e1f1c4d4907a.png)

These are my settings
![image](https://user-images.githubusercontent.com/1318627/91431330-e5ed5300-e868-11ea-9953-8f73d9a217db.png)

## Steps to Reproduce

1. Install QBittorrent latest image (from 26 or 27 of august from Docker Hub)
2. Start the container and go into GUI
3. Add torrent
4. Watch it having multiple seeds (i have a torrent with 600+ seeds but still speed never goes above 500kb/s) and almost no speed

## Environment
**OS:**      Unraid 6.8.3
**CPU architecture:** x86_64/arm32/arm64      amd64
**How docker service was installed:**      Unraid out-of-the-box installation of Docker

## Command used to create docker container (run/create/compose/screenshot)

QBittorrent image from Apps section of Community Applications, just simple "image pull > start container" with default config

## Docker logs

```log
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by j0nnymoe** [comment]
No issues here testing with https://releases.ubuntu.com/20.04/ubuntu-20.04.1-desktop-amd64.iso.torrent
![image](https://user-images.githubusercontent.com/10374553/91487875-5797c200-e8a6-11ea-9491-1ac06985a018.png)

```root@Server:~# docker inspect -f '{{ index .Config.Labels "build_version" }}' qbittorrent
Linuxserver.io version:- 14.2.5.99202004250119-7015-2c65b79ubuntu18.04.1-ls89 Build-date:- 2020-08-26T04:11:09-04:00```
