### ISSUE TITLE
UMASK_SET - subfolders

### ISSUE THREAD

**Issue by au190** [linuxserver/docker-qbittorrent#87]
## Current Behavior
version: version-14.3.0.99202010231047-7094-260e48b70ubuntu18.04.1

If I change the UMASK_SET=007 the RW - group is not propagateing to subfolders.
Ex: /my_software - dir and files in it has RW access but 
/my_software/old - dir and files in it has just R access.
Is this good ?

All the child directorys and files has that permission as the root dir has.

**Comment by j0nnymoe** [comment]
Please try using `UMASK` instead.
