### ISSUE TITLE
default Web-UI does not shows almost all the available torrents

### ISSUE THREAD

**Issue by Skyzhu881** [linuxserver/docker-qbittorrent#88]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

qBittorrent default Web UI shows all the torrents, downloading or seeding or any status, over 200 torrents available on here

## Current Behavior

qBittorrent default Web UI show all torrent as 0. CANT see any torrent (except 1 torrent, even all the status show 0) on any status, category, tag or tracker. actually i have not set any category, tag. 
but, i can see all the torrents when i enable the 3rd-party web-ui. i like the default web-ui.

## Steps to Reproduce

1.i am not sure what i did. but i think the problem is i have enable HTTPS, and i disable it when my domain certificate expired.
2. maybe it occurs after i update the container version, but i am not sure
3.
4.

## Environment
**OS: ubuntu server 20.04.1 LTS
**CPU architecture:** x86_64/
**How docker service was installed:**

via docker-compose, here is my docker-compose file

version: "2.1"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - UMASK_SET=022
      - WEBUI_PORT=6080
    volumes:
      - /mnt/storage/docker/qbittorrent/config/:/config
      - /mnt/download/:/downloads
      - /mnt/storage/media/:/sto
    ports:
      - 49881:49881
      - 49881:49881/udp
      - 6080:6080 #WebUI
    restart: unless-stopped

## Command used to create docker container (run/create/compose/screenshot)

docker-compose up -d

## Docker logs

sky@ubuntu:/mnt/storage/docker/qbittorrent$ docker logs qbittorrent 
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
The legacy data directory '/config/data/qBittorrent/' is used. It is recommended to move its content to '/config/qBittorrent/'
The legacy data directory '/config/data/qBittorrent/' is used. It is recommended to move its content to '/config/qBittorrent/'
The legacy data directory '/config/data/qBittorrent/' is used. It is recommended to move its content to '/config/qBittorrent/'
The legacy data directory '/config/data/qBittorrent/' is used. It is recommended to move its content to '/config/qBittorrent/'
The legacy data directory '/config/data/qBittorrent/' is used. It is recommended to move its content to '/config/qBittorrent/'
The legacy data directory '/config/data/qBittorrent/' is used. It is recommended to move its content to '/config/qBittorrent/'
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
Catching signal: SIGTERM
Exiting cleanly
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svwait: fatal: timed out
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
The legacy data directory '/config/data/qBittorrent/' is used. It is recommended to move its content to '/config/qBittorrent/'
The legacy data directory '/config/data/qBittorrent/' is used. It is recommended to move its content to '/config/qBittorrent/'
The legacy data directory '/config/data/qBittorrent/' is used. It is recommended to move its content to '/config/qBittorrent/'
The legacy data directory '/config/data/qBittorrent/' is used. It is recommended to move its content to '/config/qBittorrent/'
The legacy data directory '/config/data/qBittorrent/' is used. It is recommended to move its content to '/config/qBittorrent/'

**Comment by Skyzhu881** [comment]
i am new here, i dont know have to attached file. so i update all the screenshot below to explain the issue

https://mega.nz/folder/y0AhAYiA#1g_Itd6TRlx6pM8qLU19Xw

**Comment by j0nnymoe** [comment]
We don't support enabled HTTPS inside the container. I would start the container from fresh as the 4.3 was a major upgrade. I deleted your screenshots due to containing copywrited material.

**Comment by Skyzhu881** [comment]
well, thank you for deleting..
but i had already disabled https, because my certificate was expired. any idea?

**Comment by j0nnymoe** [comment]
Like I said, I would start fresh as 4.3 was a major upgrade.

**Comment by Skyzhu881** [comment]
ok, thanks for your supporting.
