### ISSUE TITLE
Error 401 when used behind nginx reverse proxy

### ISSUE THREAD

**Issue by rokups** [linuxserver/docker-qbittorrent#9]
I have my docker containers run behind nginx reverse proxy. qbittorrent runs on default port 8080. nginx configured as follows:

```
server {
    listen 80;
    listen [::]:80;
    server_name torrents.lan;

    location / {
        proxy_buffering off;
        ;proxy_set_header Host 192.168.1.200:8080;  ; tried with and without.
        proxy_pass http://192.168.1.200:8080/;
    }
}
```
Loading WebUI fails to load images and css files with error 401. Attempt to log in also fails with error 401.

When loading WebUI directly everything works as expected.

Could this also be related to csrf "improvements"? I did not use qbittorrent container previously so i do not know if it used to work or not.

**Comment by aptalca** [comment]
This issue is really beyond the scope of our support of this container. If you can access the web ui at http://192.168.1.200:8080/ then our part is working properly.

Perhaps you can ask the qbittorrent folks on their forum/github

**Comment by rokups** [comment]
Okay, thank you for clarification and sorry for the noise ;)

**Comment by Ananthusubramanian** [comment]
Hi @rokups  ,

Good Day. Hope you had resolution. If not, disable the Cross-Site Request Forgery (CSRF) protection from qbittorrent

![image](https://user-images.githubusercontent.com/22250995/210105717-61c68277-3357-4437-9895-7984f1329bca.png)
