### ISSUE TITLE
SEARCH Plugins don't work

### ISSUE THREAD

**Issue by MaverickPOL** [linuxserver/docker-qbittorrent#90]
Hi i try to install search plugins to qbittorrent but it seems that they don't work.
I use conection with SOCKS5 if this matter.
I copy .py files manually to container, then add them in search tab. Search engines apperar in search tab but when i try to search anything nothing happens.
Maby there are some python dep missing?

Also maby we can have preinstalled search plugins in this image?

**Comment by nac6** [comment]
I am seeing the same issue. I updated the search plugins and they are all listed. But when I try to search nothing is found.

**Comment by j0nnymoe** [comment]
The socks5 issue is not a container issue but more an upstream issue with qbittorrent itself.
