### ISSUE TITLE
the latest version docker crashs

### ISSUE THREAD

**Issue by stephenzhou30** [linuxserver/docker-qbittorrent#91]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

When I update from linuxserver/qbittorrent:latest on 2rd Dec, It will be dead by accident ,no reason.
In latest 3 days, It died about 4,5 times.
The log just show "traceback", then I found "restart" will make it work again

## Environment
**OS:*unraid 6.8.2*
**CPU architecture:*amd x3421*

## Image details
ID | sha256:40537b1558c72e9e024f14b2afe0c57ab5aa5ca8b733ef2ade61aca1b238fddf
Size | 319 MB
Created | 2020-12-02 13:04:35
Build | Docker 19.03.13 on linux, amd64

## Docker logs
It just show traceback, nothing else!

**Comment by j0nnymoe** [comment]
Tested within the team and unable to replicate. As it's been rebased since, please try the latest version and report back if this is still an issue.
