### ISSUE TITLE
Correct README

### ISSUE THREAD

**Issue by sege5641** [linuxserver/docker-qbittorrent#94]
Remove the "<>" from the CLI copy/paste command.

typo in the docker cli command. New users will not understand the problem from the incorrect "<>" placed in the copy/paste command

```
-v </path/to/appdata/config>:/config \
  -v </path/to/downloads>:/downloads \
```

 ```
 -v /path/to/appdata/config:/config \
  -v /path/to/downloads:/downloads \
```

**Comment by j0nnymoe** [comment]
This was done.
