### ISSUE TITLE
Problem with qbittorrent web ui in latest image

### ISSUE THREAD

**Issue by Nurtalf** [linuxserver/docker-qbittorrent#97]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
I expect to see the torrents in the web UI.

## Current Behavior
No torrents in web UI

## Steps to Reproduce
- From the previous image (2 weeks ago), i did a "docker pull linuxserver/qbittorrent" and docker-compose up

## Environment
**OS:** Centos 8
**CPU architecture:** x86_64
**How docker service was installed:**
https://get.docker.com/

## Command used to create docker container (run/create/compose/screenshot)
version: '3.7'

services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    #image: 17d5acbcd8e1
    hostname: "qbittorrent"
    container_name: qbittorrent
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    ports:
      - 58947:58947
      - 58947:58947/udp
      - 8080:8080
    volumes:
      - /data/qbittorrent/config:/config
      - /download:/downloads

networks:
  default:
    name: dockernet
    external: true

## Docker logs
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by bigboo3000** [comment]
I have the same issue, could you please add the fix linked 5 days ago?

**Comment by j0nnymoe** [comment]
@bigboo3000 it hasn't been merged because we haven't tested it. Nothing to stopping you from doing what that script does manually if you need it right now 🙂

**Comment by zaggash** [comment]
Hey @j0nnymoe, remember me ? 🙋
I was part of the team back in time when Sparkyball was there :)

**Comment by j0nnymoe** [comment]
@zaggash oh yes! Long time no see - hope all is wall

**Comment by bigboo3000** [comment]
@j0nnymoe OK thanks for the quick response!

So I just have to copy all files from  /config/data/qBittorrent to the new /config/qBittorrent/ ?

If I understand correctly there is a problem with the proposed script because it copy only backup folder but not config files, like custom search engines.

And can you confirm that   /config/qBittorrent/ will be the correct folder from now on?

**Comment by zaggash** [comment]
@bigboo3000 What is the problem with the script?
It is not working for you?

Did you actually open the link I posted to answer your question?
https://github.com/qbittorrent/qBittorrent/blob/release-4.3.3/Changelog#L16

**Comment by bigboo3000** [comment]
@zaggash I copied manually everything inside /config/data/qBittorrent to the new /config/qBittorrent/
and it worked.

I didn't use your script, I'm a linux noob sorry, but I just quickly read it and I though it was just moving the /config/data/qBittorrent/BT_backup directory and not the others directories.

**Comment by zaggash** [comment]
Yes, the goal of the upper `docker exec` cmd is to restore the torrent files.
All my configuration files were already moved to the new location, only the torrent files were missing.

I do not know if more files are needed to be moved over.
I'm not using custom search engines, not sure where they are saved.

**Comment by j0nnymoe** [comment]
The fixed has been merged.
