### ISSUE TITLE
Incorrect free space reported on web ui when using mounted mergerfs volume

### ISSUE THREAD

**Issue by oglops** [linuxserver/docker-qbittorrent#99]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

It should report free space on web ui all mounted volumes

## Current Behavior

It does not report mounted volumes as free space, but only the free space in the container

## Steps to Reproduce

1. create mergerfs from remote nfs shares
2. use podman to create linuxserver.io container and mount mergerfs volume
3. access web ui and reported free space is wrong

## Environment
**OS:** Fedora 33 running on esxi ( which runs on mac mini 2011 mid)
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

podman installed from F33 official repo

## Command used to create docker container (run/create/compose/screenshot)

```
podman run -d \
  --pod=pt \
  --name=qbittorrent \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e WEBUI_PORT=8999 \
  -p 52001:52001 \
  -p 52001:52001/udp \
  -p 8999:8999 \
  -v /mnt/asustor2/apps/qbittorrent:/config \
  -v /data:/data \
  --restart unless-stopped \
  --replace ghcr.io/linuxserver/qbittorrent
```

**Comment by oglops** [comment]
I already found some clue about this issue, it was caused by out of date qt5.9.5  lib used in linuxserver.io image, I tried [another image](https://hub.docker.com/r/gists/qbittorrent) with qt 5.15.2, it works flawlessly.

https://bugreports.qt.io/browse/QTBUG-77059

linuxserver image
![Screenshot from 2021-02-09 16-13-20](https://user-images.githubusercontent.com/2757572/107450231-bde16b80-6af9-11eb-8de9-85772043d7e5.png)

gists image
![Screenshot from 2021-02-09 17-02-57](https://user-images.githubusercontent.com/2757572/107450198-a99d6e80-6af9-11eb-8d5f-4201126e9bbe.png)

It reports very low disk space 1.1G, but in fact I got 2.4T left 
![image](https://user-images.githubusercontent.com/2757572/107439036-4ce48880-6ae6-11eb-84f9-b696fb242390.png)

/data is mergerFS created from two nfs share, container created from below command

on the host system
```
# df -h
Filesystem             Size  Used Avail Use% Mounted on
devtmpfs               3.9G     0  3.9G   0% /dev
tmpfs                  3.9G   84K  3.9G   1% /dev/shm
tmpfs                  1.6G  1.9M  1.6G   1% /run
/dev/sda2               39G   38G  1.1G  98% /
/dev/sda2               39G   38G  1.1G  98% /home
tmpfs                  3.9G   40K  3.9G   1% /tmp
mergerFS               7.2T  4.8T  2.4T  67% /data
/dev/sda1              976M  183M  727M  21% /boot
asustor:/volume2/nfs2  3.6T  1.3T  2.4T  36% /mnt/asustor2
asustor:/volume1/nfs1  3.6T  3.5T   91G  98% /mnt/asustor1
tmpfs                  796M   92K  796M   1% /run/user/42
tmpfs                  796M   56K  796M   1% /run/user/1000
```
inside the container
```
root@pt:/# df -h
Filesystem                              Size  Used Avail Use% Mounted on
overlay                                  39G   38G  1.1G  98% /
mergerFS                                7.2T  4.8T  2.4T  67% /data
tmpfs                                    64M     0   64M   0% /dev
/dev/sda2                                39G   38G  1.1G  98% /downloads
asustor:/volume2/nfs2/apps/qbittorrent  3.6T  1.3T  2.4T  36% /config
tmpfs                                   1.6G  1.9M  1.6G   1% /etc/hosts
shm                                      63M  4.0K   63M   1% /dev/shm
devtmpfs                                3.9G     0  3.9G   0% /proc/keys
```

**Comment by oglops** [comment]
I tested with mounted nfs share too, it shows incorrect free space too. This affects flexget plugin logic if it relies on qbittorrent reported free space size.

**Comment by j0nnymoe** [comment]
I believe this will get fixed once the images is moved onto Ubuntu Focal.

**Comment by oglops** [comment]
I see.. there is a MR #100 already

**Comment by j0nnymoe** [comment]
@oglops this has been merged so should be working. Please comment if it's still an issue.
